# code/tools/patch_v2_8_fix3.py
"""
Patch script for v2.8.0-fix3.

Location:
    code/tools/patch_v2_8_fix3.py

Target:
    code/codegen/validate/prompt_generator.py

Applies two edits:

  1. Insert a new helper method `_timer_variable_names` immediately
     before `_format_global_definitions`.

  2. Replace the `# Variables` block inside `_format_global_definitions`
     so that auto-generated timer variables are excluded from
     <variables> (they are already shown under <timers>).

Safety features:
  - Backup once to prompt_generator.py.bak (kept on re-run).
  - Each edit uses a literal anchor and refuses to apply if the
    anchor is missing or appears more than once.
  - Idempotent: re-running after a successful apply does nothing.

Usage:
    cd C:\\Users\\user\\OneDrive\\ドキュメント\\GitHub\\StaTable\\code
    python tools\\patch_v2_8_fix3.py
"""
from __future__ import annotations

import sys
from pathlib import Path

# Resolve code/ from this file:  tools/patch_*.py -> parent.parent == code/
CODE_DIR = Path(__file__).resolve().parent.parent
TARGET = CODE_DIR / "codegen" / "validate" / "prompt_generator.py"


# ----------------------------------------------------------------------
# Edit 1: insert helper method
# ----------------------------------------------------------------------
ANCHOR_1 = "    # ---------- <global_definitions> ----------\n"

INSERT_1 = '''    def _timer_variable_names(self, gd) -> set:
        """Names of variables auto-generated by add_timer_variables().

        [v2.8.0-fix3]
          GlobalDefinitions.__init__ calls add_timer_variables(),
          which registers the timer_base and derived timers into
          gd.variables so the code generator can emit them. Those
          entries are already shown in <timers>, so we exclude them
          from <variables> to avoid duplication and to allow an
          empty GlobalDefinitions() to collapse to <global_definitions/>.
        """
        names = set()
        tb = getattr(gd, 'timer_base', None)
        if tb is not None:
            if getattr(tb, 'variable_name', ''):
                names.add(tb.variable_name)
            for d in getattr(tb, 'derived', None) or []:
                if getattr(d, 'variable_name', ''):
                    names.add(d.variable_name)
        for et in getattr(gd, 'extra_timers', None) or []:
            if getattr(et, 'variable_name', ''):
                names.add(et.variable_name)
            for d in getattr(et, 'derived', None) or []:
                if getattr(d, 'variable_name', ''):
                    names.add(d.variable_name)
        return names

'''


# ----------------------------------------------------------------------
# Edit 2: replace the # Variables block inside _format_global_definitions
# ----------------------------------------------------------------------
ANCHOR_2_OLD = '''        # Variables
        variables = getattr(gd, 'variables', None) or []
        if variables:
            v_lines = ["    <variables>"]
            for v in variables:
                v_attrs = [f'name="{_esc(v.name)}"',
                           f'type="{_esc(v.type)}"']
                if getattr(v, 'group', ''):
                    v_attrs.append(f'group="{_esc(v.group)}"')
                if getattr(v, 'description', ''):
                    v_attrs.append(
                        f'description="{_esc(v.description)}"')
                v_lines.append(
                    f'      <variable {" ".join(v_attrs)}/>')
            v_lines.append("    </variables>")
            sections.append("\\n".join(v_lines))
'''

ANCHOR_2_NEW = '''        # Variables
        # [v2.8.0-fix3] Exclude auto-generated timer variables;
        # they are already shown in <timers>.
        timer_names = self._timer_variable_names(gd)
        variables = [
            v for v in (getattr(gd, 'variables', None) or [])
            if v.name not in timer_names
        ]
        if variables:
            v_lines = ["    <variables>"]
            for v in variables:
                v_attrs = [f'name="{_esc(v.name)}"',
                           f'type="{_esc(v.type)}"']
                if getattr(v, 'group', ''):
                    v_attrs.append(f'group="{_esc(v.group)}"')
                if getattr(v, 'description', ''):
                    v_attrs.append(
                        f'description="{_esc(v.description)}"')
                v_lines.append(
                    f'      <variable {" ".join(v_attrs)}/>')
            v_lines.append("    </variables>")
            sections.append("\\n".join(v_lines))
'''


# ----------------------------------------------------------------------
# Helpers
# ----------------------------------------------------------------------
def _apply_edit(text: str, anchor: str, replacement: str, label: str) -> str:
    count = text.count(anchor)
    if count == 0:
        print(f"  [SKIP] {label}: anchor not found (already applied?)")
        return text
    if count > 1:
        print(f"  [FAIL] {label}: anchor found {count} times (expected 1)")
        raise SystemExit(1)
    print(f"  [APPLY] {label}: replacing 1 occurrence")
    return text.replace(anchor, replacement, 1)


def _insert_before(text: str, anchor: str, insert: str, label: str) -> str:
    if insert.strip() in text:
        print(f"  [SKIP] {label}: already present")
        return text
    count = text.count(anchor)
    if count == 0:
        print(f"  [FAIL] {label}: anchor not found")
        raise SystemExit(1)
    if count > 1:
        print(f"  [FAIL] {label}: anchor found {count} times (expected 1)")
        raise SystemExit(1)
    print(f"  [APPLY] {label}: inserting helper method")
    return text.replace(anchor, insert + anchor, 1)


# ----------------------------------------------------------------------
# Main
# ----------------------------------------------------------------------
def main() -> int:
    print("=" * 70)
    print("  v2.8.0-fix3 patch")
    print("=" * 70)

    if not TARGET.exists():
        print(f"[FAIL] target not found: {TARGET}")
        return 1

    print(f"Target: {TARGET}")
    original = TARGET.read_text(encoding="utf-8")

    backup = TARGET.with_suffix(TARGET.suffix + ".bak")
    if not backup.exists():
        backup.write_text(original, encoding="utf-8")
        print(f"Backup: {backup}")
    else:
        print(f"Backup: already exists, keeping {backup}")

    patched = _insert_before(
        original,
        ANCHOR_1,
        INSERT_1,
        "Edit 1 (_timer_variable_names)",
    )
    patched = _apply_edit(
        patched,
        ANCHOR_2_OLD,
        ANCHOR_2_NEW,
        "Edit 2 (exclude timer vars)",
    )

    if patched == original:
        print()
        print("[INFO] No changes were made (already up to date).")
        return 0

    TARGET.write_text(patched, encoding="utf-8")
    print()
    print("[DONE] prompt_generator.py patched.")
    print()
    print("Next:")
    print("  python tests\\test_v2_8_p1_ai_prompt.py")
    print("  python tests\\test_v2_2_p12_6.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())