/**
 * @file    statable_role_functions_Application.c
 * @brief   Role function implementations
 *
 * @note    Code auto-generated by StaTable
 *          - Manual editing is not recommended
 *          - To modify, use StaTable
 *
 * @date    2026-09-19 17:26:55
 */

/*==============================================================*/
 *  Include files
/*==============================================================*/

#include "statable_role_functions_Application.h"

/*==============================================================*/
 *  Role function implementations
/*==============================================================*/


/* ============================================================== */
/*  Transition ID constant                                        */
/* ============================================================== */
#define TRANSITION_ID_NONE   ((uint16_t)0xFFFF)


/* ============================================================== */
/*  Role function call site table (common struct)                 */
/*  Identify cells by {from_state, event} pair                    */
/* ============================================================== */
typedef struct {
    STATE_Application_t from_state;   /* source state */
    EVENT_Application_t event;        /* event */
} RoleFuncCallSiteEntry_Application_t;


/* Transition_GetId forward declaration (body at end of file) */
static uint16_t Transition_GetId(
    const TransitionContext_Application_t *transition,
    const RoleFuncCallSiteEntry_Application_t *table,
    uint16_t table_size);


/* --- call site table for InitSession --- */
static const RoleFuncCallSiteEntry_Application_t call_sites_InitSession[] = {
    { STATE_Application_Idle, EVENT_Application_START },
};
#define CALL_SITES_InitSession_COUNT \
    (sizeof(call_sites_InitSession) / sizeof(call_sites_InitSession[0]))


/* --- call site table for LogError --- */
static const RoleFuncCallSiteEntry_Application_t call_sites_LogError[] = {
    { STATE_Application_Idle, EVENT_Application_START },
};
#define CALL_SITES_LogError_COUNT \
    (sizeof(call_sites_LogError) / sizeof(call_sites_LogError[0]))


/* --- call site table for HandlePause --- */
static const RoleFuncCallSiteEntry_Application_t call_sites_HandlePause[] = {
    { STATE_Application_Active, EVENT_Application_PAUSE },
};
#define CALL_SITES_HandlePause_COUNT \
    (sizeof(call_sites_HandlePause) / sizeof(call_sites_HandlePause[0]))


/* --- call site table for HandleStop --- */
static const RoleFuncCallSiteEntry_Application_t call_sites_HandleStop[] = {
    { STATE_Application_Active, EVENT_Application_STOP },
};
#define CALL_SITES_HandleStop_COUNT \
    (sizeof(call_sites_HandleStop) / sizeof(call_sites_HandleStop[0]))


/* --- call site table for ResumeWork --- */
static const RoleFuncCallSiteEntry_Application_t call_sites_ResumeWork[] = {
    { STATE_Application_Waiting, EVENT_Application_RESUME },
};
#define CALL_SITES_ResumeWork_COUNT \
    (sizeof(call_sites_ResumeWork) / sizeof(call_sites_ResumeWork[0]))


/**
 * @brief  Role function: Init session
 * @note   Init session
 *
 * @note   Call sites:
 *         - [pre_action]  STATE_Application_Idle -[EVENT_Application_START]-> STATE_Application_Active
 */
int RoleFunc_App_InitSession(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Application_t from_state = STATE_Application_MAX;
    EVENT_Application_t event = EVENT_Application_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_InitSession, (uint16_t)CALL_SITES_InitSession_COUNT);

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const error_severity = &ctx->data.error_severity;  /* Error severity */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    uint8_t *const mode = &ctx->data.mode;  /* Operation mode */
    bool *const confirm = &ctx->data.confirm;  /* Confirm flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:App_InitSession]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:App_InitSession]] */

    return ret;
}

/**
 * @brief  Role function: Log error
 * @note   Log error
 *
 * @note   Call sites:
 *         - [else_action]  STATE_Application_Idle -[EVENT_Application_START]-> STATE_Application_Error
 */
int RoleFunc_App_LogError(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Application_t from_state = STATE_Application_MAX;
    EVENT_Application_t event = EVENT_Application_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_LogError, (uint16_t)CALL_SITES_LogError_COUNT);

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const error_severity = &ctx->data.error_severity;  /* Error severity */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    uint8_t *const mode = &ctx->data.mode;  /* Operation mode */
    bool *const confirm = &ctx->data.confirm;  /* Confirm flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:App_LogError]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:App_LogError]] */

    return ret;
}

/**
 * @brief  Role function: Handle pause
 * @note   Handle pause
 *
 * @note   Call sites:
 *         - [pre_action]  STATE_Application_Active -[EVENT_Application_PAUSE]-> STATE_Application_Waiting
 */
int RoleFunc_App_HandlePause(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Application_t from_state = STATE_Application_MAX;
    EVENT_Application_t event = EVENT_Application_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_HandlePause, (uint16_t)CALL_SITES_HandlePause_COUNT);

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const error_severity = &ctx->data.error_severity;  /* Error severity */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    uint8_t *const mode = &ctx->data.mode;  /* Operation mode */
    bool *const confirm = &ctx->data.confirm;  /* Confirm flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:App_HandlePause]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:App_HandlePause]] */

    return ret;
}

/**
 * @brief  Role function: Handle stop
 * @note   Handle stop
 *
 * @note   Call sites:
 *         - [pre_action]  STATE_Application_Active -[EVENT_Application_STOP]-> STATE_Application_Done
 */
int RoleFunc_App_HandleStop(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Application_t from_state = STATE_Application_MAX;
    EVENT_Application_t event = EVENT_Application_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_HandleStop, (uint16_t)CALL_SITES_HandleStop_COUNT);

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const error_severity = &ctx->data.error_severity;  /* Error severity */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    uint8_t *const mode = &ctx->data.mode;  /* Operation mode */
    bool *const confirm = &ctx->data.confirm;  /* Confirm flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:App_HandleStop]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:App_HandleStop]] */

    return ret;
}

/**
 * @brief  Role function: Resume work
 * @note   Resume work
 *
 * @note   Call sites:
 *         - [pre_action]  STATE_Application_Waiting -[EVENT_Application_RESUME]-> STATE_Application_Active
 */
int RoleFunc_App_ResumeWork(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Application_t from_state = STATE_Application_MAX;
    EVENT_Application_t event = EVENT_Application_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_ResumeWork, (uint16_t)CALL_SITES_ResumeWork_COUNT);

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const error_severity = &ctx->data.error_severity;  /* Error severity */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    uint8_t *const mode = &ctx->data.mode;  /* Operation mode */
    bool *const confirm = &ctx->data.confirm;  /* Confirm flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:App_ResumeWork]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:App_ResumeWork]] */

    return ret;
}



/* ============================================================== */
/*  Transition ID conversion (end of file)                        */
/*  Linearly scans the per-function call_sites table and          */
/*  returns the index of the matching entry.                      */
/*  Returns TRANSITION_ID_NONE if no match / transition==NULL.    */
/* ============================================================== */
/**
 * @brief  Convert transition info to a unique ID
 * @param  transition  Transition context (may be NULL)
 * @param  table       Call site table (may be NULL)
 * @param  table_size  Number of entries in the table
 * @return Index in the table (TRANSITION_ID_NONE if no match)
 */
static uint16_t Transition_GetId(
    const TransitionContext_Application_t *transition,
    const RoleFuncCallSiteEntry_Application_t *table,
    uint16_t table_size)
{
    uint16_t i;

    if (transition == NULL || table == NULL) {
        return TRANSITION_ID_NONE;
    }

    for (i = 0; i < table_size; i++) {
        if (table[i].from_state == transition->from_state &&
            table[i].event      == transition->event) {
            return i;
        }
    }
    return TRANSITION_ID_NONE;
}


/* ============================================================== */
/*  User-added area                                               */
/*  Code added here is preserved across regenerations             */
/* ============================================================== */
/* [[STABLE_USER_CODE_TAIL_START]] */
/* ユーザー追加コードをここに記述（ヘルパー関数など） */

/* [[STABLE_USER_CODE_TAIL_END]] */
