/**
 * @file    statable_transitions_Application.c
 * @brief   State transition logic
 *
 * @note    Code auto-generated by StaTable
 *          - Manual editing is not recommended
 *          - To modify, use StaTable
 *
 * @date    2026-09-18 21:42:39
 */

/*==============================================================*/
 *  Include files
/*==============================================================*/

#include "statable_transitions_Application.h"
#include "statable_role_functions_Application.h"

/*==============================================================*/
 *  State transition table
/*==============================================================*/

/* ===== Cell transition function forward declarations ===== */
static STATE_Application_t t_Boot_BOOT(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx);
static STATE_Application_t t_Init_START(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx);
static STATE_Application_t t_Running_PAUSE(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx);
static STATE_Application_t t_Running_STOP(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx);
static STATE_Application_t t_Paused_RESUME(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx);
static STATE_Application_t t_Paused_STOP(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx);


/* Transition function pointer type */
typedef STATE_Application_t (*TransitionFunc_Application_t)(
    const TransitionContext_Application_t *, SystemContext_t *);

/* ============================================================== */
/*  State transition table: rows=state, cols=event      */
/*  Global variable (externally accessible)                     */
/* ============================================================== */
const TransitionFunc_Application_t transition_table_Application
    [STATE_Application_MAX][EVENT_Application_MAX] = {
    /*           | BOOT           | START          | PAUSE           | RESUME          | STOP           */
    /* ---------+--------------+--------------+---------------+---------------+--------------*/
    /* Boot     */ { t_Boot_BOOT   , NULL          , NULL           , NULL           , NULL           },
    /* Init     */ { NULL          , t_Init_START  , NULL           , NULL           , NULL           },
    /* Running  */ { NULL          , NULL          , t_Running_PAUSE, NULL           , t_Running_STOP },
    /* Paused   */ { NULL          , NULL          , NULL           , t_Paused_RESUME, t_Paused_STOP  },
    /* Stopped  */ { NULL          , NULL          , NULL           , NULL           , NULL           },
};


/**
 * @brief  Cell transition: STATE_Application_Boot -[EVENT_Application_BOOT]-> Init
 */
static STATE_Application_t t_Boot_BOOT(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    STATE_Application_t next_state = transition->from_state;

    /* Transition[0] (unconditional) */
    if (1) {
        RoleFunc_Application_Boot(transition, ctx);
        next_state = STATE_Application_Init;
        return next_state;
    }

    return next_state;
}

/**
 * @brief  Cell transition: STATE_Application_Init -[EVENT_Application_START]-> Running
 */
static STATE_Application_t t_Init_START(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    STATE_Application_t next_state = transition->from_state;

    /* Transition[0] (unconditional) */
    if (1) {
        RoleFunc_Application_Start(transition, ctx);
        next_state = STATE_Application_Running;
        return next_state;
    }

    return next_state;
}

/**
 * @brief  Cell transition: STATE_Application_Running -[EVENT_Application_PAUSE]-> Paused
 */
static STATE_Application_t t_Running_PAUSE(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    STATE_Application_t next_state = transition->from_state;

    /* Transition[0] */
    if (counter > 0) {
        next_state = STATE_Application_Paused;
        return next_state;
    }

    /* Transition[1] */
    if (counter == 0) {
        next_state = STATE_Application_Running;
        return next_state;
    }

    return next_state;
}

/**
 * @brief  Cell transition: STATE_Application_Running -[EVENT_Application_STOP]-> Stopped
 */
static STATE_Application_t t_Running_STOP(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    STATE_Application_t next_state = transition->from_state;

    /* Transition[0] */
    if (g_system_tick > 100) {
        RoleFunc_Application_Pause(transition, ctx);
        next_state = STATE_Application_Stopped;
        return next_state;
    }

    return next_state;
}

/**
 * @brief  Cell transition: STATE_Application_Paused -[EVENT_Application_RESUME]-> Running
 */
static STATE_Application_t t_Paused_RESUME(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    STATE_Application_t next_state = transition->from_state;

    /* Transition[0] (unconditional) */
    if (1) {
        RoleFunc_Application_Resume(transition, ctx);
        next_state = STATE_Application_Running;
        return next_state;
    }

    return next_state;
}

/**
 * @brief  Cell transition: STATE_Application_Paused -[EVENT_Application_STOP]-> Stopped
 */
static STATE_Application_t t_Paused_STOP(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    STATE_Application_t next_state = transition->from_state;

    /* Transition[0] (unconditional) */
    if (1) {
        next_state = STATE_Application_Stopped;
        return next_state;
    }

    return next_state;
}


/*==============================================================*/
 *  State transition functions
/*==============================================================*/

/**
 * @brief  Application layer state transition processing
 * @param  current_state  Current state
 * @param  event          Event that occurred
 * @param  ctx            System context pointer
 * @return State after transition
 */
STATE_Application_t StateMachine_Process_Application(
    STATE_Application_t current_state,
    EVENT_Application_t event,
    SystemContext_t *ctx
)
{
    TransitionContext_Application_t transition = {
        .from_state = current_state,
        .event = event,
    };
    TransitionFunc_Application_t func = transition_table_Application[current_state][event];
    if (func != NULL) {
        return func(&transition, ctx);
    }
    return current_state;
}
