/**
 * @file    statable_role_functions_Application.h
 * @brief   Role function declarations
 *
 * @note    Code auto-generated by StaTable
 *          - Manual editing is not recommended
 *          - To modify, use StaTable
 *
 * @date    2026-09-18 21:42:39
 */

#ifndef STATABLE_ROLE_FUNCTIONS_H_APPLICATION
#define STATABLE_ROLE_FUNCTIONS_H_APPLICATION

/*==============================================================*/
 *  Include files
/*==============================================================*/

#include "statable_types_Application.h"

/*==============================================================*/
 *  Role function declarations
/*==============================================================*/

/**
 * @brief  Role function: アプリ起動
 * @note   アプリ起動
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Application_Boot(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: アプリ開始
 * @note   アプリ開始
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Application_Start(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: 一時停止処理
 * @note   一時停止処理
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Application_Pause(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: 再開処理
 * @note   再開処理
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Application_Resume(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: 周期処理（ISR用）
 * @note   周期処理（ISR用）
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Application_HandleTick(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: RX処理（ISR用）
 * @note   RX処理（ISR用）
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Application_HandleRx(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: エラー処理（ISR用）
 * @note   エラー処理（ISR用）
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Application_HandleError(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: ドライバ初期化
 * @note   ドライバ初期化
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Driver_Init(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: エラーログ
 * @note   エラーログ
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Driver_LogError(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: リセット処理
 * @note   リセット処理
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Driver_Reset(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: RX確認（ISR用）
 * @note   RX確認処理
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Driver_CheckRx(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: 接続処理
 * @note   接続処理
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Middleware_Connect(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: エラー処理
 * @note   エラー処理
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Middleware_HandleErr(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: 再試行処理
 * @note   再試行処理
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Middleware_Retry(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);



#endif /* STATABLE_ROLE_FUNCTIONS_H_APPLICATION */