/**
 * @file    statable_transitions_Application.h
 * @brief   State transition function declarations
 *
 * @note    Code auto-generated by StaTable
 *          - Manual editing is not recommended
 *          - To modify, use StaTable
 *
 * @date    2026-09-20 02:21:47
 */

#ifndef STATABLE_TRANSITIONS_H_APPLICATION
#define STATABLE_TRANSITIONS_H_APPLICATION

/*==============================================================
 *  Include files
 *==============================================================*/

#include "statable_types_Application.h"

/*==============================================================
 *  Function declarations
 *==============================================================*/

/**
 * @brief  State transition processing
 * @param  current_state  Current state
 * @param  event          Event that occurred
 * @param  ctx            System context pointer
 * @return State after transition
 */
STATE_Application_t StateMachine_Process_Application(
    STATE_Application_t current_state,
    EVENT_Application_t event,
    SystemContext_t *ctx
);

#endif /* STATABLE_TRANSITIONS_H_APPLICATION */