/**
 * @file    statable_transitions_Application.c
 * @brief   State transition logic
 *
 * @note    Code auto-generated by StaTable
 *          - Manual editing is not recommended
 *          - To modify, use StaTable
 *
 * @date    2026-09-19 17:26:55
 */

/*==============================================================*/
 *  Include files
/*==============================================================*/

#include "statable_transitions_Application.h"
#include "statable_role_functions_Application.h"

/*==============================================================*/
 *  State transition table
/*==============================================================*/

/* ===== Cell transition function forward declarations ===== */
static STATE_Application_t t_Idle_START(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx);
static STATE_Application_t t_Active_PAUSE(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx);
static STATE_Application_t t_Active_STOP(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx);
static STATE_Application_t t_Active_ERROR(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx);
static STATE_Application_t t_Waiting_RESUME(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx);
static STATE_Application_t t_Error_RESET(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx);


/* Transition function pointer type */
typedef STATE_Application_t (*TransitionFunc_Application_t)(
    const TransitionContext_Application_t *, SystemContext_t *);

/* ============================================================== */
/*  State transition table: rows=state, cols=event      */
/*  Global variable (externally accessible)                     */
/* ============================================================== */
const TransitionFunc_Application_t transition_table_Application
    [STATE_Application_MAX][EVENT_Application_MAX] = {
    /*           | START          | PAUSE          | RESUME           | STOP           | ERROR          | RESET          */
    /* ---------+--------------+--------------+----------------+--------------+--------------+--------------*/
    /* Idle     */ { t_Idle_START  , NULL          , NULL            , NULL          , NULL          , NULL           },
    /* Active   */ { NULL          , t_Active_PAUSE, NULL            , t_Active_STOP , t_Active_ERROR, NULL           },
    /* Waiting  */ { NULL          , NULL          , t_Waiting_RESUME, NULL          , NULL          , NULL           },
    /* Error    */ { NULL          , NULL          , NULL            , NULL          , NULL          , t_Error_RESET  },
    /* Done     */ { NULL          , NULL          , NULL            , NULL          , NULL          , NULL           },
};


/**
 * @brief  Cell transition: STATE_Application_Idle -[EVENT_Application_START]-> (multi)
 * @note   Transition count: 1
 */
static STATE_Application_t t_Idle_START(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    STATE_Application_t next_state = transition->from_state;
    bool _handled = false;

    /* ===== Cell actions (before_transitions) ===== */
    RoleFunc_App_PreCheck(transition, ctx);

    /* ===== Transition[T1] (Commit) ===== */
    if (!_handled && counter > 0) {
        RoleFunc_App_IdleExit(transition, ctx);  /* state exit */
        RoleFunc_App_InitSession(transition, ctx);
        next_state = STATE_Application_Active;
        RoleFunc_App_ActiveEntry1(transition, ctx);  /* state entry */
        RoleFunc_App_ActiveEntry2(transition, ctx);  /* state entry */
        _handled = true;
    } else if (!_handled && !(counter > 0)) {
        RoleFunc_App_IdleExit(transition, ctx);  /* state exit */
        RoleFunc_App_LogError(transition, ctx);
        next_state = STATE_Application_Error;
        RoleFunc_App_ErrorEntry(transition, ctx);  /* state entry */
        _handled = true;
    }

    /* ===== Cell actions (after_transitions) ===== */
    RoleFunc_App_Cleanup(transition, ctx);

    return next_state;
}

/**
 * @brief  Cell transition: STATE_Application_Active -[EVENT_Application_PAUSE]-> (multi)
 * @note   Transition count: 2
 */
static STATE_Application_t t_Active_PAUSE(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    STATE_Application_t next_state = transition->from_state;
    bool _handled = false;

    /* ===== Transition[T1] (Commit) ===== */
    if (!_handled && counter > 10) {
        RoleFunc_App_HandlePause(transition, ctx);
        next_state = STATE_Application_Waiting;
        RoleFunc_App_WaitEntry(transition, ctx);  /* state entry */
        _handled = true;
    }

    /* ===== Transition[T2] (Tentative) ===== */
    if (counter <= 10) {
        next_state = STATE_Application_Active;
        RoleFunc_App_ActiveEntry1(transition, ctx);  /* state entry */
        RoleFunc_App_ActiveEntry2(transition, ctx);  /* state entry */
    }

    return next_state;
}

/**
 * @brief  Cell transition: STATE_Application_Active -[EVENT_Application_STOP]-> (multi)
 * @note   Transition count: 3
 */
static STATE_Application_t t_Active_STOP(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    STATE_Application_t next_state = transition->from_state;
    bool _handled = false;

    /* ===== Group (shared_condition) ===== */
    if (running == true) {

        /* ===== Transition[T1] (Commit) ===== */
        if (!_handled && mode == 0) {
            RoleFunc_App_HandleStop(transition, ctx);
            next_state = STATE_Application_Done;
            _handled = true;
        }

        /* ===== Group (shared_condition) ===== */
        if (mode == 1) {

            /* ===== Transition[T2] (Commit) ===== */
            if (!_handled && confirm == true) {
                next_state = STATE_Application_Done;
                _handled = true;
            }

            /* ===== Transition[T3] (Tentative) ===== */
            if (confirm == false) {
                next_state = STATE_Application_Waiting;
                RoleFunc_App_WaitEntry(transition, ctx);  /* state entry */
            }
        }
    }

    return next_state;
}

/**
 * @brief  Cell transition: STATE_Application_Active -[EVENT_Application_ERROR]-> (multi)
 * @note   Transition count: 2
 */
static STATE_Application_t t_Active_ERROR(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    STATE_Application_t next_state = transition->from_state;
    bool _handled = false;

    /* ===== Group (shared_condition) ===== */
    if (error_severity > 0) {

        /* ===== Transition[T1] (Commit) ===== */
        if (!_handled && error_code == 1) {
            next_state = STATE_Application_Error;
            RoleFunc_App_ErrorEntry(transition, ctx);  /* state entry */
            _handled = true;
        }

        /* ===== Transition[T2] (Commit) ===== */
        if (!_handled && error_code == 2) {
            next_state = STATE_Application_Error;
            RoleFunc_App_ErrorEntry(transition, ctx);  /* state entry */
            _handled = true;
        }
    }

    return next_state;
}

/**
 * @brief  Cell transition: STATE_Application_Waiting -[EVENT_Application_RESUME]-> (multi)
 * @note   Transition count: 1
 */
static STATE_Application_t t_Waiting_RESUME(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    STATE_Application_t next_state = transition->from_state;
    bool _handled = false;

    /* ===== Transition[T1] (Commit) ===== */
    if (!_handled && 1) {
        RoleFunc_App_WaitExit(transition, ctx);  /* state exit */
        RoleFunc_App_ResumeWork(transition, ctx);
        next_state = STATE_Application_Active;
        RoleFunc_App_ActiveEntry1(transition, ctx);  /* state entry */
        RoleFunc_App_ActiveEntry2(transition, ctx);  /* state entry */
        _handled = true;
    }

    return next_state;
}

/**
 * @brief  Cell transition: STATE_Application_Error -[EVENT_Application_RESET]-> (multi)
 * @note   Transition count: 2
 */
static STATE_Application_t t_Error_RESET(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    STATE_Application_t next_state = transition->from_state;
    bool _handled = false;

    /* ===== Cell actions (before_transitions) ===== */
    RoleFunc_App_LogReset(transition, ctx);

    /* ===== Transition[T1] (Commit) ===== */
    if (!_handled && retry_count < 3) {
        RoleFunc_App_ErrorExit(transition, ctx);  /* state exit */
        next_state = STATE_Application_Idle;
        RoleFunc_App_IdleEntry(transition, ctx);  /* state entry */
        _handled = true;
    }

    /* ===== Transition[T2] (Commit) ===== */
    if (!_handled && retry_count >= 3) {
        RoleFunc_App_ErrorExit(transition, ctx);  /* state exit */
        next_state = STATE_Application_Done;
        _handled = true;
    }

    /* ===== Cell actions (after_transitions) ===== */
    RoleFunc_App_Cleanup(transition, ctx);

    return next_state;
}


/*==============================================================*/
 *  State transition functions
/*==============================================================*/

/**
 * @brief  Application layer state transition processing
 * @param  current_state  Current state
 * @param  event          Event that occurred
 * @param  ctx            System context pointer
 * @return State after transition
 */
STATE_Application_t StateMachine_Process_Application(
    STATE_Application_t current_state,
    EVENT_Application_t event,
    SystemContext_t *ctx
)
{
    TransitionContext_Application_t transition = {
        .from_state = current_state,
        .event = event,
    };
    TransitionFunc_Application_t func = transition_table_Application[current_state][event];
    if (func != NULL) {
        return func(&transition, ctx);
    }
    return current_state;
}
