/**
 * @file    statable_role_functions_Application.h
 * @brief   Role function declarations
 *
 * @note    Code auto-generated by StaTable
 *          - Manual editing is not recommended
 *          - To modify, use StaTable
 *
 * @date    2026-09-20 08:37:00
 */

#ifndef STATABLE_ROLE_FUNCTIONS_H_APPLICATION
#define STATABLE_ROLE_FUNCTIONS_H_APPLICATION

/*==============================================================
 *  Include files
 *==============================================================*/

#include "statable_types_Application.h"

/*==============================================================
 *  Role function declarations
 *==============================================================*/

/**
 * @brief  Role function: Boot entry
 * @note   Boot entry
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_BootEntry(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Boot exit
 * @note   Boot exit
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_BootExit(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Init entry
 * @note   Init entry
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_InitEntry(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Running entry 1
 * @note   Running entry 1
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_RunEntry1(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Running entry 2
 * @note   Running entry 2
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_RunEntry2(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Paused entry
 * @note   Paused entry
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_PauseEntry(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Stopped entry
 * @note   Stopped entry
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_StopEntry(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: App boot
 * @note   App boot
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_Boot(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: App start
 * @note   App start
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_Start(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: App pause
 * @note   App pause
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_Pause(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: App resume
 * @note   App resume
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_Resume(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Handle stop
 * @note   Handle stop
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_HandleStop(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Pre-check
 * @note   Pre-check
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_PreCheck(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Cleanup
 * @note   Cleanup
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_Cleanup(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Pre (before transitions)
 * @note   Runs before evaluating transitions
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_Pre(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Post (after transitions)
 * @note   Runs after evaluating transitions
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_Post(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);



#endif /* STATABLE_ROLE_FUNCTIONS_H_APPLICATION */