/**
 * @file    statable_role_functions_Application.c
 * @brief   Role function implementations
 *
 * @note    Code auto-generated by StaTable
 *          - Manual editing is not recommended
 *          - To modify, use StaTable
 *
 * @date    2026-09-18 21:42:39
 */

/*==============================================================*/
 *  Include files
/*==============================================================*/

#include "statable_role_functions_Application.h"

/*==============================================================*/
 *  Role function implementations
/*==============================================================*/


/* ============================================================== */
/*  Transition ID constant                                        */
/* ============================================================== */
#define TRANSITION_ID_NONE   ((uint16_t)0xFFFF)


/* ============================================================== */
/*  Role function call site table (common struct)                 */
/*  Identify cells by {from_state, event} pair                    */
/* ============================================================== */
typedef struct {
    STATE_Application_t from_state;   /* source state */
    EVENT_Application_t event;        /* event */
} RoleFuncCallSiteEntry_Application_t;


/* Transition_GetId forward declaration (body at end of file) */
static uint16_t Transition_GetId(
    const TransitionContext_Application_t *transition,
    const RoleFuncCallSiteEntry_Application_t *table,
    uint16_t table_size);


/* --- call site table for Boot --- */
static const RoleFuncCallSiteEntry_Application_t call_sites_Boot[] = {
    { STATE_Application_Boot, EVENT_Application_BOOT },
};
#define CALL_SITES_Boot_COUNT \
    (sizeof(call_sites_Boot) / sizeof(call_sites_Boot[0]))


/* --- call site table for Start --- */
static const RoleFuncCallSiteEntry_Application_t call_sites_Start[] = {
    { STATE_Application_Init, EVENT_Application_START },
};
#define CALL_SITES_Start_COUNT \
    (sizeof(call_sites_Start) / sizeof(call_sites_Start[0]))


/* --- call site table for Pause --- */
static const RoleFuncCallSiteEntry_Application_t call_sites_Pause[] = {
    { STATE_Application_Running, EVENT_Application_STOP },
};
#define CALL_SITES_Pause_COUNT \
    (sizeof(call_sites_Pause) / sizeof(call_sites_Pause[0]))


/* --- call site table for Resume --- */
static const RoleFuncCallSiteEntry_Application_t call_sites_Resume[] = {
    { STATE_Application_Paused, EVENT_Application_RESUME },
};
#define CALL_SITES_Resume_COUNT \
    (sizeof(call_sites_Resume) / sizeof(call_sites_Resume[0]))


/**
 * @brief  Role function: アプリ起動
 * @note   アプリ起動
 *
 * @note   Call sites:
 *         - [pre_action]  STATE_Application_Boot -[EVENT_Application_BOOT]-> STATE_Application_Init
 */
int RoleFunc_Application_Boot(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Application_t from_state = STATE_Application_MAX;
    EVENT_Application_t event = EVENT_Application_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_Boot, (uint16_t)CALL_SITES_Boot_COUNT);

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* 汎用カウンタ */
    uint8_t *const error_code = &ctx->data.error_code;  /* エラーコード */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* リトライ回数 */
    bool *const rx_ready = &ctx->data.rx_ready;  /* RX 準備完了 */
    uint8_t *const rx_data = &ctx->data.rx_data;  /* RX 受信データ */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* タイマ基準 [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* 派生タイマ [10ms] */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:Application_Boot]] */
    /* ユーザー実装コードをここに記述 */

    /* [[STABLE_USER_CODE_END:Application_Boot]] */

    return ret;
}

/**
 * @brief  Role function: アプリ開始
 * @note   アプリ開始
 *
 * @note   Call sites:
 *         - [pre_action]  STATE_Application_Init -[EVENT_Application_START]-> STATE_Application_Running
 */
int RoleFunc_Application_Start(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Application_t from_state = STATE_Application_MAX;
    EVENT_Application_t event = EVENT_Application_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_Start, (uint16_t)CALL_SITES_Start_COUNT);

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* 汎用カウンタ */
    uint8_t *const error_code = &ctx->data.error_code;  /* エラーコード */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* リトライ回数 */
    bool *const rx_ready = &ctx->data.rx_ready;  /* RX 準備完了 */
    uint8_t *const rx_data = &ctx->data.rx_data;  /* RX 受信データ */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* タイマ基準 [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* 派生タイマ [10ms] */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:Application_Start]] */
    /* ユーザー実装コードをここに記述 */

    /* [[STABLE_USER_CODE_END:Application_Start]] */

    return ret;
}

/**
 * @brief  Role function: 一時停止処理
 * @note   一時停止処理
 *
 * @note   Call sites:
 *         - [pre_action]  STATE_Application_Running -[EVENT_Application_STOP]-> STATE_Application_Stopped
 */
int RoleFunc_Application_Pause(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Application_t from_state = STATE_Application_MAX;
    EVENT_Application_t event = EVENT_Application_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_Pause, (uint16_t)CALL_SITES_Pause_COUNT);

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* 汎用カウンタ */
    uint8_t *const error_code = &ctx->data.error_code;  /* エラーコード */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* リトライ回数 */
    bool *const rx_ready = &ctx->data.rx_ready;  /* RX 準備完了 */
    uint8_t *const rx_data = &ctx->data.rx_data;  /* RX 受信データ */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* タイマ基準 [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* 派生タイマ [10ms] */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:Application_Pause]] */
    /* ユーザー実装コードをここに記述 */

    /* [[STABLE_USER_CODE_END:Application_Pause]] */

    return ret;
}

/**
 * @brief  Role function: 再開処理
 * @note   再開処理
 *
 * @note   Call sites:
 *         - [pre_action]  STATE_Application_Paused -[EVENT_Application_RESUME]-> STATE_Application_Running
 */
int RoleFunc_Application_Resume(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Application_t from_state = STATE_Application_MAX;
    EVENT_Application_t event = EVENT_Application_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_Resume, (uint16_t)CALL_SITES_Resume_COUNT);

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* 汎用カウンタ */
    uint8_t *const error_code = &ctx->data.error_code;  /* エラーコード */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* リトライ回数 */
    bool *const rx_ready = &ctx->data.rx_ready;  /* RX 準備完了 */
    uint8_t *const rx_data = &ctx->data.rx_data;  /* RX 受信データ */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* タイマ基準 [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* 派生タイマ [10ms] */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:Application_Resume]] */
    /* ユーザー実装コードをここに記述 */

    /* [[STABLE_USER_CODE_END:Application_Resume]] */

    return ret;
}

/**
 * @brief  Role function: 周期処理（ISR用）
 * @note   周期処理（ISR用）
 *
 * @note   Call sites: (none)
 */
int RoleFunc_Application_HandleTick(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Application_t from_state = STATE_Application_MAX;
    EVENT_Application_t event = EVENT_Application_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, NULL, 0);

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* 汎用カウンタ */
    uint8_t *const error_code = &ctx->data.error_code;  /* エラーコード */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* リトライ回数 */
    bool *const rx_ready = &ctx->data.rx_ready;  /* RX 準備完了 */
    uint8_t *const rx_data = &ctx->data.rx_data;  /* RX 受信データ */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* タイマ基準 [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* 派生タイマ [10ms] */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:Application_HandleTick]] */
    /* ユーザー実装コードをここに記述 */

    /* [[STABLE_USER_CODE_END:Application_HandleTick]] */

    return ret;
}

/**
 * @brief  Role function: RX処理（ISR用）
 * @note   RX処理（ISR用）
 *
 * @note   Call sites: (none)
 */
int RoleFunc_Application_HandleRx(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Application_t from_state = STATE_Application_MAX;
    EVENT_Application_t event = EVENT_Application_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, NULL, 0);

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* 汎用カウンタ */
    uint8_t *const error_code = &ctx->data.error_code;  /* エラーコード */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* リトライ回数 */
    bool *const rx_ready = &ctx->data.rx_ready;  /* RX 準備完了 */
    uint8_t *const rx_data = &ctx->data.rx_data;  /* RX 受信データ */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* タイマ基準 [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* 派生タイマ [10ms] */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:Application_HandleRx]] */
    /* ユーザー実装コードをここに記述 */

    /* [[STABLE_USER_CODE_END:Application_HandleRx]] */

    return ret;
}

/**
 * @brief  Role function: エラー処理（ISR用）
 * @note   エラー処理（ISR用）
 *
 * @note   Call sites: (none)
 */
int RoleFunc_Application_HandleError(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Application_t from_state = STATE_Application_MAX;
    EVENT_Application_t event = EVENT_Application_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, NULL, 0);

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* 汎用カウンタ */
    uint8_t *const error_code = &ctx->data.error_code;  /* エラーコード */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* リトライ回数 */
    bool *const rx_ready = &ctx->data.rx_ready;  /* RX 準備完了 */
    uint8_t *const rx_data = &ctx->data.rx_data;  /* RX 受信データ */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* タイマ基準 [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* 派生タイマ [10ms] */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:Application_HandleError]] */
    /* ユーザー実装コードをここに記述 */

    /* [[STABLE_USER_CODE_END:Application_HandleError]] */

    return ret;
}



/* ============================================================== */
/*  Transition ID conversion (end of file)                        */
/*  Linearly scans the per-function call_sites table and          */
/*  returns the index of the matching entry.                      */
/*  Returns TRANSITION_ID_NONE if no match / transition==NULL.    */
/* ============================================================== */
/**
 * @brief  Convert transition info to a unique ID
 * @param  transition  Transition context (may be NULL)
 * @param  table       Call site table (may be NULL)
 * @param  table_size  Number of entries in the table
 * @return Index in the table (TRANSITION_ID_NONE if no match)
 */
static uint16_t Transition_GetId(
    const TransitionContext_Application_t *transition,
    const RoleFuncCallSiteEntry_Application_t *table,
    uint16_t table_size)
{
    uint16_t i;

    if (transition == NULL || table == NULL) {
        return TRANSITION_ID_NONE;
    }

    for (i = 0; i < table_size; i++) {
        if (table[i].from_state == transition->from_state &&
            table[i].event      == transition->event) {
            return i;
        }
    }
    return TRANSITION_ID_NONE;
}


/* ============================================================== */
/*  User-added area                                               */
/*  Code added here is preserved across regenerations             */
/* ============================================================== */
/* [[STABLE_USER_CODE_TAIL_START]] */
/* ユーザー追加コードをここに記述（ヘルパー関数など） */

/* [[STABLE_USER_CODE_TAIL_END]] */
