/**
 * @file    statable_role_functions_Application.h
 * @brief   Role function declarations
 *
 * @note    Code auto-generated by StaTable
 *          - Manual editing is not recommended
 *          - To modify, use StaTable
 *
 * @date    2026-09-19 17:26:55
 */

#ifndef STATABLE_ROLE_FUNCTIONS_H_APPLICATION
#define STATABLE_ROLE_FUNCTIONS_H_APPLICATION

/*==============================================================*/
 *  Include files
/*==============================================================*/

#include "statable_types_Application.h"

/*==============================================================*/
 *  Role function declarations
/*==============================================================*/

/**
 * @brief  Role function: Idle entry
 * @note   Idle entry
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_IdleEntry(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Idle exit
 * @note   Idle exit
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_IdleExit(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Active entry 1
 * @note   Active entry 1
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_ActiveEntry1(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Active entry 2
 * @note   Active entry 2
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_ActiveEntry2(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Waiting entry
 * @note   Waiting entry
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_WaitEntry(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Waiting exit
 * @note   Waiting exit
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_WaitExit(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Error entry
 * @note   Error entry
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_ErrorEntry(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Error exit
 * @note   Error exit
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_ErrorExit(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Pre-check
 * @note   Pre-check action
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_PreCheck(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Cleanup
 * @note   Cleanup action
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_Cleanup(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Init session
 * @note   Init session
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_InitSession(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Log error
 * @note   Log error
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_LogError(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Log reset
 * @note   Log reset
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_LogReset(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Handle pause
 * @note   Handle pause
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_HandlePause(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Handle stop
 * @note   Handle stop
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_HandleStop(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Resume work
 * @note   Resume work
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_ResumeWork(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Handle RX
 * @note   Handle RX (ISR)
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_HandleRx(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
);



#endif /* STATABLE_ROLE_FUNCTIONS_H_APPLICATION */