/**
 * @file    statable_transitions_Application.c
 * @brief   State transition logic
 *
 * @note    Code auto-generated by StaTable
 *          - Manual editing is not recommended
 *          - To modify, use StaTable
 *
 * @date    2026-09-20 11:36:09
 */

/*==============================================================
 *  Include files
 *==============================================================*/

#include "statable_transitions_Application.h"
#include "statable_role_functions_Application.h"
#include "statable_types_common.h"
#include "Driver/statable_role_functions_Driver.h"
#include "Middleware/statable_role_functions_Middleware.h"

/*==============================================================
 *  State transition table
 *==============================================================*/

/* ===== Cell transition function forward declarations ===== */
static STATE_Application_t t_Boot_BOOT(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx);
static STATE_Application_t t_Init_START(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx);
static STATE_Application_t t_Running_PAUSE(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx);
static STATE_Application_t t_Running_STOP(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx);
static STATE_Application_t t_Paused_RESUME(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx);
static STATE_Application_t t_Paused_STOP(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx);


/* Transition function pointer type */
typedef STATE_Application_t (*TransitionFunc_Application_t)(
    const TransitionContext_Application_t *, SystemContext_t *);

/* ============================================================== */
/*  State transition table: rows=state, cols=event      */
/*  Global variable (externally accessible)                     */
/* ============================================================== */
const TransitionFunc_Application_t transition_table_Application
    [STATE_Application_MAX][EVENT_Application_MAX] = {
    /*           | BOOT           | START          | PAUSE           | RESUME          | STOP           */
    /* ---------+--------------+--------------+---------------+---------------+--------------*/
    /* Boot     */ { t_Boot_BOOT   , NULL          , NULL           , NULL           , NULL           },
    /* Init     */ { NULL          , t_Init_START  , NULL           , NULL           , NULL           },
    /* Running  */ { NULL          , NULL          , t_Running_PAUSE, NULL           , t_Running_STOP },
    /* Paused   */ { NULL          , NULL          , NULL           , t_Paused_RESUME, t_Paused_STOP  },
    /* Stopped  */ { NULL          , NULL          , NULL           , NULL           , NULL           },
};


/**
 * @brief  Cell transition: STATE_Application_Boot -[EVENT_Application_BOOT]-> (multi)
 * @note   Transition count: 1
 */
static STATE_Application_t t_Boot_BOOT(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    STATE_Application_t next_state = transition->from_state;

    /* ===== Cell actions (before_transitions) ===== */
    (void)RoleFunc_App_PreCheck(transition, ctx);

    /* ===== Transition[T1] (Commit) ===== */
    if (1) {
        (void)RoleFunc_App_BootExit(transition, ctx);  /* state exit */
        (void)RoleFunc_App_Boot(transition, ctx);
        next_state = STATE_Application_Init;
        (void)RoleFunc_App_InitEntry(transition, ctx);  /* state entry */
    }

    /* ===== Cell actions (after_transitions) ===== */
    (void)RoleFunc_App_Cleanup(transition, ctx);

    return next_state;
}

/**
 * @brief  Cell transition: STATE_Application_Init -[EVENT_Application_START]-> (multi)
 * @note   Transition count: 1
 */
static STATE_Application_t t_Init_START(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    STATE_Application_t next_state = transition->from_state;

    /* ===== Cell actions (before_transitions) ===== */
    (void)RoleFunc_App_Pre(transition, ctx);

    /* ===== Transition[T1] (Commit) ===== */
    if (1) {
        (void)RoleFunc_App_Start(transition, ctx);
        next_state = STATE_Application_Running;
        (void)RoleFunc_App_RunEntry1(transition, ctx);  /* state entry */
        (void)RoleFunc_App_RunEntry2(transition, ctx);  /* state entry */
    }

    /* ===== Cell actions (after_transitions) ===== */
    (void)RoleFunc_App_Post(transition, ctx);

    return next_state;
}

/**
 * @brief  Cell transition: STATE_Application_Running -[EVENT_Application_PAUSE]-> (multi)
 * @note   Transition count: 2
 */
static STATE_Application_t t_Running_PAUSE(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    STATE_Application_t next_state = transition->from_state;

    /* ===== Transition[T1] (Commit) ===== */
    if (RoleFunc_App_PreCheck(transition, ctx) != 0) {
        (void)RoleFunc_App_Pause(transition, ctx);
        next_state = STATE_Application_Paused;
        (void)RoleFunc_App_PauseEntry(transition, ctx);  /* state entry */
    }

    /* ===== Transition[T2] (Tentative) ===== */
    if (RoleFunc_App_PreCheck(transition, ctx) == 0) {
        next_state = STATE_Application_Running;
        (void)RoleFunc_App_RunEntry1(transition, ctx);  /* state entry */
        (void)RoleFunc_App_RunEntry2(transition, ctx);  /* state entry */
    }

    return next_state;
}

/**
 * @brief  Cell transition: STATE_Application_Running -[EVENT_Application_STOP]-> (multi)
 * @note   Transition count: 2
 */
static STATE_Application_t t_Running_STOP(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    STATE_Application_t next_state = transition->from_state;

    /* ===== Group (shared_condition) ===== */
    if (ctx->data.running == true) {

        /* ===== Transition[T1] (Commit) ===== */
        if (ctx->data.g_system_tick > 100) {
            (void)RoleFunc_App_HandleStop(transition, ctx);
            next_state = STATE_Application_Stopped;
            (void)RoleFunc_App_StopEntry(transition, ctx);  /* state entry */
        }

        /* ===== Group (shared_condition) ===== */
        if (ctx->data.g_system_tick > 0) {

            /* ===== Transition[T2] (Tentative) ===== */
            if (ctx->data.g_system_tick <= 100) {
                next_state = STATE_Application_Paused;
                (void)RoleFunc_App_PauseEntry(transition, ctx);  /* state entry */
            }
        }
    }

    return next_state;
}

/**
 * @brief  Cell transition: STATE_Application_Paused -[EVENT_Application_RESUME]-> (multi)
 * @note   Transition count: 1
 */
static STATE_Application_t t_Paused_RESUME(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    STATE_Application_t next_state = transition->from_state;

    /* ===== Transition[T1] (Commit) ===== */
    if (1) {
        (void)RoleFunc_App_Resume(transition, ctx);
        next_state = STATE_Application_Running;
        (void)RoleFunc_App_RunEntry1(transition, ctx);  /* state entry */
        (void)RoleFunc_App_RunEntry2(transition, ctx);  /* state entry */
    }

    return next_state;
}

/**
 * @brief  Cell transition: STATE_Application_Paused -[EVENT_Application_STOP]-> (multi)
 * @note   Transition count: 1
 */
static STATE_Application_t t_Paused_STOP(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    STATE_Application_t next_state = transition->from_state;

    /* ===== Transition[T1] (Commit) ===== */
    if (1) {
        next_state = STATE_Application_Stopped;
        (void)RoleFunc_App_StopEntry(transition, ctx);  /* state entry */
    } else {
        next_state = STATE_Application_Paused;
        (void)RoleFunc_App_PauseEntry(transition, ctx);  /* state entry */
    }

    return next_state;
}


/*==============================================================
 *  State transition functions
 *==============================================================*/

/**
 * @brief  Application layer state transition processing
 * @param  current_state  Current state
 * @param  event          Event that occurred
 * @param  ctx            System context pointer
 * @return State after transition
 */
STATE_Application_t StateMachine_Process_Application(
    STATE_Application_t current_state,
    EVENT_Application_t event,
    SystemContext_t *ctx
)
{
    TransitionContext_Application_t transition = {
        .from_state = current_state,
        .event = event,
    };
    TransitionFunc_Application_t func = transition_table_Application[current_state][event];
    if (func != NULL) {
        return func(&transition, ctx);
    }
    return current_state;
}


/*==============================================================
 *  Event retrieval function
 *==============================================================*/

/**
 * @brief  Get next event for Application layer
 * @param  ctx  System context pointer
 * @return Next event (EVENT_Application_NONE if no pending event)
 */
EVENT_Application_t StateMachine_GetNextEvent_Application(SystemContext_t *ctx)
{
    static uint8_t consecutive_count = 0;

    if (ctx->pending_event_valid) {
        consecutive_count++;
        if (consecutive_count > MAX_CONSECUTIVE_PENDING_EVENTS) {
            /* Pending event chain too long: force reset */
            ctx->pending_event_valid = false;
            consecutive_count = 0;
            return EVENT_Application_NONE;
        }
        EVENT_Application_t evt = (EVENT_Application_t)ctx->pending_event;
        ctx->pending_event_valid = false;
        return evt;
    }
    consecutive_count = 0;
    return EVENT_Application_NONE;
}
