/**
 * @file    statable_role_functions_Application.c
 * @brief   Role function implementations
 *
 * @note    Code auto-generated by StaTable
 *          - Manual editing is not recommended
 *          - To modify, use StaTable
 *
 * @date    2026-09-19 20:52:49
 */

/*==============================================================
 *  Include files
 *==============================================================*/

#include "statable_role_functions_Application.h"

/*==============================================================
 *  Role function implementations
 *==============================================================*/


/* ============================================================== */
/*  Transition ID constant                                        */
/* ============================================================== */
#define TRANSITION_ID_NONE   ((uint16_t)0xFFFF)


/* ============================================================== */
/*  Role function call site table (common struct)                 */
/*  Identify cells by {from_state, event} pair                    */
/* ============================================================== */
typedef struct {
    STATE_Application_t from_state;   /* source state */
    EVENT_Application_t event;        /* event */
} RoleFuncCallSiteEntry_Application_t;


/* Transition_GetId forward declaration (body at end of file) */
static uint16_t Transition_GetId(
    const TransitionContext_Application_t *transition,
    const RoleFuncCallSiteEntry_Application_t *table,
    uint16_t table_size);


/* --- call site table for Boot --- */
static const RoleFuncCallSiteEntry_Application_t call_sites_Boot[] = {
    { STATE_Application_Boot, EVENT_Application_BOOT },
};
#define CALL_SITES_Boot_COUNT \
    (sizeof(call_sites_Boot) / sizeof(call_sites_Boot[0]))


/* --- call site table for Start --- */
static const RoleFuncCallSiteEntry_Application_t call_sites_Start[] = {
    { STATE_Application_Init, EVENT_Application_START },
};
#define CALL_SITES_Start_COUNT \
    (sizeof(call_sites_Start) / sizeof(call_sites_Start[0]))


/* --- call site table for Pause --- */
static const RoleFuncCallSiteEntry_Application_t call_sites_Pause[] = {
    { STATE_Application_Running, EVENT_Application_PAUSE },
};
#define CALL_SITES_Pause_COUNT \
    (sizeof(call_sites_Pause) / sizeof(call_sites_Pause[0]))


/* --- call site table for Resume --- */
static const RoleFuncCallSiteEntry_Application_t call_sites_Resume[] = {
    { STATE_Application_Paused, EVENT_Application_RESUME },
};
#define CALL_SITES_Resume_COUNT \
    (sizeof(call_sites_Resume) / sizeof(call_sites_Resume[0]))


/* --- call site table for HandleStop --- */
static const RoleFuncCallSiteEntry_Application_t call_sites_HandleStop[] = {
    { STATE_Application_Running, EVENT_Application_STOP },
};
#define CALL_SITES_HandleStop_COUNT \
    (sizeof(call_sites_HandleStop) / sizeof(call_sites_HandleStop[0]))


/**
 * @brief  Role function: App boot
 * @note   App boot
 *
 * @note   Call sites:
 *         - [pre_action]  STATE_Application_Boot -[EVENT_Application_BOOT]-> STATE_Application_Init
 */
int RoleFunc_App_Boot(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Application_t from_state = STATE_Application_MAX;
    EVENT_Application_t event = EVENT_Application_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_Boot, (uint16_t)CALL_SITES_Boot_COUNT);

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:App_Boot]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:App_Boot]] */

    return ret;
}

/**
 * @brief  Role function: App start
 * @note   App start
 *
 * @note   Call sites:
 *         - [pre_action]  STATE_Application_Init -[EVENT_Application_START]-> STATE_Application_Running
 */
int RoleFunc_App_Start(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Application_t from_state = STATE_Application_MAX;
    EVENT_Application_t event = EVENT_Application_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_Start, (uint16_t)CALL_SITES_Start_COUNT);

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:App_Start]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:App_Start]] */

    return ret;
}

/**
 * @brief  Role function: App pause
 * @note   App pause
 *
 * @note   Call sites:
 *         - [pre_action]  STATE_Application_Running -[EVENT_Application_PAUSE]-> STATE_Application_Paused
 */
int RoleFunc_App_Pause(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Application_t from_state = STATE_Application_MAX;
    EVENT_Application_t event = EVENT_Application_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_Pause, (uint16_t)CALL_SITES_Pause_COUNT);

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:App_Pause]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:App_Pause]] */

    return ret;
}

/**
 * @brief  Role function: App resume
 * @note   App resume
 *
 * @note   Call sites:
 *         - [pre_action]  STATE_Application_Paused -[EVENT_Application_RESUME]-> STATE_Application_Running
 */
int RoleFunc_App_Resume(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Application_t from_state = STATE_Application_MAX;
    EVENT_Application_t event = EVENT_Application_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_Resume, (uint16_t)CALL_SITES_Resume_COUNT);

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:App_Resume]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:App_Resume]] */

    return ret;
}

/**
 * @brief  Role function: Handle stop
 * @note   Handle stop
 *
 * @note   Call sites:
 *         - [pre_action]  STATE_Application_Running -[EVENT_Application_STOP]-> STATE_Application_Stopped
 */
int RoleFunc_App_HandleStop(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Application_t from_state = STATE_Application_MAX;
    EVENT_Application_t event = EVENT_Application_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_HandleStop, (uint16_t)CALL_SITES_HandleStop_COUNT);

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:App_HandleStop]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:App_HandleStop]] */

    return ret;
}



/* ============================================================== */
/*  Transition ID conversion (end of file)                        */
/*  Linearly scans the per-function call_sites table and          */
/*  returns the index of the matching entry.                      */
/*  Returns TRANSITION_ID_NONE if no match / transition==NULL.    */
/* ============================================================== */
/**
 * @brief  Convert transition info to a unique ID
 * @param  transition  Transition context (may be NULL)
 * @param  table       Call site table (may be NULL)
 * @param  table_size  Number of entries in the table
 * @return Index in the table (TRANSITION_ID_NONE if no match)
 */
static uint16_t Transition_GetId(
    const TransitionContext_Application_t *transition,
    const RoleFuncCallSiteEntry_Application_t *table,
    uint16_t table_size)
{
    uint16_t i;

    if (transition == NULL || table == NULL) {
        return TRANSITION_ID_NONE;
    }

    for (i = 0; i < table_size; i++) {
        if (table[i].from_state == transition->from_state &&
            table[i].event      == transition->event) {
            return i;
        }
    }
    return TRANSITION_ID_NONE;
}


/* ============================================================== */
/*  User-added area                                               */
/*  Code added here is preserved across regenerations             */
/* ============================================================== */
/* [[STABLE_USER_CODE_TAIL_START]] */
/* Write user-added code here (helper functions, etc.) */
/* [[STABLE_USER_CODE_TAIL_END]] */
