/**
 * @file    statable_types_Driver.h
 * @brief   Layer-specific type definitions (enum)
 *
 * @note    Code auto-generated by StaTable
 *          - Manual editing is not recommended
 *          - To modify, use StaTable
 *
 * @date    2026-09-20 11:36:09
 */

#ifndef STATABLE_TYPES_H_DRIVER
#define STATABLE_TYPES_H_DRIVER

/*==============================================================
 *  Include files
 *==============================================================*/

#include "statable_types_common.h"

/*==============================================================
 *  Type definitions
 *==============================================================*/

/* Driver layer state definitions */
typedef enum {
    STATE_Driver_Idle = 0,    /* Idle Type: INITIAL */
    STATE_Driver_Initializing = 1,    /* Initializing */
    STATE_Driver_Ready = 2,    /* Ready */
    STATE_Driver_Error = 3,    /* Error */
    STATE_Driver_MAX           /* element count (for system use) */
} STATE_Driver_t;


/* Driver layer event definitions */
typedef enum {
    EVENT_Driver_NONE = 0,    /* completion transition */
    EVENT_Driver_INIT = 1,    /* Init request Title: Init */
    EVENT_Driver_READY = 2,    /* Ready Title: Ready */
    EVENT_Driver_FAIL = 3,    /* Failure Title: Failure */
    EVENT_Driver_RESET = 4,    /* Reset Title: Reset */
    EVENT_Driver_MAX           /* element count (for system use) */
} EVENT_Driver_t;



/* Transition context for Driver layer */
typedef struct {
    STATE_Driver_t from_state;   /* source state */
    EVENT_Driver_t event;        /* event */
} TransitionContext_Driver_t;

#endif /* STATABLE_TYPES_H_DRIVER */