/**
 * @file    statable_role_functions_Driver.c
 * @brief   Role function implementations
 *
 * @note    Code auto-generated by StaTable
 *          - Manual editing is not recommended
 *          - To modify, use StaTable
 *
 * @date    2026-09-20 11:36:09
 */

/*==============================================================
 *  Include files
 *==============================================================*/

#include "statable_role_functions_Driver.h"
#include "Middleware/statable_role_functions_Middleware.h"
#include "Application/statable_role_functions_Application.h"

/*==============================================================
 *  Role function implementations
 *==============================================================*/


/* ============================================================== */
/*  Transition ID constant                                        */
/* ============================================================== */
#define TRANSITION_ID_NONE   ((uint16_t)0xFFFF)


/* ============================================================== */
/*  Role function call site table (common struct)                 */
/*  Identify cells by {from_state, event} pair                    */
/* ============================================================== */
typedef struct {
    STATE_Driver_t from_state;   /* source state */
    EVENT_Driver_t event;        /* event */
} RoleFuncCallSiteEntry_Driver_t;


/* Transition_GetId forward declaration (body at end of file) */
static uint16_t Transition_GetId(
    const TransitionContext_Driver_t *transition,
    const RoleFuncCallSiteEntry_Driver_t *table,
    uint16_t table_size);


/* --- call site table for IdleEntry --- */
static const RoleFuncCallSiteEntry_Driver_t call_sites_IdleEntry[] = {
    { STATE_Driver_Idle, EVENT_Driver_NONE },
};
#define CALL_SITES_IdleEntry_COUNT \
    (sizeof(call_sites_IdleEntry) / sizeof(call_sites_IdleEntry[0]))


/* --- call site table for IdleExit --- */
static const RoleFuncCallSiteEntry_Driver_t call_sites_IdleExit[] = {
    { STATE_Driver_Idle, EVENT_Driver_NONE },
};
#define CALL_SITES_IdleExit_COUNT \
    (sizeof(call_sites_IdleExit) / sizeof(call_sites_IdleExit[0]))


/* --- call site table for InitEntry --- */
static const RoleFuncCallSiteEntry_Driver_t call_sites_InitEntry[] = {
    { STATE_Driver_Initializing, EVENT_Driver_NONE },
};
#define CALL_SITES_InitEntry_COUNT \
    (sizeof(call_sites_InitEntry) / sizeof(call_sites_InitEntry[0]))


/* --- call site table for ReadyEntry --- */
static const RoleFuncCallSiteEntry_Driver_t call_sites_ReadyEntry[] = {
    { STATE_Driver_Ready, EVENT_Driver_NONE },
};
#define CALL_SITES_ReadyEntry_COUNT \
    (sizeof(call_sites_ReadyEntry) / sizeof(call_sites_ReadyEntry[0]))


/* --- call site table for ErrorEntry --- */
static const RoleFuncCallSiteEntry_Driver_t call_sites_ErrorEntry[] = {
    { STATE_Driver_Error, EVENT_Driver_NONE },
};
#define CALL_SITES_ErrorEntry_COUNT \
    (sizeof(call_sites_ErrorEntry) / sizeof(call_sites_ErrorEntry[0]))


/* --- call site table for ErrorExit --- */
static const RoleFuncCallSiteEntry_Driver_t call_sites_ErrorExit[] = {
    { STATE_Driver_Error, EVENT_Driver_NONE },
};
#define CALL_SITES_ErrorExit_COUNT \
    (sizeof(call_sites_ErrorExit) / sizeof(call_sites_ErrorExit[0]))


/* --- call site table for Init --- */
static const RoleFuncCallSiteEntry_Driver_t call_sites_Init[] = {
    { STATE_Driver_Idle, EVENT_Driver_INIT },
};
#define CALL_SITES_Init_COUNT \
    (sizeof(call_sites_Init) / sizeof(call_sites_Init[0]))


/* --- call site table for LogError --- */
static const RoleFuncCallSiteEntry_Driver_t call_sites_LogError[] = {
    { STATE_Driver_Initializing, EVENT_Driver_READY },
    { STATE_Driver_Initializing, EVENT_Driver_FAIL },
    { STATE_Driver_Ready,        EVENT_Driver_FAIL },
};
#define CALL_SITES_LogError_COUNT \
    (sizeof(call_sites_LogError) / sizeof(call_sites_LogError[0]))


/* --- call site table for Reset --- */
static const RoleFuncCallSiteEntry_Driver_t call_sites_Reset[] = {
    { STATE_Driver_Error, EVENT_Driver_RESET },
};
#define CALL_SITES_Reset_COUNT \
    (sizeof(call_sites_Reset) / sizeof(call_sites_Reset[0]))


/* --- call site table for PreCheck --- */
static const RoleFuncCallSiteEntry_Driver_t call_sites_PreCheck[] = {
    { STATE_Driver_Initializing, EVENT_Driver_READY },
    { STATE_Driver_Idle,         EVENT_Driver_INIT },
};
#define CALL_SITES_PreCheck_COUNT \
    (sizeof(call_sites_PreCheck) / sizeof(call_sites_PreCheck[0]))


/* --- call site table for Cleanup --- */
static const RoleFuncCallSiteEntry_Driver_t call_sites_Cleanup[] = {
    { STATE_Driver_Idle, EVENT_Driver_INIT },
};
#define CALL_SITES_Cleanup_COUNT \
    (sizeof(call_sites_Cleanup) / sizeof(call_sites_Cleanup[0]))


/**
 * @brief  Role function: Idle entry
 * @note   Idle entry
 *
 * @note   Call sites:
 *         - [state_entry]  STATE_Driver_Idle -[EVENT_Driver_NONE]-> STATE_Driver_Idle
 */
int RoleFunc_Driver_IdleEntry(
    const TransitionContext_Driver_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Driver_t from_state = STATE_Driver_MAX;
    EVENT_Driver_t event = EVENT_Driver_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_IdleEntry, (uint16_t)CALL_SITES_IdleEntry_COUNT);
    (void)transition_id;   /* suppress unused warning */

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */
    (void)counter;   /* suppress unused warning */
    (void)error_code;   /* suppress unused warning */
    (void)retry_count;   /* suppress unused warning */
    (void)running;   /* suppress unused warning */
    (void)g_system_tick;   /* suppress unused warning */
    (void)g_tick_10ms;   /* suppress unused warning */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:Driver_IdleEntry]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:Driver_IdleEntry]] */

    return ret;
}

/**
 * @brief  Role function: Idle exit
 * @note   Idle exit
 *
 * @note   Call sites:
 *         - [state_exit]  STATE_Driver_Idle -[EVENT_Driver_NONE]-> STATE_Driver_Idle
 */
int RoleFunc_Driver_IdleExit(
    const TransitionContext_Driver_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Driver_t from_state = STATE_Driver_MAX;
    EVENT_Driver_t event = EVENT_Driver_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_IdleExit, (uint16_t)CALL_SITES_IdleExit_COUNT);
    (void)transition_id;   /* suppress unused warning */

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */
    (void)counter;   /* suppress unused warning */
    (void)error_code;   /* suppress unused warning */
    (void)retry_count;   /* suppress unused warning */
    (void)running;   /* suppress unused warning */
    (void)g_system_tick;   /* suppress unused warning */
    (void)g_tick_10ms;   /* suppress unused warning */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:Driver_IdleExit]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:Driver_IdleExit]] */

    return ret;
}

/**
 * @brief  Role function: Init entry
 * @note   Initializing entry
 *
 * @note   Call sites:
 *         - [state_entry]  STATE_Driver_Initializing -[EVENT_Driver_NONE]-> STATE_Driver_Initializing
 */
int RoleFunc_Driver_InitEntry(
    const TransitionContext_Driver_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Driver_t from_state = STATE_Driver_MAX;
    EVENT_Driver_t event = EVENT_Driver_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_InitEntry, (uint16_t)CALL_SITES_InitEntry_COUNT);
    (void)transition_id;   /* suppress unused warning */

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */
    (void)counter;   /* suppress unused warning */
    (void)error_code;   /* suppress unused warning */
    (void)retry_count;   /* suppress unused warning */
    (void)running;   /* suppress unused warning */
    (void)g_system_tick;   /* suppress unused warning */
    (void)g_tick_10ms;   /* suppress unused warning */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:Driver_InitEntry]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:Driver_InitEntry]] */

    return ret;
}

/**
 * @brief  Role function: Ready entry
 * @note   Ready entry
 *
 * @note   Call sites:
 *         - [state_entry]  STATE_Driver_Ready -[EVENT_Driver_NONE]-> STATE_Driver_Ready
 */
int RoleFunc_Driver_ReadyEntry(
    const TransitionContext_Driver_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Driver_t from_state = STATE_Driver_MAX;
    EVENT_Driver_t event = EVENT_Driver_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_ReadyEntry, (uint16_t)CALL_SITES_ReadyEntry_COUNT);
    (void)transition_id;   /* suppress unused warning */

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */
    (void)counter;   /* suppress unused warning */
    (void)error_code;   /* suppress unused warning */
    (void)retry_count;   /* suppress unused warning */
    (void)running;   /* suppress unused warning */
    (void)g_system_tick;   /* suppress unused warning */
    (void)g_tick_10ms;   /* suppress unused warning */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:Driver_ReadyEntry]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:Driver_ReadyEntry]] */

    return ret;
}

/**
 * @brief  Role function: Error entry
 * @note   Error entry
 *
 * @note   Call sites:
 *         - [state_entry]  STATE_Driver_Error -[EVENT_Driver_NONE]-> STATE_Driver_Error
 */
int RoleFunc_Driver_ErrorEntry(
    const TransitionContext_Driver_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Driver_t from_state = STATE_Driver_MAX;
    EVENT_Driver_t event = EVENT_Driver_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_ErrorEntry, (uint16_t)CALL_SITES_ErrorEntry_COUNT);
    (void)transition_id;   /* suppress unused warning */

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */
    (void)counter;   /* suppress unused warning */
    (void)error_code;   /* suppress unused warning */
    (void)retry_count;   /* suppress unused warning */
    (void)running;   /* suppress unused warning */
    (void)g_system_tick;   /* suppress unused warning */
    (void)g_tick_10ms;   /* suppress unused warning */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:Driver_ErrorEntry]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:Driver_ErrorEntry]] */

    return ret;
}

/**
 * @brief  Role function: Error exit
 * @note   Error exit
 *
 * @note   Call sites:
 *         - [state_exit]  STATE_Driver_Error -[EVENT_Driver_NONE]-> STATE_Driver_Error
 */
int RoleFunc_Driver_ErrorExit(
    const TransitionContext_Driver_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Driver_t from_state = STATE_Driver_MAX;
    EVENT_Driver_t event = EVENT_Driver_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_ErrorExit, (uint16_t)CALL_SITES_ErrorExit_COUNT);
    (void)transition_id;   /* suppress unused warning */

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */
    (void)counter;   /* suppress unused warning */
    (void)error_code;   /* suppress unused warning */
    (void)retry_count;   /* suppress unused warning */
    (void)running;   /* suppress unused warning */
    (void)g_system_tick;   /* suppress unused warning */
    (void)g_tick_10ms;   /* suppress unused warning */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:Driver_ErrorExit]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:Driver_ErrorExit]] */

    return ret;
}

/**
 * @brief  Role function: Driver init
 * @note   Driver init
 *
 * @note   Call sites:
 *         - [pre_action]  STATE_Driver_Idle -[EVENT_Driver_INIT]-> STATE_Driver_Initializing
 */
int RoleFunc_Driver_Init(
    const TransitionContext_Driver_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Driver_t from_state = STATE_Driver_MAX;
    EVENT_Driver_t event = EVENT_Driver_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_Init, (uint16_t)CALL_SITES_Init_COUNT);
    (void)transition_id;   /* suppress unused warning */

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */
    (void)counter;   /* suppress unused warning */
    (void)error_code;   /* suppress unused warning */
    (void)retry_count;   /* suppress unused warning */
    (void)running;   /* suppress unused warning */
    (void)g_system_tick;   /* suppress unused warning */
    (void)g_tick_10ms;   /* suppress unused warning */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:Driver_Init]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:Driver_Init]] */

    return ret;
}

/**
 * @brief  Role function: Log error
 * @note   Log error
 *
 * @note   Call sites:
 *         - [pre_action]  STATE_Driver_Initializing -[EVENT_Driver_READY]-> STATE_Driver_Error
 *         - [pre_action]  STATE_Driver_Initializing -[EVENT_Driver_FAIL]-> STATE_Driver_Error
 *         - [pre_action]  STATE_Driver_Ready        -[EVENT_Driver_FAIL]-> STATE_Driver_Error
 */
int RoleFunc_Driver_LogError(
    const TransitionContext_Driver_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Driver_t from_state = STATE_Driver_MAX;
    EVENT_Driver_t event = EVENT_Driver_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_LogError, (uint16_t)CALL_SITES_LogError_COUNT);
    (void)transition_id;   /* suppress unused warning */

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */
    (void)counter;   /* suppress unused warning */
    (void)error_code;   /* suppress unused warning */
    (void)retry_count;   /* suppress unused warning */
    (void)running;   /* suppress unused warning */
    (void)g_system_tick;   /* suppress unused warning */
    (void)g_tick_10ms;   /* suppress unused warning */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:Driver_LogError]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:Driver_LogError]] */

    return ret;
}

/**
 * @brief  Role function: Reset
 * @note   Reset
 *
 * @note   Call sites:
 *         - [pre_action]  STATE_Driver_Error -[EVENT_Driver_RESET]-> STATE_Driver_Idle
 */
int RoleFunc_Driver_Reset(
    const TransitionContext_Driver_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Driver_t from_state = STATE_Driver_MAX;
    EVENT_Driver_t event = EVENT_Driver_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_Reset, (uint16_t)CALL_SITES_Reset_COUNT);
    (void)transition_id;   /* suppress unused warning */

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */
    (void)counter;   /* suppress unused warning */
    (void)error_code;   /* suppress unused warning */
    (void)retry_count;   /* suppress unused warning */
    (void)running;   /* suppress unused warning */
    (void)g_system_tick;   /* suppress unused warning */
    (void)g_tick_10ms;   /* suppress unused warning */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:Driver_Reset]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:Driver_Reset]] */

    return ret;
}

/**
 * @brief  Role function: Pre-check
 * @note   Pre-check
 *
 * @note   Call sites:
 *         - [condition]                       STATE_Driver_Initializing -[EVENT_Driver_READY]-> STATE_Driver_Ready
 *         - [cell_action_before_transitions]  STATE_Driver_Idle         -[EVENT_Driver_INIT]-> (not set)
 */
int RoleFunc_Driver_PreCheck(
    const TransitionContext_Driver_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Driver_t from_state = STATE_Driver_MAX;
    EVENT_Driver_t event = EVENT_Driver_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_PreCheck, (uint16_t)CALL_SITES_PreCheck_COUNT);
    (void)transition_id;   /* suppress unused warning */

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */
    (void)counter;   /* suppress unused warning */
    (void)error_code;   /* suppress unused warning */
    (void)retry_count;   /* suppress unused warning */
    (void)running;   /* suppress unused warning */
    (void)g_system_tick;   /* suppress unused warning */
    (void)g_tick_10ms;   /* suppress unused warning */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:Driver_PreCheck]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:Driver_PreCheck]] */

    return ret;
}

/**
 * @brief  Role function: Cleanup
 * @note   Cleanup
 *
 * @note   Call sites:
 *         - [cell_action_after_transitions]  STATE_Driver_Idle -[EVENT_Driver_INIT]-> (not set)
 */
int RoleFunc_Driver_Cleanup(
    const TransitionContext_Driver_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Driver_t from_state = STATE_Driver_MAX;
    EVENT_Driver_t event = EVENT_Driver_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_Cleanup, (uint16_t)CALL_SITES_Cleanup_COUNT);
    (void)transition_id;   /* suppress unused warning */

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */
    (void)counter;   /* suppress unused warning */
    (void)error_code;   /* suppress unused warning */
    (void)retry_count;   /* suppress unused warning */
    (void)running;   /* suppress unused warning */
    (void)g_system_tick;   /* suppress unused warning */
    (void)g_tick_10ms;   /* suppress unused warning */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:Driver_Cleanup]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:Driver_Cleanup]] */

    return ret;
}



/* ============================================================== */
/*  Transition ID conversion (end of file)                        */
/*  Linearly scans the per-function call_sites table and          */
/*  returns the index of the matching entry.                      */
/*  Returns TRANSITION_ID_NONE if no match / transition==NULL.    */
/* ============================================================== */
/**
 * @brief  Convert transition info to a unique ID
 * @param  transition  Transition context (may be NULL)
 * @param  table       Call site table (may be NULL)
 * @param  table_size  Number of entries in the table
 * @return Index in the table (TRANSITION_ID_NONE if no match)
 */
static uint16_t Transition_GetId(
    const TransitionContext_Driver_t *transition,
    const RoleFuncCallSiteEntry_Driver_t *table,
    uint16_t table_size)
{
    uint16_t i;

    if ((transition == NULL) || (table == NULL)) {
        return TRANSITION_ID_NONE;
    }

    for (i = 0; i < table_size; i++) {
        if ((table[i].from_state == transition->from_state) &&
            (table[i].event      == transition->event)) {
            return i;
        }
    }
    return TRANSITION_ID_NONE;
}


/* ============================================================== */
/*  User-added area                                               */
/*  Code added here is preserved across regenerations             */
/* ============================================================== */
/* [[STABLE_USER_CODE_TAIL_START]] */
/* Write user-added code here (helper functions, etc.) */
/* [[STABLE_USER_CODE_TAIL_END]] */
