/**
 * @file    statable_transitions_Driver.c
 * @brief   State transition logic
 *
 * @note    Code auto-generated by StaTable
 *          - Manual editing is not recommended
 *          - To modify, use StaTable
 *
 * @date    2026-09-20 02:21:47
 */

/*==============================================================
 *  Include files
 *==============================================================*/

#include "statable_transitions_Driver.h"
#include "statable_role_functions_Driver.h"

/*==============================================================
 *  State transition table
 *==============================================================*/

/* ===== Cell transition function forward declarations ===== */
static STATE_Driver_t t_Idle_INIT(
    const TransitionContext_Driver_t *transition,
    SystemContext_t *ctx);
static STATE_Driver_t t_Initializing_READY(
    const TransitionContext_Driver_t *transition,
    SystemContext_t *ctx);
static STATE_Driver_t t_Initializing_FAIL(
    const TransitionContext_Driver_t *transition,
    SystemContext_t *ctx);
static STATE_Driver_t t_Ready_FAIL(
    const TransitionContext_Driver_t *transition,
    SystemContext_t *ctx);
static STATE_Driver_t t_Error_RESET(
    const TransitionContext_Driver_t *transition,
    SystemContext_t *ctx);


/* Transition function pointer type */
typedef STATE_Driver_t (*TransitionFunc_Driver_t)(
    const TransitionContext_Driver_t *, SystemContext_t *);

/* ============================================================== */
/*  State transition table: rows=state, cols=event      */
/*  Global variable (externally accessible)                     */
/* ============================================================== */
const TransitionFunc_Driver_t transition_table_Driver
    [STATE_Driver_MAX][EVENT_Driver_MAX] = {
    /*                | INIT           | READY                | FAIL                | RESET          */
    /* --------------+--------------+--------------------+-------------------+--------------*/
    /* Idle          */ { t_Idle_INIT   , NULL                , NULL               , NULL           },
    /* Initializing  */ { NULL          , t_Initializing_READY, t_Initializing_FAIL, NULL           },
    /* Ready         */ { NULL          , NULL                , t_Ready_FAIL       , NULL           },
    /* Error         */ { NULL          , NULL                , NULL               , t_Error_RESET  },
};


/**
 * @brief  Cell transition: STATE_Driver_Idle -[EVENT_Driver_INIT]-> (multi)
 * @note   Transition count: 1
 */
static STATE_Driver_t t_Idle_INIT(
    const TransitionContext_Driver_t *transition,
    SystemContext_t *ctx
)
{
    STATE_Driver_t next_state = transition->from_state;
    bool _handled = false;

    /* ===== Cell actions (before_transitions) ===== */
    RoleFunc_Driver_PreCheck(transition, ctx);

    /* ===== Transition[T1] (Commit) ===== */
    if (!_handled && 1) {
        RoleFunc_Driver_IdleExit(transition, ctx);  /* state exit */
        RoleFunc_Driver_Init(transition, ctx);
        next_state = STATE_Driver_Initializing;
        RoleFunc_Driver_InitEntry(transition, ctx);  /* state entry */
        _handled = true;
    }

    /* ===== Cell actions (after_transitions) ===== */
    RoleFunc_Driver_Cleanup(transition, ctx);

    return next_state;
}

/**
 * @brief  Cell transition: STATE_Driver_Initializing -[EVENT_Driver_READY]-> (multi)
 * @note   Transition count: 2
 */
static STATE_Driver_t t_Initializing_READY(
    const TransitionContext_Driver_t *transition,
    SystemContext_t *ctx
)
{
    STATE_Driver_t next_state = transition->from_state;
    bool _handled = false;

    /* ===== Transition[T1] (Commit) ===== */
    if (!_handled && error_code == 0) {
        next_state = STATE_Driver_Ready;
        RoleFunc_Driver_ReadyEntry(transition, ctx);  /* state entry */
        _handled = true;
    }

    /* ===== Transition[T2] (Tentative) ===== */
    if (error_code != 0) {
        RoleFunc_Driver_LogError(transition, ctx);
        next_state = STATE_Driver_Error;
        RoleFunc_Driver_ErrorEntry(transition, ctx);  /* state entry */
    }

    return next_state;
}

/**
 * @brief  Cell transition: STATE_Driver_Initializing -[EVENT_Driver_FAIL]-> (multi)
 * @note   Transition count: 1
 */
static STATE_Driver_t t_Initializing_FAIL(
    const TransitionContext_Driver_t *transition,
    SystemContext_t *ctx
)
{
    STATE_Driver_t next_state = transition->from_state;
    bool _handled = false;

    /* ===== Transition[T1] (Commit) ===== */
    if (!_handled && 1) {
        RoleFunc_Driver_LogError(transition, ctx);
        next_state = STATE_Driver_Error;
        RoleFunc_Driver_ErrorEntry(transition, ctx);  /* state entry */
        _handled = true;
    }

    return next_state;
}

/**
 * @brief  Cell transition: STATE_Driver_Ready -[EVENT_Driver_FAIL]-> (multi)
 * @note   Transition count: 1
 */
static STATE_Driver_t t_Ready_FAIL(
    const TransitionContext_Driver_t *transition,
    SystemContext_t *ctx
)
{
    STATE_Driver_t next_state = transition->from_state;
    bool _handled = false;

    /* ===== Transition[T1] (Commit) ===== */
    if (!_handled && 1) {
        RoleFunc_Driver_LogError(transition, ctx);
        next_state = STATE_Driver_Error;
        RoleFunc_Driver_ErrorEntry(transition, ctx);  /* state entry */
        _handled = true;
    }

    return next_state;
}

/**
 * @brief  Cell transition: STATE_Driver_Error -[EVENT_Driver_RESET]-> (multi)
 * @note   Transition count: 2
 */
static STATE_Driver_t t_Error_RESET(
    const TransitionContext_Driver_t *transition,
    SystemContext_t *ctx
)
{
    STATE_Driver_t next_state = transition->from_state;
    bool _handled = false;

    /* ===== Group (shared_condition) ===== */
    if (running == false) {

        /* ===== Transition[T1] (Commit) ===== */
        if (!_handled && retry_count < 3) {
            RoleFunc_Driver_ErrorExit(transition, ctx);  /* state exit */
            RoleFunc_Driver_Reset(transition, ctx);
            next_state = STATE_Driver_Idle;
            RoleFunc_Driver_IdleEntry(transition, ctx);  /* state entry */
            _handled = true;
        } else if (!_handled && !(retry_count < 3)) {
            RoleFunc_Driver_ErrorExit(transition, ctx);  /* state exit */
            next_state = STATE_Driver_Error;
            RoleFunc_Driver_ErrorEntry(transition, ctx);  /* state entry */
            _handled = true;
        }

        /* ===== Transition[T2] (Commit) ===== */
        if (!_handled && retry_count >= 3) {
            RoleFunc_Driver_ErrorExit(transition, ctx);  /* state exit */
            next_state = STATE_Driver_Error;
            RoleFunc_Driver_ErrorEntry(transition, ctx);  /* state entry */
            _handled = true;
        }
    }

    return next_state;
}


/*==============================================================
 *  State transition functions
 *==============================================================*/

/**
 * @brief  Driver layer state transition processing
 * @param  current_state  Current state
 * @param  event          Event that occurred
 * @param  ctx            System context pointer
 * @return State after transition
 */
STATE_Driver_t StateMachine_Process_Driver(
    STATE_Driver_t current_state,
    EVENT_Driver_t event,
    SystemContext_t *ctx
)
{
    TransitionContext_Driver_t transition = {
        .from_state = current_state,
        .event = event,
    };
    TransitionFunc_Driver_t func = transition_table_Driver[current_state][event];
    if (func != NULL) {
        return func(&transition, ctx);
    }
    return current_state;
}
