/**
 * @file    statable_role_functions_Driver.h
 * @brief   Role function declarations
 *
 * @note    Code auto-generated by StaTable
 *          - Manual editing is not recommended
 *          - To modify, use StaTable
 *
 * @date    2026-09-20 15:22:57
 */

#ifndef STATABLE_ROLE_FUNCTIONS_H_DRIVER
#define STATABLE_ROLE_FUNCTIONS_H_DRIVER

/*==============================================================
 *  Include files
 *==============================================================*/

#include "statable_types_Driver.h"

/*==============================================================
 *  Role function declarations
 *==============================================================*/

/**
 * @brief  Role function: Idle entry
 * @note   Idle entry
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Driver_IdleEntry(
    const TransitionContext_Driver_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Idle exit
 * @note   Idle exit
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Driver_IdleExit(
    const TransitionContext_Driver_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Init entry
 * @note   Initializing entry
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Driver_InitEntry(
    const TransitionContext_Driver_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Ready entry
 * @note   Ready entry
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Driver_ReadyEntry(
    const TransitionContext_Driver_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Error entry
 * @note   Error entry
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Driver_ErrorEntry(
    const TransitionContext_Driver_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Error exit
 * @note   Error exit
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Driver_ErrorExit(
    const TransitionContext_Driver_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Driver init
 * @note   Driver init
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Driver_Init(
    const TransitionContext_Driver_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Log error
 * @note   Log error
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Driver_LogError(
    const TransitionContext_Driver_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Reset
 * @note   Reset
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Driver_Reset(
    const TransitionContext_Driver_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Pre-check
 * @note   Pre-check
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Driver_PreCheck(
    const TransitionContext_Driver_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Cleanup
 * @note   Cleanup
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Driver_Cleanup(
    const TransitionContext_Driver_t *transition,
    SystemContext_t *ctx
);



#endif /* STATABLE_ROLE_FUNCTIONS_H_DRIVER */