/**
 * @file    statable_role_functions_Driver.c
 * @brief   Role function implementations
 *
 * @note    Code auto-generated by StaTable
 *          - Manual editing is not recommended
 *          - To modify, use StaTable
 *
 * @date    2026-09-18 21:42:39
 */

/*==============================================================*/
 *  Include files
/*==============================================================*/

#include "statable_role_functions_Driver.h"

/*==============================================================*/
 *  Role function implementations
/*==============================================================*/


/* ============================================================== */
/*  Transition ID constant                                        */
/* ============================================================== */
#define TRANSITION_ID_NONE   ((uint16_t)0xFFFF)


/* ============================================================== */
/*  Role function call site table (common struct)                 */
/*  Identify cells by {from_state, event} pair                    */
/* ============================================================== */
typedef struct {
    STATE_Driver_t from_state;   /* source state */
    EVENT_Driver_t event;        /* event */
} RoleFuncCallSiteEntry_Driver_t;


/* Transition_GetId forward declaration (body at end of file) */
static uint16_t Transition_GetId(
    const TransitionContext_Driver_t *transition,
    const RoleFuncCallSiteEntry_Driver_t *table,
    uint16_t table_size);


/* --- call site table for Init --- */
static const RoleFuncCallSiteEntry_Driver_t call_sites_Init[] = {
    { STATE_Driver_Idle, EVENT_Driver_INIT },
};
#define CALL_SITES_Init_COUNT \
    (sizeof(call_sites_Init) / sizeof(call_sites_Init[0]))


/* --- call site table for LogError --- */
static const RoleFuncCallSiteEntry_Driver_t call_sites_LogError[] = {
    { STATE_Driver_Initializing, EVENT_Driver_READY },
    { STATE_Driver_Initializing, EVENT_Driver_FAIL },
    { STATE_Driver_Ready,        EVENT_Driver_FAIL },
};
#define CALL_SITES_LogError_COUNT \
    (sizeof(call_sites_LogError) / sizeof(call_sites_LogError[0]))


/* --- call site table for Reset --- */
static const RoleFuncCallSiteEntry_Driver_t call_sites_Reset[] = {
    { STATE_Driver_Error, EVENT_Driver_RESET },
};
#define CALL_SITES_Reset_COUNT \
    (sizeof(call_sites_Reset) / sizeof(call_sites_Reset[0]))


/**
 * @brief  Role function: ドライバ初期化
 * @note   ドライバ初期化
 *
 * @note   Call sites:
 *         - [pre_action]  STATE_Driver_Idle -[EVENT_Driver_INIT]-> STATE_Driver_Initializing
 */
int RoleFunc_Driver_Init(
    const TransitionContext_Driver_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Driver_t from_state = STATE_Driver_MAX;
    EVENT_Driver_t event = EVENT_Driver_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_Init, (uint16_t)CALL_SITES_Init_COUNT);

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* 汎用カウンタ */
    uint8_t *const error_code = &ctx->data.error_code;  /* エラーコード */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* リトライ回数 */
    bool *const rx_ready = &ctx->data.rx_ready;  /* RX 準備完了 */
    uint8_t *const rx_data = &ctx->data.rx_data;  /* RX 受信データ */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* タイマ基準 [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* 派生タイマ [10ms] */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:Driver_Init]] */
    /* ユーザー実装コードをここに記述 */

    /* [[STABLE_USER_CODE_END:Driver_Init]] */

    return ret;
}

/**
 * @brief  Role function: エラーログ
 * @note   エラーログ
 *
 * @note   Call sites:
 *         - [pre_action]  STATE_Driver_Initializing -[EVENT_Driver_READY]-> STATE_Driver_Error
 *         - [pre_action]  STATE_Driver_Initializing -[EVENT_Driver_FAIL]-> STATE_Driver_Error
 *         - [pre_action]  STATE_Driver_Ready        -[EVENT_Driver_FAIL]-> STATE_Driver_Error
 */
int RoleFunc_Driver_LogError(
    const TransitionContext_Driver_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Driver_t from_state = STATE_Driver_MAX;
    EVENT_Driver_t event = EVENT_Driver_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_LogError, (uint16_t)CALL_SITES_LogError_COUNT);

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* 汎用カウンタ */
    uint8_t *const error_code = &ctx->data.error_code;  /* エラーコード */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* リトライ回数 */
    bool *const rx_ready = &ctx->data.rx_ready;  /* RX 準備完了 */
    uint8_t *const rx_data = &ctx->data.rx_data;  /* RX 受信データ */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* タイマ基準 [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* 派生タイマ [10ms] */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:Driver_LogError]] */
    /* ユーザー実装コードをここに記述 */

    /* [[STABLE_USER_CODE_END:Driver_LogError]] */

    return ret;
}

/**
 * @brief  Role function: リセット処理
 * @note   リセット処理
 *
 * @note   Call sites:
 *         - [pre_action]  STATE_Driver_Error -[EVENT_Driver_RESET]-> STATE_Driver_Idle
 */
int RoleFunc_Driver_Reset(
    const TransitionContext_Driver_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Driver_t from_state = STATE_Driver_MAX;
    EVENT_Driver_t event = EVENT_Driver_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_Reset, (uint16_t)CALL_SITES_Reset_COUNT);

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* 汎用カウンタ */
    uint8_t *const error_code = &ctx->data.error_code;  /* エラーコード */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* リトライ回数 */
    bool *const rx_ready = &ctx->data.rx_ready;  /* RX 準備完了 */
    uint8_t *const rx_data = &ctx->data.rx_data;  /* RX 受信データ */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* タイマ基準 [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* 派生タイマ [10ms] */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:Driver_Reset]] */
    /* ユーザー実装コードをここに記述 */

    /* [[STABLE_USER_CODE_END:Driver_Reset]] */

    return ret;
}

/**
 * @brief  Role function: RX確認（ISR用）
 * @note   RX確認処理
 *
 * @note   Call sites: (none)
 */
int RoleFunc_Driver_CheckRx(
    const TransitionContext_Driver_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Driver_t from_state = STATE_Driver_MAX;
    EVENT_Driver_t event = EVENT_Driver_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, NULL, 0);

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* 汎用カウンタ */
    uint8_t *const error_code = &ctx->data.error_code;  /* エラーコード */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* リトライ回数 */
    bool *const rx_ready = &ctx->data.rx_ready;  /* RX 準備完了 */
    uint8_t *const rx_data = &ctx->data.rx_data;  /* RX 受信データ */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* タイマ基準 [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* 派生タイマ [10ms] */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:Driver_CheckRx]] */
    /* ユーザー実装コードをここに記述 */

    /* [[STABLE_USER_CODE_END:Driver_CheckRx]] */

    return ret;
}



/* ============================================================== */
/*  Transition ID conversion (end of file)                        */
/*  Linearly scans the per-function call_sites table and          */
/*  returns the index of the matching entry.                      */
/*  Returns TRANSITION_ID_NONE if no match / transition==NULL.    */
/* ============================================================== */
/**
 * @brief  Convert transition info to a unique ID
 * @param  transition  Transition context (may be NULL)
 * @param  table       Call site table (may be NULL)
 * @param  table_size  Number of entries in the table
 * @return Index in the table (TRANSITION_ID_NONE if no match)
 */
static uint16_t Transition_GetId(
    const TransitionContext_Driver_t *transition,
    const RoleFuncCallSiteEntry_Driver_t *table,
    uint16_t table_size)
{
    uint16_t i;

    if (transition == NULL || table == NULL) {
        return TRANSITION_ID_NONE;
    }

    for (i = 0; i < table_size; i++) {
        if (table[i].from_state == transition->from_state &&
            table[i].event      == transition->event) {
            return i;
        }
    }
    return TRANSITION_ID_NONE;
}


/* ============================================================== */
/*  User-added area                                               */
/*  Code added here is preserved across regenerations             */
/* ============================================================== */
/* [[STABLE_USER_CODE_TAIL_START]] */
/* ユーザー追加コードをここに記述（ヘルパー関数など） */

/* [[STABLE_USER_CODE_TAIL_END]] */
