/**
 * @file    statable_transitions_Driver.h
 * @brief   State transition function declarations
 *
 * @note    Code auto-generated by StaTable
 *          - Manual editing is not recommended
 *          - To modify, use StaTable
 *
 * @date    2026-09-19 23:27:07
 */

#ifndef STATABLE_TRANSITIONS_H_DRIVER
#define STATABLE_TRANSITIONS_H_DRIVER

/*==============================================================
 *  Include files
 *==============================================================*/

#include "statable_types_Driver.h"

/*==============================================================
 *  Function declarations
 *==============================================================*/

/**
 * @brief  State transition processing
 * @param  current_state  Current state
 * @param  event          Event that occurred
 * @param  ctx            System context pointer
 * @return State after transition
 */
STATE_Driver_t StateMachine_Process_Driver(
    STATE_Driver_t current_state,
    EVENT_Driver_t event,
    SystemContext_t *ctx
);

#endif /* STATABLE_TRANSITIONS_H_DRIVER */