/**
 * @file    statable_role_functions_Middleware.h
 * @brief   Role function declarations
 *
 * @note    Code auto-generated by StaTable
 *          - Manual editing is not recommended
 *          - To modify, use StaTable
 *
 * @date    2026-09-19 19:54:26
 */

#ifndef STATABLE_ROLE_FUNCTIONS_H_MIDDLEWARE
#define STATABLE_ROLE_FUNCTIONS_H_MIDDLEWARE

/*==============================================================
 *  Include files
 *==============================================================*/

#include "statable_types_Middleware.h"

/*==============================================================
 *  Role function declarations
 *==============================================================*/

/**
 * @brief  Role function: Idle entry
 * @note   Idle entry
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Middleware_IdleEntry(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Connecting entry
 * @note   Connecting entry
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Middleware_ConnEntry(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Connecting exit
 * @note   Connecting exit
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Middleware_ConnExit(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Connected entry
 * @note   Connected entry
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Middleware_ConnOkEntry(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Error entry
 * @note   Error entry
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Middleware_ErrorEntry(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Connect
 * @note   Connect
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Middleware_Connect(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Handle error
 * @note   Handle error
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Middleware_HandleErr(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Retry
 * @note   Retry
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Middleware_Retry(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Before connect
 * @note   Before connect
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Middleware_BeforeConnect(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Idle exit
 * @note   Idle exit
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Driver_IdleExit(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Init entry
 * @note   Initializing entry
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Driver_InitEntry(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Ready entry
 * @note   Ready entry
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Driver_ReadyEntry(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Error exit
 * @note   Error exit
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Driver_ErrorExit(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Driver init
 * @note   Driver init
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Driver_Init(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Log error
 * @note   Log error
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Driver_LogError(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Reset
 * @note   Reset
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Driver_Reset(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Pre-check
 * @note   Pre-check
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Driver_PreCheck(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Cleanup
 * @note   Cleanup
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Driver_Cleanup(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Boot entry
 * @note   Boot entry
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_BootEntry(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Boot exit
 * @note   Boot exit
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_BootExit(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Running entry 1
 * @note   Running entry 1
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_RunEntry1(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Running entry 2
 * @note   Running entry 2
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_RunEntry2(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Paused entry
 * @note   Paused entry
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_PauseEntry(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Stopped entry
 * @note   Stopped entry
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_StopEntry(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: App boot
 * @note   App boot
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_Boot(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: App start
 * @note   App start
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_Start(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: App pause
 * @note   App pause
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_Pause(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: App resume
 * @note   App resume
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_Resume(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Handle stop
 * @note   Handle stop
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_HandleStop(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Pre (before transitions)
 * @note   Runs before evaluating transitions
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_Pre(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Post (after transitions)
 * @note   Runs after evaluating transitions
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_App_Post(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
);



#endif /* STATABLE_ROLE_FUNCTIONS_H_MIDDLEWARE */