/**
 * @file    statable_transitions_Middleware.h
 * @brief   State transition function declarations
 *
 * @note    Code auto-generated by StaTable
 *          - Manual editing is not recommended
 *          - To modify, use StaTable
 *
 * @date    2026-09-19 19:54:26
 */

#ifndef STATABLE_TRANSITIONS_H_MIDDLEWARE
#define STATABLE_TRANSITIONS_H_MIDDLEWARE

/*==============================================================
 *  Include files
 *==============================================================*/

#include "statable_types_Middleware.h"

/*==============================================================
 *  Function declarations
 *==============================================================*/

/**
 * @brief  State transition processing
 * @param  current_state  Current state
 * @param  event          Event that occurred
 * @param  ctx            System context pointer
 * @return State after transition
 */
STATE_Middleware_t StateMachine_Process_Middleware(
    STATE_Middleware_t current_state,
    EVENT_Middleware_t event,
    SystemContext_t *ctx
);

#endif /* STATABLE_TRANSITIONS_H_MIDDLEWARE */