/**
 * @file    statable_role_functions_Middleware.c
 * @brief   Role function implementations
 *
 * @note    Code auto-generated by StaTable
 *          - Manual editing is not recommended
 *          - To modify, use StaTable
 *
 * @date    2026-09-18 21:42:39
 */

/*==============================================================*/
 *  Include files
/*==============================================================*/

#include "statable_role_functions_Middleware.h"

/*==============================================================*/
 *  Role function implementations
/*==============================================================*/


/* ============================================================== */
/*  Transition ID constant                                        */
/* ============================================================== */
#define TRANSITION_ID_NONE   ((uint16_t)0xFFFF)


/* ============================================================== */
/*  Role function call site table (common struct)                 */
/*  Identify cells by {from_state, event} pair                    */
/* ============================================================== */
typedef struct {
    STATE_Middleware_t from_state;   /* source state */
    EVENT_Middleware_t event;        /* event */
} RoleFuncCallSiteEntry_Middleware_t;


/* Transition_GetId forward declaration (body at end of file) */
static uint16_t Transition_GetId(
    const TransitionContext_Middleware_t *transition,
    const RoleFuncCallSiteEntry_Middleware_t *table,
    uint16_t table_size);


/* --- call site table for Connect --- */
static const RoleFuncCallSiteEntry_Middleware_t call_sites_Connect[] = {
    { STATE_Middleware_Idle, EVENT_Middleware_CONNECT },
};
#define CALL_SITES_Connect_COUNT \
    (sizeof(call_sites_Connect) / sizeof(call_sites_Connect[0]))


/* --- call site table for HandleErr --- */
static const RoleFuncCallSiteEntry_Middleware_t call_sites_HandleErr[] = {
    { STATE_Middleware_Connecting, EVENT_Middleware_CONNECTED },
    { STATE_Middleware_Connecting, EVENT_Middleware_ERROR },
    { STATE_Middleware_Connected,  EVENT_Middleware_ERROR },
};
#define CALL_SITES_HandleErr_COUNT \
    (sizeof(call_sites_HandleErr) / sizeof(call_sites_HandleErr[0]))


/* --- call site table for Retry --- */
static const RoleFuncCallSiteEntry_Middleware_t call_sites_Retry[] = {
    { STATE_Middleware_Error, EVENT_Middleware_RETRY },
};
#define CALL_SITES_Retry_COUNT \
    (sizeof(call_sites_Retry) / sizeof(call_sites_Retry[0]))


/**
 * @brief  Role function: 接続処理
 * @note   接続処理
 *
 * @note   Call sites:
 *         - [pre_action]  STATE_Middleware_Idle -[EVENT_Middleware_CONNECT]-> STATE_Middleware_Connecting
 */
int RoleFunc_Middleware_Connect(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Middleware_t from_state = STATE_Middleware_MAX;
    EVENT_Middleware_t event = EVENT_Middleware_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_Connect, (uint16_t)CALL_SITES_Connect_COUNT);

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* 汎用カウンタ */
    uint8_t *const error_code = &ctx->data.error_code;  /* エラーコード */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* リトライ回数 */
    bool *const rx_ready = &ctx->data.rx_ready;  /* RX 準備完了 */
    uint8_t *const rx_data = &ctx->data.rx_data;  /* RX 受信データ */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* タイマ基準 [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* 派生タイマ [10ms] */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:Middleware_Connect]] */
    /* ユーザー実装コードをここに記述 */

    /* [[STABLE_USER_CODE_END:Middleware_Connect]] */

    return ret;
}

/**
 * @brief  Role function: エラー処理
 * @note   エラー処理
 *
 * @note   Call sites:
 *         - [pre_action]  STATE_Middleware_Connecting -[EVENT_Middleware_CONNECTED]-> STATE_Middleware_Error
 *         - [pre_action]  STATE_Middleware_Connecting -[EVENT_Middleware_ERROR]-> STATE_Middleware_Error
 *         - [pre_action]  STATE_Middleware_Connected  -[EVENT_Middleware_ERROR]-> STATE_Middleware_Error
 */
int RoleFunc_Middleware_HandleErr(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Middleware_t from_state = STATE_Middleware_MAX;
    EVENT_Middleware_t event = EVENT_Middleware_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_HandleErr, (uint16_t)CALL_SITES_HandleErr_COUNT);

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* 汎用カウンタ */
    uint8_t *const error_code = &ctx->data.error_code;  /* エラーコード */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* リトライ回数 */
    bool *const rx_ready = &ctx->data.rx_ready;  /* RX 準備完了 */
    uint8_t *const rx_data = &ctx->data.rx_data;  /* RX 受信データ */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* タイマ基準 [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* 派生タイマ [10ms] */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:Middleware_HandleErr]] */
    /* ユーザー実装コードをここに記述 */

    /* [[STABLE_USER_CODE_END:Middleware_HandleErr]] */

    return ret;
}

/**
 * @brief  Role function: 再試行処理
 * @note   再試行処理
 *
 * @note   Call sites:
 *         - [pre_action]  STATE_Middleware_Error -[EVENT_Middleware_RETRY]-> STATE_Middleware_Idle
 */
int RoleFunc_Middleware_Retry(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Middleware_t from_state = STATE_Middleware_MAX;
    EVENT_Middleware_t event = EVENT_Middleware_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_Retry, (uint16_t)CALL_SITES_Retry_COUNT);

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* 汎用カウンタ */
    uint8_t *const error_code = &ctx->data.error_code;  /* エラーコード */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* リトライ回数 */
    bool *const rx_ready = &ctx->data.rx_ready;  /* RX 準備完了 */
    uint8_t *const rx_data = &ctx->data.rx_data;  /* RX 受信データ */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* タイマ基準 [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* 派生タイマ [10ms] */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:Middleware_Retry]] */
    /* ユーザー実装コードをここに記述 */

    /* [[STABLE_USER_CODE_END:Middleware_Retry]] */

    return ret;
}



/* ============================================================== */
/*  Transition ID conversion (end of file)                        */
/*  Linearly scans the per-function call_sites table and          */
/*  returns the index of the matching entry.                      */
/*  Returns TRANSITION_ID_NONE if no match / transition==NULL.    */
/* ============================================================== */
/**
 * @brief  Convert transition info to a unique ID
 * @param  transition  Transition context (may be NULL)
 * @param  table       Call site table (may be NULL)
 * @param  table_size  Number of entries in the table
 * @return Index in the table (TRANSITION_ID_NONE if no match)
 */
static uint16_t Transition_GetId(
    const TransitionContext_Middleware_t *transition,
    const RoleFuncCallSiteEntry_Middleware_t *table,
    uint16_t table_size)
{
    uint16_t i;

    if (transition == NULL || table == NULL) {
        return TRANSITION_ID_NONE;
    }

    for (i = 0; i < table_size; i++) {
        if (table[i].from_state == transition->from_state &&
            table[i].event      == transition->event) {
            return i;
        }
    }
    return TRANSITION_ID_NONE;
}


/* ============================================================== */
/*  User-added area                                               */
/*  Code added here is preserved across regenerations             */
/* ============================================================== */
/* [[STABLE_USER_CODE_TAIL_START]] */
/* ユーザー追加コードをここに記述（ヘルパー関数など） */

/* [[STABLE_USER_CODE_TAIL_END]] */
