/**
 * @file    statable_transitions_Middleware.c
 * @brief   State transition logic
 *
 * @note    Code auto-generated by StaTable
 *          - Manual editing is not recommended
 *          - To modify, use StaTable
 *
 * @date    2026-09-19 23:27:07
 */

/*==============================================================
 *  Include files
 *==============================================================*/

#include "statable_transitions_Middleware.h"
#include "statable_role_functions_Middleware.h"

/*==============================================================
 *  State transition table
 *==============================================================*/

/* ===== Cell transition function forward declarations ===== */
static STATE_Middleware_t t_Idle_CONNECT(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx);
static STATE_Middleware_t t_Connecting_CONNECTED(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx);
static STATE_Middleware_t t_Connecting_ERROR(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx);
static STATE_Middleware_t t_Connected_ERROR(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx);
static STATE_Middleware_t t_Error_RETRY(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx);


/* Transition function pointer type */
typedef STATE_Middleware_t (*TransitionFunc_Middleware_t)(
    const TransitionContext_Middleware_t *, SystemContext_t *);

/* ============================================================== */
/*  State transition table: rows=state, cols=event      */
/*  Global variable (externally accessible)                     */
/* ============================================================== */
const TransitionFunc_Middleware_t transition_table_Middleware
    [STATE_Middleware_MAX][EVENT_Middleware_MAX] = {
    /*              | CONNECT        | CONNECTED              | ERROR              | RETRY          */
    /* ------------+--------------+----------------------+------------------+--------------*/
    /* Idle        */ { t_Idle_CONNECT, NULL                  , NULL              , NULL           },
    /* Connecting  */ { NULL          , t_Connecting_CONNECTED, t_Connecting_ERROR, NULL           },
    /* Connected   */ { NULL          , NULL                  , t_Connected_ERROR , NULL           },
    /* Error       */ { NULL          , NULL                  , NULL              , t_Error_RETRY  },
};


/**
 * @brief  Cell transition: STATE_Middleware_Idle -[EVENT_Middleware_CONNECT]-> (multi)
 * @note   Transition count: 1
 */
static STATE_Middleware_t t_Idle_CONNECT(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
)
{
    STATE_Middleware_t next_state = transition->from_state;
    bool _handled = false;

    /* ===== Transition[T1] (Commit) ===== */
    if (!_handled && 1) {
        RoleFunc_Middleware_Connect(transition, ctx);
        next_state = STATE_Middleware_Connecting;
        RoleFunc_Middleware_ConnEntry(transition, ctx);  /* state entry */
        _handled = true;
    }

    return next_state;
}

/**
 * @brief  Cell transition: STATE_Middleware_Connecting -[EVENT_Middleware_CONNECTED]-> (multi)
 * @note   Transition count: 2
 */
static STATE_Middleware_t t_Connecting_CONNECTED(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
)
{
    STATE_Middleware_t next_state = transition->from_state;
    bool _handled = false;

    /* ===== Group (shared_condition) ===== */
    if (error_code == 0) {

        /* ===== Transition[T1] (Commit) ===== */
        if (!_handled && retry_count < 3) {
            RoleFunc_Middleware_ConnExit(transition, ctx);  /* state exit */
            next_state = STATE_Middleware_Connected;
            RoleFunc_Middleware_ConnOkEntry(transition, ctx);  /* state entry */
            _handled = true;
        }

        /* ===== Transition[T2] (Commit) ===== */
        if (!_handled && retry_count >= 3) {
            RoleFunc_Middleware_ConnExit(transition, ctx);  /* state exit */
            RoleFunc_Middleware_HandleErr(transition, ctx);
            next_state = STATE_Middleware_Error;
            RoleFunc_Middleware_ErrorEntry(transition, ctx);  /* state entry */
            _handled = true;
        }
    }

    return next_state;
}

/**
 * @brief  Cell transition: STATE_Middleware_Connecting -[EVENT_Middleware_ERROR]-> (multi)
 * @note   Transition count: 1
 */
static STATE_Middleware_t t_Connecting_ERROR(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
)
{
    STATE_Middleware_t next_state = transition->from_state;
    bool _handled = false;

    /* ===== Transition[T1] (Commit) ===== */
    if (!_handled && 1) {
        RoleFunc_Middleware_ConnExit(transition, ctx);  /* state exit */
        RoleFunc_Middleware_HandleErr(transition, ctx);
        next_state = STATE_Middleware_Error;
        RoleFunc_Middleware_ErrorEntry(transition, ctx);  /* state entry */
        _handled = true;
    } else if (!_handled && !(1)) {
        RoleFunc_Middleware_ConnExit(transition, ctx);  /* state exit */
        RoleFunc_Middleware_Retry(transition, ctx);
        next_state = STATE_Middleware_Idle;
        RoleFunc_Middleware_IdleEntry(transition, ctx);  /* state entry */
        _handled = true;
    }

    return next_state;
}

/**
 * @brief  Cell transition: STATE_Middleware_Connected -[EVENT_Middleware_ERROR]-> (multi)
 * @note   Transition count: 1
 */
static STATE_Middleware_t t_Connected_ERROR(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
)
{
    STATE_Middleware_t next_state = transition->from_state;
    bool _handled = false;

    /* ===== Transition[T1] (Commit) ===== */
    if (!_handled && 1) {
        RoleFunc_Middleware_HandleErr(transition, ctx);
        next_state = STATE_Middleware_Error;
        RoleFunc_Middleware_ErrorEntry(transition, ctx);  /* state entry */
        _handled = true;
    }

    return next_state;
}

/**
 * @brief  Cell transition: STATE_Middleware_Error -[EVENT_Middleware_RETRY]-> (multi)
 * @note   Transition count: 2
 */
static STATE_Middleware_t t_Error_RETRY(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
)
{
    STATE_Middleware_t next_state = transition->from_state;
    bool _handled = false;

    /* ===== Transition[T1] (Commit) ===== */
    if (!_handled && retry_count < 3) {
        RoleFunc_Middleware_Retry(transition, ctx);
        next_state = STATE_Middleware_Idle;
        RoleFunc_Middleware_IdleEntry(transition, ctx);  /* state entry */
        _handled = true;
    }

    /* ===== Transition[T2] (Tentative) ===== */
    if (retry_count >= 3) {
        next_state = STATE_Middleware_Error;
        RoleFunc_Middleware_ErrorEntry(transition, ctx);  /* state entry */
    }

    return next_state;
}


/*==============================================================
 *  State transition functions
 *==============================================================*/

/**
 * @brief  Middleware layer state transition processing
 * @param  current_state  Current state
 * @param  event          Event that occurred
 * @param  ctx            System context pointer
 * @return State after transition
 */
STATE_Middleware_t StateMachine_Process_Middleware(
    STATE_Middleware_t current_state,
    EVENT_Middleware_t event,
    SystemContext_t *ctx
)
{
    TransitionContext_Middleware_t transition = {
        .from_state = current_state,
        .event = event,
    };
    TransitionFunc_Middleware_t func = transition_table_Middleware[current_state][event];
    if (func != NULL) {
        return func(&transition, ctx);
    }
    return current_state;
}
