/**
 * @file    statable_role_functions_Middleware.h
 * @brief   Role function declarations
 *
 * @note    Code auto-generated by StaTable
 *          - Manual editing is not recommended
 *          - To modify, use StaTable
 *
 * @date    2026-09-20 08:37:00
 */

#ifndef STATABLE_ROLE_FUNCTIONS_H_MIDDLEWARE
#define STATABLE_ROLE_FUNCTIONS_H_MIDDLEWARE

/*==============================================================
 *  Include files
 *==============================================================*/

#include "statable_types_Middleware.h"

/*==============================================================
 *  Role function declarations
 *==============================================================*/

/**
 * @brief  Role function: Idle entry
 * @note   Idle entry
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Middleware_IdleEntry(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Connecting entry
 * @note   Connecting entry
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Middleware_ConnEntry(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Connecting exit
 * @note   Connecting exit
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Middleware_ConnExit(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Connected entry
 * @note   Connected entry
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Middleware_ConnOkEntry(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Error entry
 * @note   Error entry
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Middleware_ErrorEntry(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Connect
 * @note   Connect
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Middleware_Connect(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Handle error
 * @note   Handle error
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Middleware_HandleErr(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Retry
 * @note   Retry
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Middleware_Retry(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
);

/**
 * @brief  Role function: Before connect
 * @note   Before connect
 * @param  transition  Transition context (may be NULL: called from ISR)
 * @param  ctx         System context pointer
 * @return 0: success, non-zero: error (can also be used for condition checks)
 */
int RoleFunc_Middleware_BeforeConnect(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
);



#endif /* STATABLE_ROLE_FUNCTIONS_H_MIDDLEWARE */