/**
 * @file    statable_role_functions_Middleware.c
 * @brief   Role function implementations
 *
 * @note    Code auto-generated by StaTable
 *          - Manual editing is not recommended
 *          - To modify, use StaTable
 *
 * @date    2026-09-20 08:37:00
 */

/*==============================================================
 *  Include files
 *==============================================================*/

#include "statable_role_functions_Middleware.h"
#include "Driver/statable_role_functions_Driver.h"
#include "Application/statable_role_functions_Application.h"

/*==============================================================
 *  Role function implementations
 *==============================================================*/


/* ============================================================== */
/*  Transition ID constant                                        */
/* ============================================================== */
#define TRANSITION_ID_NONE   ((uint16_t)0xFFFF)


/* ============================================================== */
/*  Role function call site table (common struct)                 */
/*  Identify cells by {from_state, event} pair                    */
/* ============================================================== */
typedef struct {
    STATE_Middleware_t from_state;   /* source state */
    EVENT_Middleware_t event;        /* event */
} RoleFuncCallSiteEntry_Middleware_t;


/* Transition_GetId forward declaration (body at end of file) */
static uint16_t Transition_GetId(
    const TransitionContext_Middleware_t *transition,
    const RoleFuncCallSiteEntry_Middleware_t *table,
    uint16_t table_size);


/* --- call site table for IdleEntry --- */
static const RoleFuncCallSiteEntry_Middleware_t call_sites_IdleEntry[] = {
    { STATE_Middleware_Idle, EVENT_Middleware_NONE },
};
#define CALL_SITES_IdleEntry_COUNT \
    (sizeof(call_sites_IdleEntry) / sizeof(call_sites_IdleEntry[0]))


/* --- call site table for ConnEntry --- */
static const RoleFuncCallSiteEntry_Middleware_t call_sites_ConnEntry[] = {
    { STATE_Middleware_Connecting, EVENT_Middleware_NONE },
};
#define CALL_SITES_ConnEntry_COUNT \
    (sizeof(call_sites_ConnEntry) / sizeof(call_sites_ConnEntry[0]))


/* --- call site table for ConnExit --- */
static const RoleFuncCallSiteEntry_Middleware_t call_sites_ConnExit[] = {
    { STATE_Middleware_Connecting, EVENT_Middleware_NONE },
};
#define CALL_SITES_ConnExit_COUNT \
    (sizeof(call_sites_ConnExit) / sizeof(call_sites_ConnExit[0]))


/* --- call site table for ConnOkEntry --- */
static const RoleFuncCallSiteEntry_Middleware_t call_sites_ConnOkEntry[] = {
    { STATE_Middleware_Connected, EVENT_Middleware_NONE },
};
#define CALL_SITES_ConnOkEntry_COUNT \
    (sizeof(call_sites_ConnOkEntry) / sizeof(call_sites_ConnOkEntry[0]))


/* --- call site table for ErrorEntry --- */
static const RoleFuncCallSiteEntry_Middleware_t call_sites_ErrorEntry[] = {
    { STATE_Middleware_Error, EVENT_Middleware_NONE },
};
#define CALL_SITES_ErrorEntry_COUNT \
    (sizeof(call_sites_ErrorEntry) / sizeof(call_sites_ErrorEntry[0]))


/* --- call site table for Connect --- */
static const RoleFuncCallSiteEntry_Middleware_t call_sites_Connect[] = {
    { STATE_Middleware_Idle, EVENT_Middleware_CONNECT },
};
#define CALL_SITES_Connect_COUNT \
    (sizeof(call_sites_Connect) / sizeof(call_sites_Connect[0]))


/* --- call site table for HandleErr --- */
static const RoleFuncCallSiteEntry_Middleware_t call_sites_HandleErr[] = {
    { STATE_Middleware_Connecting, EVENT_Middleware_CONNECTED },
    { STATE_Middleware_Connecting, EVENT_Middleware_ERROR },
    { STATE_Middleware_Connected,  EVENT_Middleware_ERROR },
};
#define CALL_SITES_HandleErr_COUNT \
    (sizeof(call_sites_HandleErr) / sizeof(call_sites_HandleErr[0]))


/* --- call site table for Retry --- */
static const RoleFuncCallSiteEntry_Middleware_t call_sites_Retry[] = {
    { STATE_Middleware_Connecting, EVENT_Middleware_ERROR },
    { STATE_Middleware_Error,      EVENT_Middleware_RETRY },
};
#define CALL_SITES_Retry_COUNT \
    (sizeof(call_sites_Retry) / sizeof(call_sites_Retry[0]))


/**
 * @brief  Role function: Idle entry
 * @note   Idle entry
 *
 * @note   Call sites:
 *         - [state_entry]  STATE_Middleware_Idle -[EVENT_Middleware_NONE]-> STATE_Middleware_Idle
 */
int RoleFunc_Middleware_IdleEntry(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Middleware_t from_state = STATE_Middleware_MAX;
    EVENT_Middleware_t event = EVENT_Middleware_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_IdleEntry, (uint16_t)CALL_SITES_IdleEntry_COUNT);
    (void)transition_id;   /* suppress unused warning */

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */
    (void)counter;   /* suppress unused warning */
    (void)error_code;   /* suppress unused warning */
    (void)retry_count;   /* suppress unused warning */
    (void)running;   /* suppress unused warning */
    (void)g_system_tick;   /* suppress unused warning */
    (void)g_tick_10ms;   /* suppress unused warning */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:Middleware_IdleEntry]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:Middleware_IdleEntry]] */

    return ret;
}

/**
 * @brief  Role function: Connecting entry
 * @note   Connecting entry
 *
 * @note   Call sites:
 *         - [state_entry]  STATE_Middleware_Connecting -[EVENT_Middleware_NONE]-> STATE_Middleware_Connecting
 */
int RoleFunc_Middleware_ConnEntry(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Middleware_t from_state = STATE_Middleware_MAX;
    EVENT_Middleware_t event = EVENT_Middleware_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_ConnEntry, (uint16_t)CALL_SITES_ConnEntry_COUNT);
    (void)transition_id;   /* suppress unused warning */

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */
    (void)counter;   /* suppress unused warning */
    (void)error_code;   /* suppress unused warning */
    (void)retry_count;   /* suppress unused warning */
    (void)running;   /* suppress unused warning */
    (void)g_system_tick;   /* suppress unused warning */
    (void)g_tick_10ms;   /* suppress unused warning */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:Middleware_ConnEntry]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:Middleware_ConnEntry]] */

    return ret;
}

/**
 * @brief  Role function: Connecting exit
 * @note   Connecting exit
 *
 * @note   Call sites:
 *         - [state_exit]  STATE_Middleware_Connecting -[EVENT_Middleware_NONE]-> STATE_Middleware_Connecting
 */
int RoleFunc_Middleware_ConnExit(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Middleware_t from_state = STATE_Middleware_MAX;
    EVENT_Middleware_t event = EVENT_Middleware_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_ConnExit, (uint16_t)CALL_SITES_ConnExit_COUNT);
    (void)transition_id;   /* suppress unused warning */

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */
    (void)counter;   /* suppress unused warning */
    (void)error_code;   /* suppress unused warning */
    (void)retry_count;   /* suppress unused warning */
    (void)running;   /* suppress unused warning */
    (void)g_system_tick;   /* suppress unused warning */
    (void)g_tick_10ms;   /* suppress unused warning */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:Middleware_ConnExit]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:Middleware_ConnExit]] */

    return ret;
}

/**
 * @brief  Role function: Connected entry
 * @note   Connected entry
 *
 * @note   Call sites:
 *         - [state_entry]  STATE_Middleware_Connected -[EVENT_Middleware_NONE]-> STATE_Middleware_Connected
 */
int RoleFunc_Middleware_ConnOkEntry(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Middleware_t from_state = STATE_Middleware_MAX;
    EVENT_Middleware_t event = EVENT_Middleware_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_ConnOkEntry, (uint16_t)CALL_SITES_ConnOkEntry_COUNT);
    (void)transition_id;   /* suppress unused warning */

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */
    (void)counter;   /* suppress unused warning */
    (void)error_code;   /* suppress unused warning */
    (void)retry_count;   /* suppress unused warning */
    (void)running;   /* suppress unused warning */
    (void)g_system_tick;   /* suppress unused warning */
    (void)g_tick_10ms;   /* suppress unused warning */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:Middleware_ConnOkEntry]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:Middleware_ConnOkEntry]] */

    return ret;
}

/**
 * @brief  Role function: Error entry
 * @note   Error entry
 *
 * @note   Call sites:
 *         - [state_entry]  STATE_Middleware_Error -[EVENT_Middleware_NONE]-> STATE_Middleware_Error
 */
int RoleFunc_Middleware_ErrorEntry(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Middleware_t from_state = STATE_Middleware_MAX;
    EVENT_Middleware_t event = EVENT_Middleware_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_ErrorEntry, (uint16_t)CALL_SITES_ErrorEntry_COUNT);
    (void)transition_id;   /* suppress unused warning */

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */
    (void)counter;   /* suppress unused warning */
    (void)error_code;   /* suppress unused warning */
    (void)retry_count;   /* suppress unused warning */
    (void)running;   /* suppress unused warning */
    (void)g_system_tick;   /* suppress unused warning */
    (void)g_tick_10ms;   /* suppress unused warning */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:Middleware_ErrorEntry]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:Middleware_ErrorEntry]] */

    return ret;
}

/**
 * @brief  Role function: Connect
 * @note   Connect
 *
 * @note   Call sites:
 *         - [pre_action]  STATE_Middleware_Idle -[EVENT_Middleware_CONNECT]-> STATE_Middleware_Connecting
 */
int RoleFunc_Middleware_Connect(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Middleware_t from_state = STATE_Middleware_MAX;
    EVENT_Middleware_t event = EVENT_Middleware_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_Connect, (uint16_t)CALL_SITES_Connect_COUNT);
    (void)transition_id;   /* suppress unused warning */

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */
    (void)counter;   /* suppress unused warning */
    (void)error_code;   /* suppress unused warning */
    (void)retry_count;   /* suppress unused warning */
    (void)running;   /* suppress unused warning */
    (void)g_system_tick;   /* suppress unused warning */
    (void)g_tick_10ms;   /* suppress unused warning */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:Middleware_Connect]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:Middleware_Connect]] */

    return ret;
}

/**
 * @brief  Role function: Handle error
 * @note   Handle error
 *
 * @note   Call sites:
 *         - [pre_action]  STATE_Middleware_Connecting -[EVENT_Middleware_CONNECTED]-> STATE_Middleware_Error
 *         - [pre_action]  STATE_Middleware_Connecting -[EVENT_Middleware_ERROR]-> STATE_Middleware_Error
 *         - [pre_action]  STATE_Middleware_Connected  -[EVENT_Middleware_ERROR]-> STATE_Middleware_Error
 */
int RoleFunc_Middleware_HandleErr(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Middleware_t from_state = STATE_Middleware_MAX;
    EVENT_Middleware_t event = EVENT_Middleware_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_HandleErr, (uint16_t)CALL_SITES_HandleErr_COUNT);
    (void)transition_id;   /* suppress unused warning */

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */
    (void)counter;   /* suppress unused warning */
    (void)error_code;   /* suppress unused warning */
    (void)retry_count;   /* suppress unused warning */
    (void)running;   /* suppress unused warning */
    (void)g_system_tick;   /* suppress unused warning */
    (void)g_tick_10ms;   /* suppress unused warning */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:Middleware_HandleErr]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:Middleware_HandleErr]] */

    return ret;
}

/**
 * @brief  Role function: Retry
 * @note   Retry
 *
 * @note   Call sites:
 *         - [else_action]  STATE_Middleware_Connecting -[EVENT_Middleware_ERROR]-> STATE_Middleware_Idle
 *         - [pre_action]   STATE_Middleware_Error      -[EVENT_Middleware_RETRY]-> STATE_Middleware_Idle
 */
int RoleFunc_Middleware_Retry(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Middleware_t from_state = STATE_Middleware_MAX;
    EVENT_Middleware_t event = EVENT_Middleware_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_Retry, (uint16_t)CALL_SITES_Retry_COUNT);
    (void)transition_id;   /* suppress unused warning */

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */
    (void)counter;   /* suppress unused warning */
    (void)error_code;   /* suppress unused warning */
    (void)retry_count;   /* suppress unused warning */
    (void)running;   /* suppress unused warning */
    (void)g_system_tick;   /* suppress unused warning */
    (void)g_tick_10ms;   /* suppress unused warning */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:Middleware_Retry]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:Middleware_Retry]] */

    return ret;
}

/**
 * @brief  Role function: Before connect
 * @note   Before connect
 *
 * @note   Call sites: (none)
 */
int RoleFunc_Middleware_BeforeConnect(
    const TransitionContext_Middleware_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Middleware_t from_state = STATE_Middleware_MAX;
    EVENT_Middleware_t event = EVENT_Middleware_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, NULL, 0);
    (void)transition_id;   /* suppress unused warning */

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */
    (void)counter;   /* suppress unused warning */
    (void)error_code;   /* suppress unused warning */
    (void)retry_count;   /* suppress unused warning */
    (void)running;   /* suppress unused warning */
    (void)g_system_tick;   /* suppress unused warning */
    (void)g_tick_10ms;   /* suppress unused warning */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:Middleware_BeforeConnect]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:Middleware_BeforeConnect]] */

    return ret;
}



/* ============================================================== */
/*  Transition ID conversion (end of file)                        */
/*  Linearly scans the per-function call_sites table and          */
/*  returns the index of the matching entry.                      */
/*  Returns TRANSITION_ID_NONE if no match / transition==NULL.    */
/* ============================================================== */
/**
 * @brief  Convert transition info to a unique ID
 * @param  transition  Transition context (may be NULL)
 * @param  table       Call site table (may be NULL)
 * @param  table_size  Number of entries in the table
 * @return Index in the table (TRANSITION_ID_NONE if no match)
 */
static uint16_t Transition_GetId(
    const TransitionContext_Middleware_t *transition,
    const RoleFuncCallSiteEntry_Middleware_t *table,
    uint16_t table_size)
{
    uint16_t i;

    if (transition == NULL || table == NULL) {
        return TRANSITION_ID_NONE;
    }

    for (i = 0; i < table_size; i++) {
        if (table[i].from_state == transition->from_state &&
            table[i].event      == transition->event) {
            return i;
        }
    }
    return TRANSITION_ID_NONE;
}


/* ============================================================== */
/*  User-added area                                               */
/*  Code added here is preserved across regenerations             */
/* ============================================================== */
/* [[STABLE_USER_CODE_TAIL_START]] */
/* Write user-added code here (helper functions, etc.) */
/* [[STABLE_USER_CODE_TAIL_END]] */
