/**
 * @file    statable_types_Middleware.h
 * @brief   Layer-specific type definitions (enum)
 *
 * @note    Code auto-generated by StaTable
 *          - Manual editing is not recommended
 *          - To modify, use StaTable
 *
 * @date    2026-09-20 03:21:38
 */

#ifndef STATABLE_TYPES_H_MIDDLEWARE
#define STATABLE_TYPES_H_MIDDLEWARE

/*==============================================================
 *  Include files
 *==============================================================*/

#include "statable_types_common.h"

/*==============================================================
 *  Type definitions
 *==============================================================*/

/* Middleware layer state definitions */
typedef enum {
    STATE_Middleware_Idle = 0,    /* Idle Type: INITIAL */
    STATE_Middleware_Connecting = 1,    /* Connecting */
    STATE_Middleware_Connected = 2,    /* Connected */
    STATE_Middleware_Error = 3,    /* Error */
    STATE_Middleware_MAX           /* element count (for system use) */
} STATE_Middleware_t;


/* Middleware layer event definitions */
typedef enum {
    EVENT_Middleware_NONE = 0,    /* completion transition */
    EVENT_Middleware_CONNECT = 1,    /* Connect request Title: Connect */
    EVENT_Middleware_CONNECTED = 2,    /* Connected Title: Connected */
    EVENT_Middleware_ERROR = 3,    /* Error Title: Error */
    EVENT_Middleware_RETRY = 4,    /* Retry Title: Retry */
    EVENT_Middleware_MAX           /* element count (for system use) */
} EVENT_Middleware_t;



/* Transition context for Middleware layer */
typedef struct {
    STATE_Middleware_t from_state;   /* source state */
    EVENT_Middleware_t event;        /* event */
} TransitionContext_Middleware_t;

#endif /* STATABLE_TYPES_H_MIDDLEWARE */