/**
 * @file    statable_types_Application.h
 * @brief   Layer-specific type definitions (enum)
 *
 * @note    Code auto-generated by StaTable
 *          - Manual editing is not recommended
 *          - To modify, use StaTable
 *
 * @date    2026-09-19 22:00:34
 */

#ifndef STATABLE_TYPES_H_APPLICATION
#define STATABLE_TYPES_H_APPLICATION

/*==============================================================
 *  Include files
 *==============================================================*/

#include "statable_types_common.h"

/*==============================================================
 *  Type definitions
 *==============================================================*/

/* Application layer state definitions */
typedef enum {
    STATE_Application_Boot = 0,    /* Boot Type: INITIAL */
    STATE_Application_Init = 1,    /* Init */
    STATE_Application_Running = 2,    /* Running */
    STATE_Application_Paused = 3,    /* Paused */
    STATE_Application_Stopped = 4,    /* Stopped Type: FINAL */
    STATE_Application_MAX           /* element count (for system use) */
} STATE_Application_t;


/* Application layer event definitions */
typedef enum {
    EVENT_Application_NONE = 0,    /* completion transition */
    EVENT_Application_BOOT = 1,    /* Boot Title: Boot */
    EVENT_Application_START = 2,    /* Start Title: Start */
    EVENT_Application_PAUSE = 3,    /* Pause Title: Pause */
    EVENT_Application_RESUME = 4,    /* Resume Title: Resume */
    EVENT_Application_STOP = 5,    /* Stop Title: Stop */
    EVENT_Application_MAX           /* element count (for system use) */
} EVENT_Application_t;



/* Transition context for Application layer */
typedef struct {
    STATE_Application_t from_state;   /* source state */
    EVENT_Application_t event;        /* event */
} TransitionContext_Application_t;

#endif /* STATABLE_TYPES_H_APPLICATION */