# codegen/state_actions_generator.py
"""
State actions generation module (v2.7.0)

Generates per-layer Entry / Exit / Do dispatch code:

  - statable_state_actions_<Layer>.h
      void <Layer>_Entry(STATE_<Layer>_t state, SystemContext_t *ctx);
      void <Layer>_Exit (STATE_<Layer>_t state, SystemContext_t *ctx);
      void <Layer>_Do   (STATE_<Layer>_t state, SystemContext_t *ctx);

  - statable_state_actions_<Layer>.c
      - Entry / Exit / Do dispatch tables (ordered init, C89-compatible)
      - Dispatchers
      - Per-state functions with [[STABLE_USER_CODE_..._custom]] markers

Design notes
------------
- Table order MUST match STATE_<Layer>_t enum order.
- Each per-state function contains:
    * GUI-edited actions (regenerated)
    * User custom code (preserved)
- Role function calls receive NULL for the transition pointer
  (state actions are not tied to a specific transition).

Version: 1.0 (2026-09-26 / initial)
"""

import sys
import os
import logging
from string import Template
from typing import Dict, List, Optional

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from statable.model import State, ActionStep
from statable.state_machine import StateMachine

try:
    from .type_mapper import CTypeMapper
    from .naming_convention import CNamingConvention
    from .code_templates import CodeTemplates
except ImportError:
    from type_mapper import CTypeMapper
    from naming_convention import CNamingConvention
    from code_templates import CodeTemplates

logger = logging.getLogger(__name__)


def _extract_rf_name(action) -> str:
    """[v2.7.0] Extract role_function name from ActionStep or str."""
    if action is None:
        return ""
    if isinstance(action, str):
        return action
    return getattr(action, "role_function", "") or ""


class StateActionsGenerator:
    """State actions (Entry / Exit / Do) code generator."""

    HEADER_TEMPLATES = {
        'file_comment': '''/**
 * @file    statable_state_actions_{layer}.h
 * @brief   State actions (Entry / Exit / Do) for {layer} layer
 *
 * @note    Code auto-generated by StaTable
 *          - Manual editing is not recommended
 *          - To modify, use StaTable
 */''',
        'guard_start': '#ifndef STATABLE_STATE_ACTIONS_{LAYER}_H\n'
                       '#define STATABLE_STATE_ACTIONS_{LAYER}_H\n',
        'guard_end': '#endif /* STATABLE_STATE_ACTIONS_{LAYER}_H */',
        'include_common': '#include "statable_types_common.h"',
        'include_layer': '#include "statable_types_{layer}.h"',
        'decl_entry': 'void {layer}_Entry(STATE_{layer}_t state, SystemContext_t *ctx);',
        'decl_exit':  'void {layer}_Exit (STATE_{layer}_t state, SystemContext_t *ctx);',
        'decl_do':    'void {layer}_Do   (STATE_{layer}_t state, SystemContext_t *ctx);',
    }

    SOURCE_TEMPLATES = {
        'file_comment': '''/**
 * @file    statable_state_actions_{layer}.c
 * @brief   State actions (Entry / Exit / Do) for {layer} layer
 *
 * @note    Code auto-generated by StaTable
 *          - Manual editing is not recommended
 *          - To modify, use StaTable
 *          - C89-compatible: no designated initializers used.
 *            Table order MUST match STATE_{layer}_t enum order.
 */''',
        'include_own': '#include "statable_state_actions_{layer}.h"',
        'type_typedef': 'typedef void (*{layer}_StateFunc_t)(SystemContext_t *ctx);',
    }

    def __init__(self):
        self.mapper = CTypeMapper()
        self.naming = CNamingConvention()
        self.templates = CodeTemplates()
        self.layer_name: str = ""

    def set_layer(self, layer_name: str):
        self.layer_name = layer_name

    def _log_debug(self, message, level='debug'):
        log_func = getattr(logger, level, logger.debug)
        log_func(message)

    # ------------------------------------------------------------------
    # Name helpers
    # ------------------------------------------------------------------
    def _state_type(self) -> str:
        return (f"STATE_{self.layer_name}_t"
                if self.layer_name else "STATE_t")

    def _state_max(self) -> str:
        return (f"STATE_{self.layer_name}_MAX"
                if self.layer_name else "STATE_MAX")

    def _state_enum(self, state_name: str) -> str:
        s = self.naming.to_pascal_case(state_name) if state_name else "Unknown"
        return (f"STATE_{self.layer_name}_{s}"
                if self.layer_name else f"STATE_{s}")

    def _func_type(self) -> str:
        return (f"{self.layer_name}_StateFunc_t"
                if self.layer_name else "StateFunc_t")

    def _state_suffix(self, state_name: str) -> str:
        """C-safe suffix for per-state function names."""
        return self.naming.to_pascal_case(state_name) if state_name else "Unknown"

    def _rf_call(self, rf_name: str) -> str:
        """Generate RoleFunc_<NS>_<Name>(NULL, ctx) or fallback."""
        if not rf_name:
            return ""
        if rf_name.startswith("RoleFunc_"):
            full = rf_name
        elif "." in rf_name:
            ns, name = rf_name.split(".", 1)
            full = (f"RoleFunc_{self.naming.to_pascal_case(ns)}_"
                    f"{self.naming.to_pascal_case(name)}")
        elif self.layer_name:
            full = (f"RoleFunc_{self.layer_name}_"
                    f"{self.naming.to_pascal_case(rf_name)}")
        else:
            full = f"RoleFunc_{self.naming.to_pascal_case(rf_name)}"
        return f"(void){full}(NULL, ctx)"

    def _fire_event_call(self, event_name: str) -> str:
        """Generate FIRE_EVENT_<Layer>(<EVENT>) or fallback comment."""
        if not event_name:
            return ""
        # event_name is expected to be "Layer.EVENT" or "EVENT"
        if "." in event_name:
            layer, evt = event_name.split(".", 1)
        else:
            layer, evt = self.layer_name, event_name
        evt_upper = self.naming.to_upper_snake(evt)
        return f"FIRE_EVENT_{layer}({layer.upper()}_{evt_upper})"

    # ------------------------------------------------------------------
    # Per-action code emission
    # ------------------------------------------------------------------
    def _action_line(self, action: ActionStep, indent: str = "    ") -> str:
        """Emit one ActionStep as a C statement (with optional condition)."""
        atype = getattr(action, "action_type", "role") or "role"
        cond = (getattr(action, "condition", "") or "").strip()

        if atype == "fire_event":
            call = self._fire_event_call(
                getattr(action, "event_name", "") or "")
            if not call:
                return ""
        elif atype == "custom":
            # Custom is not emitted from GUI actions
            return ""
        else:
            rf = _extract_rf_name(action)
            call = self._rf_call(rf)
            if not call:
                return ""

        if cond:
            return (f"{indent}if ({cond}) {{\n"
                    f"{indent}    {call};\n"
                    f"{indent}}}\n")
        return f"{indent}{call};\n"

    def _emit_actions(self, actions: List[ActionStep]) -> str:
        """Emit all GUI-edited actions for one kind (Entry / Exit / Do)."""
        if not actions:
            return ""
        parts = ["    /* --- GUI-edited actions (regenerated) --- */\n"]
        for a in actions:
            line = self._action_line(a)
            if line:
                parts.append(line)
        parts.append("    /* --- end GUI-edited actions --- */\n\n")
        return "".join(parts)

    # ------------------------------------------------------------------
    # Per-state function
    # ------------------------------------------------------------------
    def _state_func_name(self, kind: str, state_name: str) -> str:
        """<Layer>_<Kind>_<State>"""
        return (f"{self.layer_name}_{kind}_"
                f"{self._state_suffix(state_name)}")

    def _custom_marker_name(self, kind: str, state_name: str) -> str:
        return (f"{self.layer_name}_{kind}_"
                f"{self._state_suffix(state_name)}_custom")

    def _generate_state_func(self, kind: str, state: State,
                             actions: List[ActionStep]) -> str:
        """Generate one per-state function (Entry / Exit / Do)."""
        func_name = self._state_func_name(kind, state.name)
        marker = self._custom_marker_name(kind, state.name)

        parts = []
        parts.append(f"static void {func_name}(SystemContext_t *ctx)\n")
        parts.append("{\n")
        parts.append(self._emit_actions(actions))
        parts.append(
            f"    /* --- user custom code (preserved) --- */\n")
        parts.append(
            f"    /* [[STABLE_USER_CODE_START:{marker}]] */\n")
        parts.append("    (void)ctx;\n")
        parts.append(
            f"    /* [[STABLE_USER_CODE_END:{marker}]] */\n")
        parts.append("}\n")
        return "".join(parts)

    # ------------------------------------------------------------------
    # Entry / Exit / Do groups
    # ------------------------------------------------------------------
    def _collect_actions_by_kind(self, sm: StateMachine,
                                 kind: str) -> Dict[str, List[ActionStep]]:
        """Return {state_name: [ActionStep, ...]} for the given kind."""
        result: Dict[str, List[ActionStep]] = {}
        for state in sm.states.values():
            if kind == "Entry":
                actions = list(getattr(state, "entry", []) or [])
            elif kind == "Exit":
                actions = list(getattr(state, "exit", []) or [])
            elif kind == "Do":
                actions = list(getattr(state, "do_actions", []) or [])
            else:
                actions = []
            result[state.name] = actions
        return result

    # ------------------------------------------------------------------
    # Forward declarations
    # ------------------------------------------------------------------
    def _generate_forward_decls(self, sm: StateMachine) -> str:
        parts = []
        for kind in ("Entry", "Exit", "Do"):
            parts.append(
                f"/* ---- {kind} forward declarations ---- */\n")
            for state in sm.states.values():
                func_name = self._state_func_name(kind, state.name)
                parts.append(
                    f"static void {func_name}(SystemContext_t *ctx);\n")
            parts.append("\n")
        return "".join(parts)

    # ------------------------------------------------------------------
    # Dispatch table (ordered init, C89)
    # ------------------------------------------------------------------
    def _generate_table(self, kind: str, sm: StateMachine) -> str:
        """Generate one ordered-init dispatch table."""
        layer = self.layer_name or "System"
        func_type = self._func_type()
        state_max = self._state_max()
        table_name = f"g_{layer}_{kind}Table"

        parts = []
        parts.append(
            f"static const {func_type} {table_name}[{state_max}] = {{\n")

        # Ordered by enum definition order.
        # StateMachine.states is a dict (insertion order); we rely on
        # the same iteration order used by enum generation.
        for state in sm.states.values():
            func_name = self._state_func_name(kind, state.name)
            parts.append(
                f"    {func_name},  /* {self._state_enum(state.name)} */\n")
        parts.append("};\n")
        return "".join(parts)

    # ------------------------------------------------------------------
    # Dispatcher
    # ------------------------------------------------------------------
    def _generate_dispatcher(self, kind: str, sm: StateMachine) -> str:
        layer = self.layer_name or "System"
        func_type = self._func_type()
        state_type = self._state_type()
        state_max = self._state_max()
        table_name = f"g_{layer}_{kind}Table"

        parts = []
        parts.append(f"void {layer}_{kind}({state_type} state, "
                     f"SystemContext_t *ctx)\n")
        parts.append("{\n")
        parts.append(f"    if ((unsigned)state < (unsigned){state_max}) {{\n")
        parts.append(f"        {func_type} fn = {table_name}[state];\n")
        parts.append("        if (fn != NULL) {\n")
        parts.append("            fn(ctx);\n")
        parts.append("        }\n")
        parts.append("    }\n")
        parts.append("}\n")
        return "".join(parts)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------
    def generate_header(self, sm: StateMachine) -> str:
        """Generate statable_state_actions_<Layer>.h"""
        layer = self.layer_name or "System"
        T = self.HEADER_TEMPLATES
        guard = T['guard_start'].replace("{LAYER}", layer.upper())

        parts = []
        parts.append(T['file_comment'].format(layer=layer))
        parts.append("\n\n")
        parts.append(guard)
        parts.append("\n")
        parts.append(T['include_common'])
        parts.append("\n")
        parts.append(T['include_layer'].format(layer=layer))
        parts.append("\n\n")
        parts.append(
            "/* Entry / Exit / Do dispatch (state actions) */\n")
        parts.append(T['decl_entry'].format(layer=layer))
        parts.append("\n")
        parts.append(T['decl_exit'].format(layer=layer))
        parts.append("\n")
        parts.append(T['decl_do'].format(layer=layer))
        parts.append("\n\n")
        parts.append(T['guard_end'].replace("{LAYER}", layer.upper()))
        parts.append("\n")
        return "".join(parts)

    def generate_source(self, sm: StateMachine) -> str:
        """Generate statable_state_actions_<Layer>.c"""
        layer = self.layer_name or "System"
        T = self.SOURCE_TEMPLATES

        parts = []
        parts.append(T['file_comment'].format(layer=layer))
        parts.append("\n\n")
        parts.append(T['include_own'].format(layer=layer))
        parts.append("\n\n")
        parts.append(T['type_typedef'].format(layer=layer))
        parts.append("\n\n")

        # Forward declarations
        parts.append(self._generate_forward_decls(sm))
        parts.append("\n")

        # Tables
        for kind in ("Entry", "Exit", "Do"):
            parts.append(
                f"/* ---- {kind} dispatch table ---- */\n")
            parts.append(self._generate_table(kind, sm))
            parts.append("\n")

        # Dispatchers
        for kind in ("Entry", "Exit", "Do"):
            parts.append(
                f"/* ---- {kind} dispatcher ---- */\n")
            parts.append(self._generate_dispatcher(kind, sm))
            parts.append("\n")

        # Per-state functions
        for kind in ("Entry", "Exit", "Do"):
            actions_by_state = self._collect_actions_by_kind(sm, kind)
            parts.append(
                f"/* ---- {kind} functions (user-editable) ---- */\n")
            for state in sm.states.values():
                parts.append(self._generate_state_func(
                    kind, state, actions_by_state.get(state.name, [])))
                parts.append("\n")

        return "".join(parts)