/**
 * @file    statable_role_functions_Application.c
 * @brief   Role function implementations
 *
 * @note    Code auto-generated by StaTable
 *          - Manual editing is not recommended
 *          - To modify, use StaTable
 *
 * @date    2026-09-19 22:08:36
 */

/*==============================================================
 *  Include files
 *==============================================================*/

#include "statable_role_functions_Application.h"

/*==============================================================
 *  Role function implementations
 *==============================================================*/


/* ============================================================== */
/*  Transition ID constant                                        */
/* ============================================================== */
#define TRANSITION_ID_NONE   ((uint16_t)0xFFFF)


/* ============================================================== */
/*  Role function call site table (common struct)                 */
/*  Identify cells by {from_state, event} pair                    */
/* ============================================================== */
typedef struct {
    STATE_Application_t from_state;   /* source state */
    EVENT_Application_t event;        /* event */
} RoleFuncCallSiteEntry_Application_t;


/* Transition_GetId forward declaration (body at end of file) */
static uint16_t Transition_GetId(
    const TransitionContext_Application_t *transition,
    const RoleFuncCallSiteEntry_Application_t *table,
    uint16_t table_size);


/* --- call site table for BootEntry --- */
static const RoleFuncCallSiteEntry_Application_t call_sites_BootEntry[] = {
    { STATE_Application_Boot, EVENT_Application_NONE },
};
#define CALL_SITES_BootEntry_COUNT \
    (sizeof(call_sites_BootEntry) / sizeof(call_sites_BootEntry[0]))


/* --- call site table for BootExit --- */
static const RoleFuncCallSiteEntry_Application_t call_sites_BootExit[] = {
    { STATE_Application_Boot, EVENT_Application_NONE },
};
#define CALL_SITES_BootExit_COUNT \
    (sizeof(call_sites_BootExit) / sizeof(call_sites_BootExit[0]))


/* --- call site table for InitEntry --- */
static const RoleFuncCallSiteEntry_Application_t call_sites_InitEntry[] = {
    { STATE_Application_Init, EVENT_Application_NONE },
};
#define CALL_SITES_InitEntry_COUNT \
    (sizeof(call_sites_InitEntry) / sizeof(call_sites_InitEntry[0]))


/* --- call site table for RunEntry1 --- */
static const RoleFuncCallSiteEntry_Application_t call_sites_RunEntry1[] = {
    { STATE_Application_Running, EVENT_Application_NONE },
};
#define CALL_SITES_RunEntry1_COUNT \
    (sizeof(call_sites_RunEntry1) / sizeof(call_sites_RunEntry1[0]))


/* --- call site table for RunEntry2 --- */
static const RoleFuncCallSiteEntry_Application_t call_sites_RunEntry2[] = {
    { STATE_Application_Running, EVENT_Application_NONE },
};
#define CALL_SITES_RunEntry2_COUNT \
    (sizeof(call_sites_RunEntry2) / sizeof(call_sites_RunEntry2[0]))


/* --- call site table for PauseEntry --- */
static const RoleFuncCallSiteEntry_Application_t call_sites_PauseEntry[] = {
    { STATE_Application_Paused, EVENT_Application_NONE },
};
#define CALL_SITES_PauseEntry_COUNT \
    (sizeof(call_sites_PauseEntry) / sizeof(call_sites_PauseEntry[0]))


/* --- call site table for StopEntry --- */
static const RoleFuncCallSiteEntry_Application_t call_sites_StopEntry[] = {
    { STATE_Application_Stopped, EVENT_Application_NONE },
};
#define CALL_SITES_StopEntry_COUNT \
    (sizeof(call_sites_StopEntry) / sizeof(call_sites_StopEntry[0]))


/* --- call site table for Boot --- */
static const RoleFuncCallSiteEntry_Application_t call_sites_Boot[] = {
    { STATE_Application_Boot, EVENT_Application_BOOT },
};
#define CALL_SITES_Boot_COUNT \
    (sizeof(call_sites_Boot) / sizeof(call_sites_Boot[0]))


/* --- call site table for Start --- */
static const RoleFuncCallSiteEntry_Application_t call_sites_Start[] = {
    { STATE_Application_Init, EVENT_Application_START },
};
#define CALL_SITES_Start_COUNT \
    (sizeof(call_sites_Start) / sizeof(call_sites_Start[0]))


/* --- call site table for Pause --- */
static const RoleFuncCallSiteEntry_Application_t call_sites_Pause[] = {
    { STATE_Application_Running, EVENT_Application_PAUSE },
};
#define CALL_SITES_Pause_COUNT \
    (sizeof(call_sites_Pause) / sizeof(call_sites_Pause[0]))


/* --- call site table for Resume --- */
static const RoleFuncCallSiteEntry_Application_t call_sites_Resume[] = {
    { STATE_Application_Paused, EVENT_Application_RESUME },
};
#define CALL_SITES_Resume_COUNT \
    (sizeof(call_sites_Resume) / sizeof(call_sites_Resume[0]))


/* --- call site table for HandleStop --- */
static const RoleFuncCallSiteEntry_Application_t call_sites_HandleStop[] = {
    { STATE_Application_Running, EVENT_Application_STOP },
};
#define CALL_SITES_HandleStop_COUNT \
    (sizeof(call_sites_HandleStop) / sizeof(call_sites_HandleStop[0]))


/* --- call site table for PreCheck --- */
static const RoleFuncCallSiteEntry_Application_t call_sites_PreCheck[] = {
    { STATE_Application_Boot, EVENT_Application_BOOT },
};
#define CALL_SITES_PreCheck_COUNT \
    (sizeof(call_sites_PreCheck) / sizeof(call_sites_PreCheck[0]))


/* --- call site table for Cleanup --- */
static const RoleFuncCallSiteEntry_Application_t call_sites_Cleanup[] = {
    { STATE_Application_Boot, EVENT_Application_BOOT },
};
#define CALL_SITES_Cleanup_COUNT \
    (sizeof(call_sites_Cleanup) / sizeof(call_sites_Cleanup[0]))


/* --- call site table for Pre --- */
static const RoleFuncCallSiteEntry_Application_t call_sites_Pre[] = {
    { STATE_Application_Init, EVENT_Application_START },
};
#define CALL_SITES_Pre_COUNT \
    (sizeof(call_sites_Pre) / sizeof(call_sites_Pre[0]))


/* --- call site table for Post --- */
static const RoleFuncCallSiteEntry_Application_t call_sites_Post[] = {
    { STATE_Application_Init, EVENT_Application_START },
};
#define CALL_SITES_Post_COUNT \
    (sizeof(call_sites_Post) / sizeof(call_sites_Post[0]))


/**
 * @brief  Role function: Boot entry
 * @note   Boot entry
 *
 * @note   Call sites:
 *         - [state_entry]  STATE_Application_Boot -[EVENT_Application_NONE]-> STATE_Application_Boot
 */
int RoleFunc_App_BootEntry(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Application_t from_state = STATE_Application_MAX;
    EVENT_Application_t event = EVENT_Application_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_BootEntry, (uint16_t)CALL_SITES_BootEntry_COUNT);

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:App_BootEntry]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:App_BootEntry]] */

    return ret;
}

/**
 * @brief  Role function: Boot exit
 * @note   Boot exit
 *
 * @note   Call sites:
 *         - [state_exit]  STATE_Application_Boot -[EVENT_Application_NONE]-> STATE_Application_Boot
 */
int RoleFunc_App_BootExit(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Application_t from_state = STATE_Application_MAX;
    EVENT_Application_t event = EVENT_Application_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_BootExit, (uint16_t)CALL_SITES_BootExit_COUNT);

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:App_BootExit]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:App_BootExit]] */

    return ret;
}

/**
 * @brief  Role function: Init entry
 * @note   Init entry
 *
 * @note   Call sites:
 *         - [state_entry]  STATE_Application_Init -[EVENT_Application_NONE]-> STATE_Application_Init
 */
int RoleFunc_App_InitEntry(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Application_t from_state = STATE_Application_MAX;
    EVENT_Application_t event = EVENT_Application_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_InitEntry, (uint16_t)CALL_SITES_InitEntry_COUNT);

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:App_InitEntry]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:App_InitEntry]] */

    return ret;
}

/**
 * @brief  Role function: Running entry 1
 * @note   Running entry 1
 *
 * @note   Call sites:
 *         - [state_entry]  STATE_Application_Running -[EVENT_Application_NONE]-> STATE_Application_Running
 */
int RoleFunc_App_RunEntry1(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Application_t from_state = STATE_Application_MAX;
    EVENT_Application_t event = EVENT_Application_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_RunEntry1, (uint16_t)CALL_SITES_RunEntry1_COUNT);

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:App_RunEntry1]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:App_RunEntry1]] */

    return ret;
}

/**
 * @brief  Role function: Running entry 2
 * @note   Running entry 2
 *
 * @note   Call sites:
 *         - [state_entry]  STATE_Application_Running -[EVENT_Application_NONE]-> STATE_Application_Running
 */
int RoleFunc_App_RunEntry2(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Application_t from_state = STATE_Application_MAX;
    EVENT_Application_t event = EVENT_Application_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_RunEntry2, (uint16_t)CALL_SITES_RunEntry2_COUNT);

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:App_RunEntry2]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:App_RunEntry2]] */

    return ret;
}

/**
 * @brief  Role function: Paused entry
 * @note   Paused entry
 *
 * @note   Call sites:
 *         - [state_entry]  STATE_Application_Paused -[EVENT_Application_NONE]-> STATE_Application_Paused
 */
int RoleFunc_App_PauseEntry(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Application_t from_state = STATE_Application_MAX;
    EVENT_Application_t event = EVENT_Application_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_PauseEntry, (uint16_t)CALL_SITES_PauseEntry_COUNT);

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:App_PauseEntry]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:App_PauseEntry]] */

    return ret;
}

/**
 * @brief  Role function: Stopped entry
 * @note   Stopped entry
 *
 * @note   Call sites:
 *         - [state_entry]  STATE_Application_Stopped -[EVENT_Application_NONE]-> STATE_Application_Stopped
 */
int RoleFunc_App_StopEntry(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Application_t from_state = STATE_Application_MAX;
    EVENT_Application_t event = EVENT_Application_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_StopEntry, (uint16_t)CALL_SITES_StopEntry_COUNT);

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:App_StopEntry]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:App_StopEntry]] */

    return ret;
}

/**
 * @brief  Role function: App boot
 * @note   App boot
 *
 * @note   Call sites:
 *         - [pre_action]  STATE_Application_Boot -[EVENT_Application_BOOT]-> STATE_Application_Init
 */
int RoleFunc_App_Boot(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Application_t from_state = STATE_Application_MAX;
    EVENT_Application_t event = EVENT_Application_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_Boot, (uint16_t)CALL_SITES_Boot_COUNT);

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:App_Boot]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:App_Boot]] */

    return ret;
}

/**
 * @brief  Role function: App start
 * @note   App start
 *
 * @note   Call sites:
 *         - [pre_action]  STATE_Application_Init -[EVENT_Application_START]-> STATE_Application_Running
 */
int RoleFunc_App_Start(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Application_t from_state = STATE_Application_MAX;
    EVENT_Application_t event = EVENT_Application_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_Start, (uint16_t)CALL_SITES_Start_COUNT);

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:App_Start]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:App_Start]] */

    return ret;
}

/**
 * @brief  Role function: App pause
 * @note   App pause
 *
 * @note   Call sites:
 *         - [pre_action]  STATE_Application_Running -[EVENT_Application_PAUSE]-> STATE_Application_Paused
 */
int RoleFunc_App_Pause(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Application_t from_state = STATE_Application_MAX;
    EVENT_Application_t event = EVENT_Application_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_Pause, (uint16_t)CALL_SITES_Pause_COUNT);

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:App_Pause]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:App_Pause]] */

    return ret;
}

/**
 * @brief  Role function: App resume
 * @note   App resume
 *
 * @note   Call sites:
 *         - [pre_action]  STATE_Application_Paused -[EVENT_Application_RESUME]-> STATE_Application_Running
 */
int RoleFunc_App_Resume(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Application_t from_state = STATE_Application_MAX;
    EVENT_Application_t event = EVENT_Application_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_Resume, (uint16_t)CALL_SITES_Resume_COUNT);

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:App_Resume]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:App_Resume]] */

    return ret;
}

/**
 * @brief  Role function: Handle stop
 * @note   Handle stop
 *
 * @note   Call sites:
 *         - [pre_action]  STATE_Application_Running -[EVENT_Application_STOP]-> STATE_Application_Stopped
 */
int RoleFunc_App_HandleStop(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Application_t from_state = STATE_Application_MAX;
    EVENT_Application_t event = EVENT_Application_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_HandleStop, (uint16_t)CALL_SITES_HandleStop_COUNT);

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:App_HandleStop]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:App_HandleStop]] */

    return ret;
}

/**
 * @brief  Role function: Pre-check
 * @note   Pre-check
 *
 * @note   Call sites:
 *         - [cell_action_before_transitions]  STATE_Application_Boot -[EVENT_Application_BOOT]-> (not set)
 */
int RoleFunc_App_PreCheck(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Application_t from_state = STATE_Application_MAX;
    EVENT_Application_t event = EVENT_Application_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_PreCheck, (uint16_t)CALL_SITES_PreCheck_COUNT);

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:App_PreCheck]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:App_PreCheck]] */

    return ret;
}

/**
 * @brief  Role function: Cleanup
 * @note   Cleanup
 *
 * @note   Call sites:
 *         - [cell_action_after_transitions]  STATE_Application_Boot -[EVENT_Application_BOOT]-> (not set)
 */
int RoleFunc_App_Cleanup(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Application_t from_state = STATE_Application_MAX;
    EVENT_Application_t event = EVENT_Application_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_Cleanup, (uint16_t)CALL_SITES_Cleanup_COUNT);

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:App_Cleanup]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:App_Cleanup]] */

    return ret;
}

/**
 * @brief  Role function: Pre (before transitions)
 * @note   Runs before evaluating transitions
 *
 * @note   Call sites:
 *         - [cell_action_before_transitions]  STATE_Application_Init -[EVENT_Application_START]-> (not set)
 */
int RoleFunc_App_Pre(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Application_t from_state = STATE_Application_MAX;
    EVENT_Application_t event = EVENT_Application_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_Pre, (uint16_t)CALL_SITES_Pre_COUNT);

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:App_Pre]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:App_Pre]] */

    return ret;
}

/**
 * @brief  Role function: Post (after transitions)
 * @note   Runs after evaluating transitions
 *
 * @note   Call sites:
 *         - [cell_action_after_transitions]  STATE_Application_Init -[EVENT_Application_START]-> (not set)
 */
int RoleFunc_App_Post(
    const TransitionContext_Application_t *transition,
    SystemContext_t *ctx
)
{
    /* ===== transition NULL guard (supports ISR calls) ===== */
    STATE_Application_t from_state = STATE_Application_MAX;
    EVENT_Application_t event = EVENT_Application_NONE;
    if (transition != NULL) {
        from_state = transition->from_state;
        event = transition->event;
    }
    (void)from_state;   /* suppress unused warning */
    (void)event;   /* suppress unused warning */

    /* ===== transition ID (index within call_sites) ===== */
    const uint16_t transition_id = Transition_GetId(
        transition, call_sites_Post, (uint16_t)CALL_SITES_Post_COUNT);

    /* ===== local pointer to ctx->data ===== */
    uint32_t *const counter = &ctx->data.counter;  /* General counter */
    uint8_t *const error_code = &ctx->data.error_code;  /* Error code */
    uint8_t *const retry_count = &ctx->data.retry_count;  /* Retry counter */
    bool *const running = &ctx->data.running;  /* Running flag */
    volatile uint32_t *const g_system_tick = &ctx->data.g_system_tick;  /* Timer base [1ms] */
    uint8_t *const g_tick_10ms = &ctx->data.g_tick_10ms;  /* Derived timer [10ms] */

    /* ===== return value ===== */
    int ret = 0;   /* can be modified in user code */

    /* TODO: implement the code here */

    /* [[STABLE_USER_CODE_START:App_Post]] */
    /* Write user implementation code here */
    /* [[STABLE_USER_CODE_END:App_Post]] */

    return ret;
}



/* ============================================================== */
/*  Transition ID conversion (end of file)                        */
/*  Linearly scans the per-function call_sites table and          */
/*  returns the index of the matching entry.                      */
/*  Returns TRANSITION_ID_NONE if no match / transition==NULL.    */
/* ============================================================== */
/**
 * @brief  Convert transition info to a unique ID
 * @param  transition  Transition context (may be NULL)
 * @param  table       Call site table (may be NULL)
 * @param  table_size  Number of entries in the table
 * @return Index in the table (TRANSITION_ID_NONE if no match)
 */
static uint16_t Transition_GetId(
    const TransitionContext_Application_t *transition,
    const RoleFuncCallSiteEntry_Application_t *table,
    uint16_t table_size)
{
    uint16_t i;

    if (transition == NULL || table == NULL) {
        return TRANSITION_ID_NONE;
    }

    for (i = 0; i < table_size; i++) {
        if (table[i].from_state == transition->from_state &&
            table[i].event      == transition->event) {
            return i;
        }
    }
    return TRANSITION_ID_NONE;
}


/* ============================================================== */
/*  User-added area                                               */
/*  Code added here is preserved across regenerations             */
/* ============================================================== */
/* [[STABLE_USER_CODE_TAIL_START]] */
/* Write user-added code here (helper functions, etc.) */
/* [[STABLE_USER_CODE_TAIL_END]] */
