#!/usr/bin/env python3
"""Apply translation batches to translations.json."""
import argparse
import json
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
BATCHES = {}

BATCHES["batch1"] = {
    "s0001": " description",
    "s0002": " comment",
    "s0003": " * @brief  Role function: $title\\n",
    "s0004": " struct body",
    "s0005": "Completion transition",
    "s0006": " * @param  transition  Transition context (may be NULL: when called from ISR)\\n",
    "s0007": "    $event_type event;        /* Triggering event */\\n",
    "s0008": "    $state_type from_state;   /* Source state */\\n",
    "s0009": " * @param  ctx         System context pointer\\n",
    "s0010": " * @return 0: success, non-zero: error (can also be used for conditions)\\n",
    "s0011": " * @param  ctx  System context pointer",
    "s0012": " * @return success: true, failure: false",
    "s0013": " * @param  queue  Queue",
    "s0014": " ===== Public methods =====",
    "s0015": " --- Section comments ---",
    "s0016": " Group comments",
    "s0017": " Step execution dictionary",
    "s0018": " Constructor",
    "s0019": " Public API",
    "s0020": "Event definitions",
    "s0021": " Helpers",
    "s0022": "\\n        Generate pending event control macros\\n\\n        Example:\\n            /* ============================================================== */\\n            /*  Pending event control                                         */\\n            /* ============================================================== */\\n\\n            /* Event fire macro */\\n            /* Used in role functions: FIRE_EVENT(ctx, EVENT_XXX_YYY); */\\n            #define FIRE_EVENT(ctx, evt)  do { \\\\\\n                (ctx)->pending_event = (uint16_t)(evt); \\\\\\n                (ctx)->pending_event_valid = true; \\\\\\n            } while(0)\\n\\n            /* Upper limit of consecutive pending event processing */\\n            /* For infinite loop prevention. Overridable via -D at build time */\\n            #ifndef MAX_CONSECUTIVE_PENDING_EVENTS\\n            #define MAX_CONSECUTIVE_PENDING_EVENTS 16\\n            #endif\\n        ",
    "s0023": "\\nC struct code generation module (multi-layer state machine support)\\n\\nGenerated structs:\\n  1. custom_type              : User-defined types (unchanged)\\n  2. system_data              : Global variables (unchanged)\\n  3. event_flags              : Event flags (unchanged)\\n  4. system_context           : SystemContext_t (pending_event added)\\n  5. transition_context       : Common TransitionContext_t (new, base type)\\n  6. layer_transition_context : TransitionContext_<Layer>_t (new, per-layer)\\n  7. pending_event_macros     : FIRE_EVENT / MAX_CONSECUTIVE_PENDING_EVENTS macros (new)\\n\\nDesign policy:\\n  - Templates are data-driven via string.Template\\n  - pending_event is uint16_t (holds layer enum values generically)\\n  - Provides both per-layer TransitionContext_<Layer>_t and common base TransitionContext_t\\n",
    "s0024": "\\nVariable/flag generation module (multi-layer state machine support)\\n\\n[v1.5 fix]\\n  - _generate_normal_init initializes custom struct variables with memset\\n    (up to v1.4, `ctx->data.system_status = 0;` caused a compile error)\\n\\n[v1.6 section 9.8 #92 fix]\\n  - Fixed access macro field name\\n    DATA_COUNTER(ctx) ((ctx)->data.COUNTER)  -> bug\\n    DATA_COUNTER(ctx) ((ctx)->data.counter)  -> fixed\\n    Macro name is uppercase (to_upper_snake), field name uses sanitize_identifier\\n\\n[v2.0 fix]\\n  - Correctly recognize standard types with `_t` suffix (uint32_t / uint8_t, etc.)\\n    Old: DEFAULT_INIT_VALUES had 'uint32' but not 'uint32_t'\\n         -> standard type was treated as custom type and generated redundant memset\\n    New: added _t-suffixed types to DEFAULT_INIT_VALUES\\n         _normalize_type_for_init strips volatile / const qualifiers before lookup\\n",
    "s0025": "\\nRole function generation module (multi-layer state machine + ISR support)\\n\\nVersion: 3.0 (2026-09-13 / Stage 4: transition-side Namespace.Name support)\\n  - _normalize_func_ref preserves qualified_name\\n  - _extract_func_names_from_condition detects 'Driver.Init' form\\n  - _get_call_sites_for_func supports both qualified / bare lookups\\n\\n[v1.5 additions]\\n  - Added _VALID_C_IDENTIFIER guard to _normalize_func_ref\\n    -> rejects C operator contaminated references like 'retry_count++'\\n  - Added undefined reference warning log to generate_all_implementations\\n\\n[v1.6 additions]\\n  - Added _should_emit_implementation (layer filter / plan A)\\n  - generate_all_implementations now filters output so that only functions\\n    of the current layer or those with callers are emitted (reduces empty stubs)\\n",
    "s0026": "\\n        Return all generated artifacts as a dictionary\\n\\n        Returns:\\n            {\\n                'custom_types': str,\\n                'system_data': str,\\n                'event_flags': str,\\n                'system_context': str,\\n                'common_transition_context': str,\\n                'pending_event_macros': str,\\n            }\\n        ",
    "s0027": "\\n        Generate SystemContext_t (pending_event / pending_event_valid added)\\n\\n        Example:\\n            /* System-wide struct */\\n            typedef struct {\\n                SystemData_t data;\\n                EventFlags_t flags;\\n                uint16_t pending_event;\\n                bool pending_event_valid;\\n            } SystemContext_t;\\n        ",
    "s0028": "\\nInterrupt handler ISR generation module (H3: ISR context support)\\n\\nFeatures:\\n  1. Automatic ctx pointer insertion\\n  2. Action Namespace.Name -> RoleFunc_<NS>_<Name>(NULL, ctx) conversion\\n  3. Legacy identifier(args) conversion\\n  4. User marker [[STABLE_USER_CODE_START:<Marker>]]\\n  5. Automatic extraction of used_role_functions / used_variables\\n  6. Entry / exit logging\\n",
    "s0029": "\\n        Generate per-layer TransitionContext_<Layer>_t\\n",
    "s0030": "\\n        Generate common base type TransitionContext_t\\n",
    "s0031": "\\n        Convert action string to C code\\n",
    "s0032": "\\n        [v1.5 fix] Custom types use memset\\n        [v2.0 fix] Recognize _t suffix types\\n",
    "s0033": "\\n        Generate flag access macros\\n",
    "s0034": "\\n        Normalize type name for DEFAULT_INIT_VALUES lookup.\\n",
    "s0035": "\\n        Decide whether to emit implementation in this layer's file (v1.6 plan A)\\n",
    "s0036": "\\n        Extract used role functions and used variables from handler\\n",
    "s0037": "\\n        Generate implementations for this layer's file.\\n",
    "s0038": "\\n        Generate data access macros\\n",
    "s0039": "\\n        Generate event enum (including NONE = 0)\\n",
    "s0040": "\\n        Generate timer variable struct\\n",
    "s0041": "\\nTimer variable generation module (fully data-driven)\\n",
    "s0042": "\\n        Generate all structs at once\\n",
    "s0043": "\\n        Generate ISR\\n",
    "s0044": "\\nC enum code generation module (multi-layer state machine support)\\n",
    "s0045": "/*  Transition ID constants                                     */\\n",
    "s0046": "/*  returned.                                                   */\\n",
    "s0047": " 7. pending_event macros (FIRE_EVENT / MAX_CONSECUTIVE_PENDING_EVENTS)",
    "s0048": "/*  Identifies cell by {from_state, event} pair                 */\\n",
    "s0049": "/*  User extension area                                         */\\n",
    "s0050": "/*  Pending event control                                       */\\n",
    "s0051": "/*  If no match / transition==NULL, returns TRANSITION_ID_NONE   */\\n",
    "s0052": "/*  Transition ID conversion (end of file)                      */\\n",
    "s0053": "    /* ===== transition ID (index in call_sites) ===== */\\n",
    "s0054": "    /* ===== transition NULL guard (for ISR calls) ===== */\\n",
    "s0055": "    uint16_t event;        /* Triggering event */\\n",
    "s0056": "Recompute handler's used_role_functions / used_variables and write back",
    "s0057": "    uint16_t from_state;   /* Source state */\\n",
    "s0058": "    bool pending_event_valid;       /* Pending event valid flag */\\n",
    "s0059": "    uint16_t pending_event;         /* Pending event */\\n",
    "s0060": "/*  Linear search the call_sites table */\\n",
    "s0061": " * @return Index in table (TRANSITION_ID_NONE if no match)\\n",
    "s0062": "/*  Return index of matched entry.                              */\\n",
    "s0063": "/*  Role function call-site table (common struct)               */\\n",
    "s0064": "/* Use in role functions: FIRE_EVENT(ctx, EVENT_XXX_YYY); */\\n",
    "s0065": " v1.6 section 9.8 #92: macro generation",
    "s0066": "/*  Code added here is preserved on regeneration                */\\n",
    "s0067": "/* Same layout as per-layer TransitionContext_<Layer>_t */\\n",
    "s0068": "    $event_flags_type flags;    /* Event flags */\\n",
    "s0069": "    $system_data_type data;     /* Global variables */\\n",
    "s0070": "Set layer name (legacy identifier(args) form)",
    "s0071": "    /* ===== Local pointer to ctx->data ===== */\\n",
    "s0072": " --- MAX_CONSECUTIVE_PENDING_EVENTS macro ---",
    "s0073": " [Data table 4] Per-layer TransitionContext_<Layer>_t",
    "s0074": " * @param  table       Call-site table (may be NULL)\\n",
    "s0075": "    (void)$member_name;   /* Suppress unused warning */\\n",
    "s0076": "    (void)ctx;         /* Suppress unused argument warning */\\n",
    "s0077": "    int ret = 0;   /* User code may overwrite */\\n",
    "s0078": " * @param  transition  Transition context (may be NULL)\\n",
    "s0079": " [Data table 1] Common struct templates",
    "s0080": " [Data table 3] Common TransitionContext_t template",
    "s0081": "/* Transition_GetId forward declaration */\\n",
    "s0082": "     Generated code must treat 'uint32_t' as standard",
    "s0083": " * @brief  Convert transition info to unique ID\\n",
    "s0084": " 4. SystemContext_t (pending_event added)",
    "s0085": "\\n/* --- Call-site table for $func_name --- */\\n",
    "s0086": "    $name           /* Element count */\\n",
    "s0087": " 5. Bare identifier (PascalCase only)",
    "s0088": "\\nOSAL code generation module\\n",
    "s0089": "   Consistent with type_mapper.py's TYPE_MAPPING:",
    "s0090": " Sign qualifier is kept,",
    "s0091": "     'uint32' -> 'uint32_t' conversion, so",
    "s0092": "    /* ===== Context reference (auto-generated) ===== */",
    "s0093": " 6. Per-layer TransitionContext_<Layer>_t",
    "s0094": "One role-function call site",
    "s0095": " v1.5 added: detect undefined references",
    "s0096": "/* Generic transition context */\\n",
    "s0097": "    /* ===== Actions (auto-generated) ===== */",
    "s0098": " * @param  table_size  Number of elements\\n",
    "s0099": "/* Add user code here */\\n",
    "s0100": "Set layer name (per-layer TransitionContext)",
    "s0101": " 'unsigned' alone is kept as-is",
    "s0102": " * @param  ctx  System context pointer\\n",
    "s0103": " --- struct end ( }} -> } fixed) ---",
    "s0104": " v1.6 section 9.8 #92: separate macro name and field name",
    "s0105": " Names starting with RoleFunc_ / ISR_ kept as-is",
    "s0106": "/* For infinite loop prevention. */\\n",
    "s0107": "Convert condition-attached action to C code",
    "s0108": " 5. Common TransitionContext_t (base type)",
    "s0109": " Standard types: = 0 / = false",
    "s0110": "    /* ===== User extension area ===== */",
    "s0111": "Role function generation class",
    "s0112": "\\nEvent queue code generation module\\n",
    "s0113": " --- 1. Namespace.Name form ---",
    "s0114": " ---  pending_event members ---",
    "s0115": " v1.6 plan A: layer filter decision",
    "s0116": " v2.0 fix: add standard types with _t suffix",
    "s0117": " [Table 2] Implementation template",
    "s0118": " [Table 3] TRANSITION_ID_NONE constant",
    "s0119": " *\\n * @note   Callers: (none)\\n",
    "s0120": " [Table 6] call_sites table",
    "s0121": "Interrupt handler ISR generation class",
    "s0122": "    /* ===== Return value ===== */\\n",
    "s0123": "    /* Write user implementation code here */\\n",
    "s0124": " * @param  event  Dequeued event",
    "s0125": " C reserved words excluded",
    "s0126": " v1.5: normalization of reference strings",
    "s0127": " v1.6 plan A: layer filter",
    "s0128": "/* Used when managing flags bitwise */\\n",
    "s0129": "    /* ===== Entry log ===== */",
    "s0130": "    /* ===== Exit log ===== */",
    "s0131": " * @brief  System context initialization\\n",
    "s0132": " --- data / flags members ---",
    "s0133": " 4. Entire string is bare identifier",
    "s0134": " v2.0: custom type decision",
    "s0135": "    /* Add user code here */",
    "s0136": " 3. function_name(...) form",
    "s0137": "/* Manages timer variables */",
    "s0138": "C enum code generation class",
    "s0139": "C struct code generation class",
    "s0140": " 1. User-defined types (custom_type)",
    "s0141": " 2. Handle RoleFunc_ prefix",
    "s0142": " ===== Enqueue generation step =====",
    "s0143": " [Table 4] Common struct for call-site table",
    "s0144": " [Table 5] Transition_GetId",
    "s0145": "/* $layer layer transition context */\\n",
    "s0146": "Event queue code generation class",
    "s0147": "Variable/flag generation class",
    "s0148": "    /* Event flag initialization */\\n",
    "s0149": "    /* Global variable initialization */\\n",
    "s0150": " *\\n * @note   Callers:\\n",
    "s0151": " --- FIRE_EVENT macro ---",
    "s0152": " [Table 8] User extension area at end of file",
    "s0153": " [Data table 6] Member generation template",
    "s0154": "/* Event flag bit mask definitions */\\n",
    "s0155": "OSAL code generation class",
    "s0156": "    /* Pending event initialization */\\n",
    "s0157": " * @param  event  Event",
    "s0158": " ===== Struct generation step =====",
    "s0159": " [v1.5 added] C identifier validation regex",
    "s0160": " [Data table 2] Common macro template",
    "s0161": " 2. Namespace.Name form",
    "s0162": " ===== Step execution function =====",
    "s0163": " Convert to RoleFunc name",
    "s0164": " v1.5 fix: exclude empty-name events",
    "s0165": "/* Upper limit of consecutive pending events */\\n",
    "s0166": "    /* NULL check */\\n",
    "s0167": "    /* (action undefined) */",
    "s0168": " --- 2. Function call form ---",
    "s0169": " 3.  v1.5 added: identifier validation",
    "s0170": " Type qualifiers",
    "s0171": "Unified management of globals and event flags",
    "s0172": " * @brief  Timer variable initialization",
    "s0173": " * @note   Used role functions:",
    "s0174": " 1. RoleFunc_XXX form",
    "s0175": " 2. Function called from layer's transitions",
    "s0176": " [Data table 5] Member kind detection",
    "s0177": " Name generation (namespace support)",
    "s0178": "Timer variable generation class",
    "s0179": " * @brief  Timer update processing",
    "s0180": " --- struct begin ---",
    "s0181": " ---- boolean / char ----",
    "s0182": " v2.0 added: type name normalization",
    "s0183": " ---- unsigned integers ----",
    "s0184": " ---- signed integers ----",
    "s0185": " ===== Name generation =====",
    "s0186": " [Table 1] Declaration template",
    "s0187": " [Table 7] Caller comment",
    "s0188": "/* Event fire macro */\\n",
    "s0189": " --- 3. Otherwise ---",
    "s0190": "Log display name",
    "s0191": " ---- floating point ----",
    "s0192": "/* Timer variable struct */",
    "s0193": "System context pointer",
    "s0194": "Backward compatibility: single struct",
    "s0195": " C keywords kept as-is",
    "s0196": "  }} -> } fixed",
    "s0197": "Generate all event queue code",
    "s0198": "Generate all event queue structs",
    "s0199": " Normalize trailing semicolon",
    "s0200": "Event queue struct generation",
}

BATCHES["batch2"] = {
    "s0201": "Generate all event queue code",
    "s0202": "Generate all event queue functions",
    "s0203": "Get available OS types",
    "s0204": " 1. Strip argument part",
    "s0205": " Pass after excluding empty names",
    "s0206": " Function extraction from condition expression",
    "s0207": " struct end",
    "s0208": " Action parsing",
    "s0209": " Source generation step",
    "s0210": " Header generation step",
    "s0211": " Strip leading qualifiers",
    "s0212": " Call-site collection",
    "s0213": "Generate all OSAL code",
    "s0214": " 1. Functions of this layer",
    "s0215": " Used symbol extraction",
    "s0216": " Initialization code generation",
    "s0217": " Backward-compatible API",
    "s0218": " Generation step definition",
    "s0219": "OSAL source generation",
    "s0220": "OSAL header generation",
    "s0221": "Event flag definition",
    "s0222": "Enqueue function generation",
    "s0223": "System-wide struct",
    "s0224": " 8. Batch generation",
    "s0225": " Generation methods",
    "s0226": "Generate one member",
    "s0227": "Dequeue function generation",
    "s0228": "Generate all ISRs",
    "s0229": "Transition context",
    "s0230": " Step execution",
    "s0231": " Generation step",
    "s0232": " Class constants",
    "s0233": " Flag body",
    "s0234": " Description / unit",
    "s0235": " Name generation",
    "s0236": " Variable body",
    "s0237": " Deduplication",
    "s0238": "(not set)",
    "s0239": "State definition",
    "s0240": "Warning",
    "s0241": "Description",
    "s0242": "Delete",
    "s0243": "(unnamed)",
    "s0244": "Title",
    "s0245": "Add",
    "s0246": "Type",
    "s0247": "(untitled transition)",
    "s0248": "Close",
    "s0249": "Title *",
    "s0250": "Event name",
    "s0251": "Label shown in the list (auto-set if empty)",
    "s0252": "Group",
    "s0253": "Error",
    "s0254": "Confirm",
    "s0255": "(completion)",
    "s0256": "Completion",
    "s0257": "Select output directory",
    "s0258": " v1.6 added",
    "s0259": " Layer settings",
    "s0260": "(internal)",
    "s0261": "Bit width",
    "s0262": "Yes",
    "s0263": "Unit",
    "s0264": "Info",
    "s0265": "OK button: auto-set provisional title if title is empty",
    "s0266": "Search (prefix match):",
    "s0267": "Apply selected changes",
    "s0268": "Build UI",
    "s0269": "Cancel",
    "s0270": "Interrupt name",
    "s0271": " Buttons",
    "s0272": "Flag name",
    "s0273": "Max value",
    "s0274": "Min value",
    "s0275": "Delete row",
    "s0276": "Add row",
    "s0277": "Name",
    "s0278": " Title input field (required / provisional title auto-set)",
    "s0279": "NonRTOS (bare metal)",
    "s0280": "switch-case style",
    "s0281": "Please enter a type name.",
    "s0282": " Super include",
    "s0283": "Double-click to edit",
    "s0284": " Tab widget",
    "s0285": " External include",
    "s0286": "Event queue definition",
    "s0287": " Folder structure",
    "s0288": "Edit role function",
    "s0289": " OS type",
    "s0290": " Path settings",
    "s0291": " Naming convention",
    "s0292": "Role function",
    "s0293": "Add...",
    "s0294": "Delivery type",
    "s0295": "Return type",
    "s0296": " Search",
    "s0297": "Initial value",
    "s0298": "Variable name",
    "s0299": "Target",
    "s0300": "Function name",
    "s0301": "None",
    "s0302": "Move up",
    "s0303": "Move down",
    "s0304": "Target",
    "s0305": "Insert",
    "s0306": "Edit",
    "s0307": "Array",
    "s0308": "1. Click \\\"Copy\\\" button to copy the prompt to the clipboard\\n",
    "s0309": "name can be either qualified_name or a bare name",
    "s0310": "\\nValidation / AI integration dialog\\nPySide6 compatible\\n",
    "s0311": "Prompt copied to clipboard.\\n",
    "s0312": "4. Paste the answer in the \\\"AI answer intake\\\" tab",
    "s0313": "Please paste into ChatGPT or similar and ask.",
    "s0314": " ===== AI prompt tab =====",
    "s0315": "2. Paste into ChatGPT or similar and ask\\n",
    "s0316": "Failed to copy to clipboard.",
    "s0317": " ===== AI answer tab =====",
    "s0318": " ===== Change list tab =====",
    "s0319": " ===== Validation result tab =====",
    "s0320": "Please set the output directory.",
    "s0321": " Namespace (e.g., \\\"Driver\\\")",
    "s0322": "Paste the AI answer here",
    "s0323": "Paste AI answer from clipboard",
    "s0324": "Global variables shared across the system",
    "s0325": "Handler when the title column is edited directly",
    "s0326": "Event flags managed as bit fields",
    "s0327": "Perform AI diagnosis with the following steps:\\n",
    "s0328": "Helper function to show the validation dialog",
    "s0329": "Copy prompt to clipboard",
    "s0330": "The following warnings occurred:\\n\\n",
    "s0331": "Conditional actions inside an interrupt handler",
    "s0332": "No changes selected for applying.",
    "s0333": "A role function with the same name already exists.",
    "s0334": "Set up the AI prompt tab",
    "s0335": "Table that reliably captures double-click events",
    "s0336": " Bare name (e.g., \\\"Init\\\")",
    "s0337": "AI answer is empty.",
    "s0338": "Please enter an event name.",
    "s0339": "Please enter an interrupt name.",
    "s0340": "Please enter a base variable name.",
    "s0341": "3. Copy the AI answer\\n",
    "s0342": "Please enter a queue name.",
    "s0343": "Please enter a member name.",
    "s0344": "Please enter a placeholder name.",
    "s0345": "Parse the answer and generate a change list",
    "s0346": " Collect all tabs as layers",
    "s0347": " Switch the tab to the change list",
    "s0348": "Set up the AI answer tab",
    "s0349": "Paste from clipboard",
    "s0350": "Pre-generation validation / AI diagnosis",
    "s0351": "Please enter a period name.",
    "s0352": "Set up the change list tab",
    "s0353": "Set up the validation result tab",
    "s0354": "There is no state transition tab.",
    "s0355": "Clipboard is empty.",
    "s0356": "Validation / AI integration dialog",
    "s0357": " Prompt preview",
    "s0358": " Severity-based coloring",
    "s0359": "Device resource placeholder definition",
    "s0360": "3) AI answer intake",
    "s0361": "Edit state transition event",
    "s0362": "2) AI prompt",
    "s0363": "4) Change list / apply",
    "s0364": "Timer tick variable definition",
    "s0365": "Copy prompt",
    "s0366": "Derived timer variable definition",
    "s0367": " Event flags",
    "s0368": " Global variables",
    "s0369": " Summary label",
    "s0370": " Project name",
    "s0371": " Prompt generation",
    "s0372": " Problem list update",
    "s0373": " Show change list",
    "s0374": " Paste button",
    "s0375": "else target:",
    "s0376": "Event delivery settings",
    "s0377": "Table-driven style",
    "s0378": "Edit interrupt handler",
    "s0379": "Get current settings",
    "s0380": " \\\"+\\\" button",
    "s0381": " Copy button",
    "s0382": " Summary update",
    "s0383": " Pending event",
    "s0384": " Re-validate button",
    "s0385": " Close button",
    "s0386": "Parse AI answer",
    "s0387": "Event flags",
    "s0388": "Global variables",
    "s0389": "Code generation settings",
    "s0390": "Timer interrupt",
    "s0391": "Timer base variable",
    "s0392": "Register in bulk...",
    "s0393": "Use array",
    "s0394": " Apply button",
    "s0395": " Problem list",
    "s0396": " Parse button",
    "s0397": " Description label",
    "s0398": " Duplicates ignored",
    "s0399": "1) Validation result",
    "s0400": "Event kind",
}

BATCHES["batch3"] = {
    "s0401": "Role function:",
    "s0402": "Condition: none",
    "s0403": "State transition condition",
    "s0404": "Warnings during generation",
    "s0405": "Related events",
    "s0406": " Answer input",
    "s0407": " Change list",
    "s0408": " Unset placeholder",
    "s0409": "OS type:",
    "s0410": "-> (not set)",
    "s0411": "Action",
    "s0412": "Copy complete",
    "s0413": "Code generation",
    "s0414": "Parameter",
    "s0415": "Message",
    "s0416": "Literalize",
    "s0417": "Layer settings",
    "s0418": "Browse...",
    "s0419": "Base variable name",
    "s0420": "Run validation",
    "s0421": "Array size",
    "s0422": " Re-validate",
    "s0423": " Close",
    "s0424": "Category",
    "s0425": "Queue name",
    "s0426": "Flat",
    "s0427": "Member name",
    "s0428": "Placeholder name",
    "s0429": "Save complete",
    "s0430": "Suggested fix",
    "s0431": "Output directory:",
    "s0432": "Output settings",
    "s0433": "Interrupt protection",
    "s0434": "Apply complete",
    "s0435": "Namespace",
    "s0436": "Arg 1 name",
    "s0437": "Arg 1 type",
    "s0438": "Arg 2 name",
    "s0439": "Arg 2 type",
    "s0440": "Condition:",
    "s0441": "Parse complete",
    "s0442": "Target:",
    "s0443": "Function name:",
    "s0444": " Log",
    "s0445": " Output",
    "s0446": "Size",
    "s0447": "Timer",
    "s0448": "Priority",
    "s0449": "Re-validate",
    "s0450": "Period name",
    "s0451": "Per layer",
    "s0452": "Source",
    "s0453": "Element type",
    "s0454": "Description:",
    "s0455": "Severity",
    "s0456": "Save",
    "s0457": "Multiplier",
    "s0458": "Type name",
    "s0459": "Enabled",
    "s0460": "Reason",
    "s0461": "Selection",
    "s0462": "\\nCode display widget (read-only, ActionDraft support)\\n",
    "s0463": "\\n         v1.5 change: construct RoleFunction with kwargs\\n",
    "s0464": "\\n        Convert reference string to RoleFunc_<Namespace>_<PascalName>\\n",
    "s0465": "\\n    Handler that collects logs at WARNING level or higher\\n",
    "s0466": "\\nCanvas widget (plan C: ordered-list support)\\n",
    "s0467": "\\n         v1.5 change: added namespace column (index 2)\\n",
    "s0468": "\\nCollapsible palette by category\\n",
    "s0469": "\\n        Role function edit request\\n",
    "s0470": "\\n        Infer layer name from ActionDraft\\n",
    "s0471": "\\n        Generate a unique name\\n",
    "s0472": "\\n        Transition -> ActionDraft conversion\\n",
    "s0473": "\\n        Open the transition edit dialog\\n",
    "s0474": "\\nAction edit draft model (node position saving support)\\n",
    "s0475": "\\n        [v1.5 change] Set namespace and all args as kwargs\\n",
    "s0476": "Store application settings in a JSON file\\n",
    "s0477": "\\n        Rebuild role function / transition condition list\\n",
    "s0478": "\\n        Insert a role function into the action field\\n",
    "s0479": "\\n    Mermaid diagram preview widget\\n",
    "s0480": "\\nStaTable main window\\n",
    "s0481": "\\n        Find the FlowNodeItem at scene coordinates\\n",
    "s0482": "Shared role function definition\\n",
    "s0483": "\\nStaTable GUI layer\\n",
    "s0484": "\\n    Convert a value to a list if it isn't one.\\n",
    "s0485": "StaTable preference definitions\\n",
    "s0486": "\\nCode generation settings dialog\\n",
    "s0487": "   On the caller side, use `from statable_gui.main_window import MainWindow` to",
    "s0488": " v1.6: get SM's layer_name",
    "s0489": "Dialog to configure event delivery type",
    "s0490": "   From Stage 1/4, role functions handled by qualified_name",
    "s0491": "Transition condition node\\n- Drop a role function on top",
    "s0492": " Stage 3: auto-extract used_role_functions",
    "s0493": "   - If empty, fallback to most frequent namespace",
    "s0494": "Management class for global variables, event flags, interrupts",
    "s0495": " v1.6 added: layer name",
    "s0496": "          4=return type, 5=arg1 type, 6=arg1 name, 7=arg2 type, 8=arg2 name",
    "s0497": "   Loading before creating PySide6 QApplication causes errors",
    "s0498": "\\nTransition condition builder dialog\\n",
    "s0499": "   - When STATABLE_DISABLE_MERMAID=1: do not import",
    "s0500": " 1. If ActionDraft has layer_name attribute, use it",
    "s0501": " transition or pre_action -> added to pre_actions",
    "s0502": " Construct with all kwargs",
    "s0503": "Management dialog for interrupt handlers, device resources",
    "s0504": "   - Pass sm.layer_name from generators",
    "s0505": "   MainWindow / StateMachineTab not re-exported.",
    "s0506": " v1.6: get SM's layer_name (fallback)",
    "s0507": " Adding an entry here enables attribute access.",
    "s0508": "If DIRECT event notified from ISR, auto-converted to DOUBLE.\\n",
    "s0509": "Enter title of this interrupt handler.",
    "s0510": "Data model for globals, event flags, interrupts, resources",
    "s0511": "   Even if <SharedLibraries> is empty, present candidates",
    "s0512": " Debug log: shared library content at init",
    "s0513": "Specify a generated header such as Renesas Smart Configurator.\\n",
    "s0514": "Enter title of this role function.",
    "s0515": "Save all tabs, global definitions, shared libraries\\n",
    "s0516": "     -> Qt WebEngine runtime not initialized",
    "s0517": "   Also pass namespace (v1.4 #69 / v1.5 #86)",
    "s0518": " else or else_action -> added to else_actions",
    "s0519": " Shared library (integrated into statable_gui/libcntrl)",
    "s0520": "Dialog to batch-edit multiple transitions in one cell",
    "s0521": "Transition -> FlowItem (type=transition) conversion",
    "s0522": " Auto-complete 2: register transition conditions",
    "s0523": " Target state choices",
    "s0524": "Enter title of this item.",
    "s0525": "Dialog to edit transition action",
    "s0526": "\\nNode edit dialog\\n",
    "s0527": "Nodes cannot be moved inside canvas.\\nReorder using ordered list.",
    "s0528": "    (Allow selecting SM's local functions when library empty)",
    "s0529": " A valid C identifier form (rejects retry_count++)",
    "s0530": " layer_name represents \\\"the layer this draft belongs to\\\"",
    "s0531": "Common widget for selecting globals, event flags, return values",
    "s0532": " New column order: 0=title, 1=function, 2=namespace, 3=description",
    "s0533": " Auto-complete 1: register SM role functions",
    "s0534": " If not added anywhere, becomes standalone",
    "s0535": "Used as generated file name <project_name>_run.c",
    "s0536": "\\nLayer settings dialog\\n",
    "s0537": "  Empty -> generates without layer name (STATE_Idle).\\n",
    "s0538": " ---- Test mode: do not generate WebEngine ----",
    "s0539": " A1: for STATABLE_DISABLE_MERMAID check",
    "s0540": " Debug log: content passed to ActionEditorDialog",
    "s0541": "Select or enter state transition event name from ISR.\\n",
    "s0542": "Generate statable_all.h (for user main.c)",
    "s0543": "Dialog to manage interrupt handlers, resources, timers",
    "s0544": "Please enter an interrupt name (e.g., TIMER0_IRQHandler)",
    "s0545": " A1: branch WebEngine import by env var",
    "s0546": " Attribute access (prefs.last_project_dir etc.)",
    "s0547": "Literalize numeric values. Give each value a name.",
    "s0548": "\\nAction edit main dialog\\n",
    "s0549": "\\nTransition edit dialog\\n",
    "s0550": "GUI display name: 'Driver.Init' or 'Init'",
    "s0551": "Automatically convert DIRECT events used in ISR to DOUBLE",
    "s0552": "Select QUEUE if you need event counts or data.",
    "s0553": "Specified header is #include'd into insertion target.",
    "s0554": "If specified, can be referenced as 'Driver.Init'.\\n",
    "s0555": "\\nStaTable main widget\\n",
    "s0556": "\\nVisual edit flow list\\n",
    "s0557": "\\nC code generation dialog\\n",
    "s0558": " v1.5 change: 8 columns -> 9 columns",
    "s0559": " If event name is empty, default to \\\"NewEvent\\\"",
    "s0560": "Processing aborted beyond this count.",
    "s0561": "- Priority: range 1-9. 1 (low) runs first.\\n",
    "s0562": "Register all timer base variables as global variables",
    "s0563": "   Generates cell-level transition functions.",
    "s0564": " v1.5 new: namespace input field",
    "s0565": " Merge shared library and SM role functions",
    "s0566": " Do not accept, to handle double-click",
    "s0567": "Please install PySide6-Addons.\\n",
    "s0568": "else condition\\n- Drop a function on top",
    "s0569": "- Layer name: used in code identifiers (e.g., Driver -> ",
    "s0570": " Prevent text items from receiving mouse events",
    "s0571": "statable_all.h (for user main.c)",
    "s0572": "- Tab name: display name.",
    "s0573": "\\nState transition table widget\\n",
    "s0574": " Namespace.Name form: insert reference only",
    "s0575": " Completely disable canvas drag move",
    "s0576": " Generation style / table style fixed",
    "s0577": " Extract only file name from path",
    "s0578": "* Fixed to style optimized for C.\\n",
    "s0579": "Return (name, sm) list sorted by priority ascending",
    "s0580": "Describe \\\"state transition condition\\\" and \\\"action code\\\"\\n",
    "s0581": "If condition is empty, action runs unconditionally.\\n",
    "s0582": " Automatically convert ISR DIRECT to DOUBLE",
    "s0583": " For node position saving",
    "s0584": " Event list table (title column added)",
    "s0585": " Register data from sample state machine",
    "s0586": "Override drag start to reliably execute QDrag",
    "s0587": "Unique key in library: 'Driver.Init'",
    "s0588": "   clear() preserves it",
    "s0589": " Also detect suffix match of 'Namespace.Name'",
    "s0590": " [v1.5 fix] register role function",
    "s0591": "If any transition condition uses this literal,\\n",
    "s0592": "Table that captures double-click events",
    "s0593": "Entering a new event name registers it as-is.",
    "s0594": " Debug log: scene rect and viewport info",
    "s0595": " change: use qualified_name",
    "s0596": " Action column or display title column -> D&D editor",
    "s0597": " If already starts with RoleFunc_, keep as-is",
    "s0598": "OK button: update event delivery type and close",
    "s0599": "QWebEngineView is not available.\\n",
    "s0600": "Table-driven style (cell-level function + function table)",
}

BATCHES["batch4"] = {
    "s0601": "Role function node\\n- Double-click to rename",
    "s0602": "Example: battery_voltage > 3000",
    "s0603": "Determine if event used from interrupt handler",
    "s0604": "Save by merging with existing file",
    "s0605": "\\nLiteral management dialog\\n",
    "s0606": "---- Test mode: do nothing ----",
    "s0607": "Always fixed to 3-line display",
    "s0608": "Direct save of generated code",
    "s0609": "Get target state choices from state machine",
    "s0610": "FlowItem -> Transition conversion",
    "s0611": "Collapsible palette by category",
    "s0612": "Action flow (drag & drop, double-click)",
    "s0613": "If empty, treated as no layer ('Init').",
    "s0614": "2. Count namespaces of referenced functions",
    "s0615": "===== External include operations =====",
    "s0616": " Prefer displaying qualified_name",
    "s0617": " Debug log: output received text",
    "s0618": "List table (title column added)",
    "s0619": "Ignore write failures",
    "s0620": "On edit, always delete old then add",
    "s0621": "Setting item definitions",
    "s0622": "Role function library shared across project",
    "s0623": "Array style (2D array + O(1) access)",
    "s0624": "===== Double-click edit =====",
    "s0625": "===== Sync on list change =====",
    "s0626": "3-line display on FlowNodeItem side",
    "s0627": "Maintain 3 lines when flow_item absent",
    "s0628": " v1.5: function name is column 1",
    "s0629": "Global variables, event flags, interrupts,",
    "s0630": "Debug log: output shared library content",
    "s0631": "Search for corresponding StateMachine",
    "s0632": "else action\\n- Reorder via ordered list",
    "s0633": "Sample data generation (GUI layer re-export)",
    "s0634": "Literal library shared across project",
    "s0635": "Transition condition library shared",
    "s0636": "Priority is duplicated. Continue anyway?",
    "s0637": "Output directory is not set.\\n",
    "s0638": "Add available symbols to tree by category",
    "s0639": "Set default values for unsaved keys",
    "s0640": "Display derived timers of specified timer",
    "s0641": "Short label shown in state transition table",
    "s0642": "- Normal: import as before",
    "s0643": "=== Reflect role function table ===",
    "s0644": "===== Load draft =====",
    "s0645": "OS type (this is meaningful, so selectable)",
    "s0646": "Reflect current value to combo box after UI",
    "s0647": "Check event_names list",
    "s0648": "Shared library (across project)",
    "s0649": "STATE_Driver_Idle).\\n",
    "s0650": "StaTable dedicated logger (singleton)",
    "s0651": "Title of this event. Direct editing allowed.",
    "s0652": "Global variables, event flags, return values",
    "s0653": "Global variables / event flag management",
    "s0654": "Check this if timer interrupt",
    "s0655": "Interrupt handler, device resources, timers",
    "s0656": "Recompute conversion column from settings",
    "s0657": "Apply settings to each StateMachine",
    "s0658": "You must also remove from condition expression.",
    "s0659": "Edit the selected row with visual editor",
    "s0660": "Explicitly import it.",
    "s0661": " Output matching real file generation",
    "s0662": "Collect role function prototypes (dedupe)",
    "s0663": "Internal moves left to standard behavior",
    "s0664": "If layer name unset, use tab name",
    "s0665": "Flow list supporting D&D and row insertion",
    "s0666": "\\nPlease delete these transitions first.",
    "s0667": "Title of this queue. Direct editing allowed.",
    "s0668": "Enter description of this interrupt handler",
    "s0669": "Open global variables / event flag definitions",
    "s0670": "Dialog to literalize numeric values",
    "s0671": "// else target (not set)",
    "s0672": "---- Event handler ----",
    "s0673": "2. From current SM role functions",
    "s0674": "Check the code in actions",
    "s0675": " Legacy form: preserve call with args",
    "s0676": "Timer settings tab (multi-base-timer)",
    "s0677": "Reference name -> RoleFunc function name",
    "s0678": "If condition is empty, show \\\"Condition: none\\\"",
    "s0679": "Generate Doxygen-style comments",
    "s0680": "transitions .c file",
    "s0681": "Interrupt name driving this timer (optional)",
    "s0682": "Title of this transition. Direct editing allowed.",
    "s0683": "Global variables & event flag definitions",
    "s0684": "Double-click to edit each cell.",
    "s0685": "Dialog for creating/editing role functions",
    "s0686": "Upper limit of consecutive pending events.\\n",
    "s0687": "Shared literal management dialog",
    "s0688": "Namespace (layer name / feature group).\\n",
    "s0689": "Save current settings to JSON file",
    "s0690": "Reflect current target into combo box",
    "s0691": "Update setting by key name and save",
    "s0692": "Dialog to build transition condition via GUI",
    "s0693": "Pre-transition processing\\n- Reorder via ordered list",
    "s0694": "Update conversion column when combo changes",
    "s0695": "----  Code generation ----",
    "s0696": "=== Reflect state table ===",
    "s0697": " Interrupt name driving this timer",
    "s0698": " Auto-extract used role functions and vars",
    "s0699": " Update library references of existing tabs",
    "s0700": "Window / preview size constants",
    "s0701": "Title (editable, linked to tab name)",
    "s0702": "Bottom: display C code in ctx-> form",
    "s0703": "Set undefined ones as normal attributes",
    "s0704": "Skip if already present in library",
    "s0705": "Use first 20 chars of condition as title",
    "s0706": "If target is empty, show \\\"-> (not set)\\\"",
    "s0707": "C code generation dialog (multi-layer)",
    "s0708": "Show/hide TraceBall log",
    "s0709": "Open pre-generation validation / AI diag",
    "s0710": "Load when sample data not set",
    "s0711": "Get state name list from state machine",
    "s0712": "Enter title, member name, group name",
    "s0713": "Switch edit dialog based on column",
    "s0714": "Please select a literal to delete.",
    "s0715": "Open condition builder to edit expression",
    "s0716": "Generated C code (ctx-> form)",
    "s0717": "Please select a literal to edit.",
    "s0718": "Get setting by key name (legacy style)",
    "s0719": "\\nSystem global variables (separate screen)\\n",
    "s0720": "---- Data load ----",
    "s0721": "---- Setting read/write ----",
    "s0722": " Generation style / table style fixed",
    "s0723": " Multi-layer list (set from outside)",
    "s0724": "System global definitions (if any)",
    "s0725": "Pass library object directly",
    "s0726": "If key defined, set and save",
    "s0727": "State transition condition column -> builder",
    "s0728": "Load settings from JSON file",
    "s0729": "include/src separation (recommended)",
    "s0730": "Event flag bulk register dialog",
    "s0731": "Global variable bulk register dialog",
    "s0732": "Double-click to open condition builder",
    "s0733": "Double-click to edit state transition condition",
    "s0734": "Example: Driver (empty = no layer)",
    "s0735": "Open D&D editor for specified row",
    "s0736": "Enter a new timer name:",
    "s0737": "State transition event definition list dialog",
    "s0738": "\\nShared library management package\\n",
    "s0739": "---- Normal mode ----",
    "s0740": "Create and insert FlowItem",
    "s0741": " Pass current else target",
    "s0742": " Automatic multi-layer / single detection",
    "s0743": " Attach warning collection handler",
    "s0744": "Global settings checkbox",
    "s0745": "Set node size and displayed content",
    "s0746": "Rebuild dict preserving original positions",
    "s0747": "Notify parent FlowWidget",
    "s0748": "Create edit tab for one base timer",
    "s0749": "Event queue definition list dialog",
    "s0750": "State machine and global definitions",
    "s0751": "Double-click to edit action code",
    "s0752": "Generate user code markers",
    "s0753": "Dialog for adding/editing literals",
    "s0754": "Interrupt handler, device resources,",
    "s0755": "Set layer execution priority and order",
    "s0756": "Dialog to edit state transition conditions",
    "s0757": "Edit transition (D&D visual editing)",
    "s0758": "---- Warning display ----",
    "s0759": "ISR usage column (read-only)",
    "s0760": " Replace shared library too",
    "s0761": " Generation style (fixed display)",
    "s0762": "Role function return value (temp var)",
    "s0763": "Please enter a group name.",
    "s0764": "Sample data loaded",
    "s0765": "Title, member name, group name",
    "s0766": "The main timer cannot be deleted.",
    "s0767": "Manage user-defined types (structs)",
    "s0768": "Shared role function edit dialog",
    "s0769": "Select an external include file",
    "s0770": "State transition event definition dialog",
    "s0771": "State transition event edit dialog",
    "s0772": "No code was generated.",
    "s0773": "Please select a row to edit.",
    "s0774": "Function name prefix (optional)",
    "s0775": "\\nRole function edit dialog\\n",
    "s0776": "\\nShared role function library\\n",
    "s0777": "\\nAction edit D&D package\\n",
    "s0778": "else target state selection",
    "s0779": " Apply project settings",
    "s0780": " Collect project settings",
    "s0781": " Show warnings last if any",
    "s0782": "Event name (read-only)",
    "s0783": "Double-click to rename tab",
    "s0784": "Default settings file path",
    "s0785": "Undefined attributes raise normal errors",
    "s0786": "Import the settings dialog",
    "s0787": "Added: current else target",
    "s0788": "Event queue definition dialog",
    "s0789": "Event selection combo box",
    "s0790": "Open event delivery type settings",
    "s0791": "Error: max < min",
    "s0792": "Group selection combo box",
    "s0793": "Return the checkbox state",
    "s0794": "User-defined type management dialog",
    "s0795": "User-defined type edit dialog",
    "s0796": "Used literals (select from existing)",
    "s0797": "First set the output directory in settings",
    "s0798": "Display all base timers as tabs",
    "s0799": "The condition expression is empty.",
    "s0800": "\\nShared literal library\\n",
}

BATCHES["batch5"] = {
    "s0801": "\\nShared transition condition library\\n",
    "s0802": "    // target not set",
    "s0803": " 1. From shared library",
    "s0804": " Code generation settings manager",
    "s0805": " Title input widget",
    "s0806": " Title (direct edit)",
    "s0807": " Title (read-only)",
    "s0808": " Role function select / insert bar",
    "s0809": " Priority (spin box)",
    "s0810": " Dialog launch methods",
    "s0811": " Handler when the name changes",
    "s0812": " Conversion column (read-only)",
    "s0813": " External include file",
    "s0814": " If key is defined, return its value",
    "s0815": " Condition expression (including literals)",
    "s0816": " Validation / AI integration module",
    "s0817": "include folder name:",
    "s0818": "Delete this node?",
    "s0819": "Find the row number from event name",
    "s0820": "Event delivery settings dialog",
    "s0821": "Open global definitions...",
    "s0822": "Title, event name, description",
    "s0823": "Double-click to edit with D&D",
    "s0824": "Edit device resource placeholder",
    "s0825": "Visual edit widget",
    "s0826": "Use bit fields",
    "s0827": "Load the whole project",
    "s0828": "Add / edit user-defined types",
    "s0829": "Open the layer settings dialog",
    "s0830": "role functions .c file",
    "s0831": "Condition expression (symbol names)",
    "s0832": "Struct member edit dialog",
    "s0833": "Open state transition event definitions",
    "s0834": " Pass current target",
    "s0835": " Multi-layer support helper",
    "s0836": " Create text item",
    "s0837": " Drop from palette",
    "s0838": " Project save / load",
    "s0839": " Logger (lightweight)",
    "s0840": " Log / validation / code generation",
    "s0841": " Role function (bool)",
    "s0842": " Shared literal library",
    "s0843": " Interrupt handler check",
    "s0844": " If failure occurs, revert",
    "s0845": " Layer list table (4 columns)",
    "s0846": " Left: symbol picker",
    "s0847": " Add condition template",
    "s0848": " Source (read-only)",
    "s0849": " Related event selection list",
    "s0850": "Generate DEBUG logs",
    "s0851": "Generate ERROR logs",
    "s0852": "Event flag bulk register",
    "s0853": "Event prefix:",
    "s0854": "Global variable bulk register",
    "s0855": "Code generation settings dialog",
    "s0856": "System globals...",
    "s0857": "Title, queue name, description",
    "s0858": "Title input widget",
    "s0859": "Project folder name:",
    "s0860": "Example: MyProject",
    "s0861": "Shared transition condition template",
    "s0862": "Please enter a name.",
    "s0863": "External include file",
    "s0864": "External include settings tab",
    "s0865": "No layers are defined.",
    "s0866": "Add a new state transition tab",
    "s0867": "Conditional action list:",
    "s0868": "Search filter (prefix match)",
    "s0869": "State selection combo box",
    "s0870": "Get generated files",
    "s0871": "Reset settings?",
    "s0872": "Open advanced settings dialog",
    "s0873": " Event delivery settings",
    "s0874": " Event list table",
    "s0875": " Open global definitions",
    "s0876": " Code generation module",
    "s0877": " Table style: fixed",
    "s0878": " Device resource tab",
    "s0879": " Device / timer settings",
    "s0880": " Role function section",
    "s0881": " Sort by priority ascending",
    "s0882": " Priority duplicate check",
    "s0883": " Deduplication (order-preserving)",
    "s0884": "Generate INFO logs",
    "s0885": "Use else condition",
    "s0886": "Add group dialog",
    "s0887": "System global variables",
    "s0888": "Flag prefix:",
    "s0889": "Role function (bool)",
    "s0890": "Common UI components",
    "s0891": "Type selection combo box",
    "s0892": "Enter a new group name",
    "s0893": "Save generated code...",
    "s0894": "Generated code preview:",
    "s0895": " D&D editor integration",
    "s0896": " v1.5 added",
    "s0897": " Project name",
    "s0898": " Layer name (editable)",
    "s0899": " Add timer base",
    "s0900": " Do nothing otherwise",
    "s0901": " Symbol name text",
    "s0902": " Tab name (read-only)",
    "s0903": " Double-click handling",
    "s0904": " For drag attempt detection",
    "s0905": " Project XML",
    "s0906": " Used global variables",
    "s0907": " Derived timer button",
    "s0908": " Added: current target",
    "s0909": " Target state selection",
    "s0910": " Transition condition section",
    "s0911": "Event: completion transition",
    "s0912": "Change code generation settings",
    "s0913": "Handler when style changes",
    "s0914": "Super include",
    "s0915": "Layer settings dialog",
    "s0916": "Use attached data",
    "s0917": "common .c file",
    "s0918": "Edit base timer...",
    "s0919": "Add new group",
    "s0920": "New role function...",
    "s0921": "Number of conditional actions",
    "s0922": "Validation / AI diagnosis...",
    "s0923": "State prefix:",
    "s0924": "State transition event definition",
    "s0925": "Direct save of generated code",
    "s0926": "is not set.",
    "s0927": "Update settings info label",
    "s0928": " Action buttons",
    "s0929": " Event name edit field",
    "s0930": " Default target",
    "s0931": " Bit field",
    "s0932": " Preview area",
    "s0933": " Merge settings label",
    "s0934": " Literalize button",
    "s0935": " Unique literal name",
    "s0936": " Pending event limit",
    "s0937": " Interrupt handler tab",
    "s0938": " Right: condition expression edit",
    "s0939": " Base timer tab",
    "s0940": " Resolve layer name and type name",
    "s0941": " Last used folder",
    "s0942": " Generation style: fixed",
    "s0943": " Settings info group",
    "s0944": " Logical operator combo",
    "s0945": " Delivery type combo",
    "s0946": "+ Add role function",
    "s0947": "// target not set",
    "s0948": "else (not set)",
    "s0949": "src folder name:",
    "s0950": "Edit event queue",
    "s0951": "Edit event flag",
    "s0952": "Event definitions...",
    "s0953": "Edit global variable",
    "s0954": "Generate comments",
    "s0955": "Code generation(&G)",
    "s0956": "Edit timer base variable",
    "s0957": "There are no tabs.",
    "s0958": "Build the table",
    "s0959": "Default target:",
    "s0960": "Save project",
    "s0961": "Open project",
    "s0962": "User-defined type management",
    "s0963": "User-defined type edit",
    "s0964": "Used global variables",
    "s0965": "Output directory",
    "s0966": "Handler when output dir changes",
    "s0967": "Interrupt name (optional)",
    "s0968": "Please specify.",
    "s0969": "Max consecutive processing:",
    "s0970": "Edit derived timer variable",
    "s0971": "Rename current tab",
    "s0972": " C source output dir",
    "s0973": " OS type label",
    "s0974": " Pass all layers",
    "s0975": " Multi-layer generation",
    "s0976": " Export dir",
    "s0977": " Custom list",
    "s0978": " Double-click",
    "s0979": " Template name",
    "s0980": " Preview apply",
    "s0981": " Progress bar",
    "s0982": " Add literal",
    "s0983": " Spec documents location",
    "s0984": " Completion message",
    "s0985": " Strip argument part",
    "s0986": " Determine insertion position",
    "s0987": " Search by bare name",
    "s0988": " Advanced settings button",
    "s0989": " Warning collector class",
    "s0990": "+ Add transition condition",
    "s0991": "Event selection screen",
    "s0992": "Code generation...",
    "s0993": "Run code generation",
    "s0994": "Open timer settings",
    "s0995": "Device resource",
    "s0996": "Debug log settings",
    "s0997": "Register flag...",
    "s0998": "Update preview",
    "s0999": "Prefix:",
    "s1000": "Project name:",
}

BATCHES["batch6"] = {
    "s1001": "Project settings",
    "s1002": "Main toolbar",
    "s1003": "Retry count threshold",
    "s1004": "Pending event settings",
    "s1005": "Shared literal definition",
    "s1006": "Common folder name:",
    "s1007": "Interrupt handler definition",
    "s1008": "Add base timer",
    "s1009": "External include",
    "s1010": "Symbol to insert",
    "s1011": "Edit condition...",
    "s1012": "Struct member edit",
    "s1013": "Derived timer variable:",
    "s1014": "State transition condition edit",
    "s1015": "Save current settings",
    "s1016": "Save generated code",
    "s1017": "Reflect settings to UI",
    "s1018": "About settings items",
    "s1019": "Transition condition builder",
    "s1020": " RTOS usage",
    "s1021": " Newly added",
    "s1022": " Event ID",
    "s1023": " Event variable",
    "s1024": " Event kind",
    "s1025": " Clear button",
    "s1026": " Comment settings",
    "s1027": " Signal connection",
    "s1028": " Debug log",
    "s1029": " Log settings tab",
    "s1030": " Used events",
    "s1031": " Used literals",
    "s1032": " Dependency check",
    "s1033": " Output settings tab",
    "s1034": " Constant symbol",
    "s1035": " Condition builder",
    "s1036": " Generation style",
    "s1037": " Source layer",
    "s1038": " Duplicate check",
    "s1039": "Generate C code",
    "s1040": "entry function",
    "s1041": "Global definitions",
    "s1042": "Table style:",
    "s1043": "Reset button",
    "s1044": "Register variable...",
    "s1045": "Validation / AI diagnosis",
    "s1046": "Save generated code",
    "s1047": "Generation style:",
    "s1048": "Generation settings...",
    "s1049": "Advanced settings...",
    "s1050": "Pre-transition processing:",
    "s1051": "Placement folder:",
    "s1052": "Handler on close",
    "s1053": " D&D edit",
    "s1054": " Event name",
    "s1055": " Code generation",
    "s1056": " Toolbar",
    "s1057": " Merge settings",
    "s1058": " Attached data",
    "s1059": " With priority",
    "s1060": " Register button",
    "s1061": " Set rect",
    "s1062": " Edit button",
    "s1063": " Settings / environment",
    "s1064": " Delivery type",
    "s1065": "(untitled action)",
    "s1066": "(untitled condition)",
    "s1067": "C code generation",
    "s1068": "RTOS usage",
    "s1069": "exit function",
    "s1070": "Event ID",
    "s1071": "Event name:",
    "s1072": "Event variable",
    "s1073": "Add group",
    "s1074": "Comment settings",
    "s1075": "Rename timer",
    "s1076": "Data variable name",
    "s1077": "File name:",
    "s1078": "Folder structure",
    "s1079": "Member list:",
    "s1080": "Literal management",
    "s1081": "Literal edit",
    "s1082": "Add literal",
    "s1083": "Log settings tab",
    "s1084": "Used events",
    "s1085": "Output settings tab",
    "s1086": "Interrupt handler",
    "s1087": "Interrupt settings",
    "s1088": "Action code:",
    "s1089": "Basic settings tab",
    "s1090": "Constant symbol",
    "s1091": "Numeric literal",
    "s1092": "Validate(&V)",
    "s1093": "Generation style",
    "s1094": "Generation settings info",
    "s1095": "Source layer",
    "s1096": "Display title",
    "s1097": "Logical operator:",
    "s1098": " Layer name",
    "s1099": " New",
    "s1100": " Orange",
    "s1101": " Queue name",
    "s1102": " Title",
    "s1103": " Tab management",
    "s1104": " Menu",
    "s1105": " Literal",
    "s1106": " Refresh list",
    "s1107": " Future support",
    "s1108": " Output settings",
    "s1109": " Initial tab",
    "s1110": " Interrupt protection",
    "s1111": " Right pane",
    "s1112": " Left pane",
    "s1113": " Left/right split",
    "s1114": " Preferences",
    "s1115": "D&D edit",
    "s1116": "ISR usage",
    "s1117": "OK button",
    "s1118": "Event:",
    "s1119": "Group name",
    "s1120": "Timer settings",
    "s1121": "Rename tab",
    "s1122": "Driver layer",
    "s1123": "Flow edit",
    "s1124": "Merge settings",
    "s1125": "Delete member",
    "s1126": "Edit member",
    "s1127": "Add member",
    "s1128": "Literal name",
    "s1129": "Attached data",
    "s1130": "With priority",
    "s1131": "Action code",
    "s1132": "Generation style:",
    "s1133": "Get settings",
    "s1134": " Size",
    "s1135": " Help",
    "s1136": " Priority",
    "s1137": " Output directory",
    "s1138": " Bare name",
    "s1139": " Insertion target",
    "s1140": " Note:",
    "s1141": " Row management",
    "s1142": " Element type",
    "s1143": "(complete)",
    "s1144": "do function",
    "s1145": "Data type",
    "s1146": "Merge:",
    "s1147": "Middle layer",
    "s1148": "Member count",
    "s1149": "Reset",
    "s1150": "Literal",
    "s1151": "Show log",
    "s1152": "Log settings",
    "s1153": "Edit action",
    "s1154": "Naming convention",
    "s1155": "Basic settings",
    "s1156": "Variable name:",
    "s1157": "Operation not allowed",
    "s1158": "New tab",
    "s1159": "Min voltage",
    "s1160": "State list",
    "s1161": "Generation settings",
    "s1162": "Auto layout",
    "s1163": "Add row",
    "s1164": "Display name:",
    "s1165": "No transition",
    "s1166": "Transition condition",
    "s1167": " Tab",
    "s1168": " List",
    "s1169": " Body",
    "s1170": " Register",
    "s1171": " Array",
    "s1172": "Clear",
    "s1173": "Code",
    "s1174": "Type",
    "s1175": "Tab name",
    "s1176": "Name:",
    "s1177": "Type definitions",
    "s1178": "Converted",
    "s1179": "Insert target",
    "s1180": "Structure:",
    "s1181": " Value",
    "s1182": " Red",
    "s1183": " Blue",
    "s1184": "Value:",
    "s1185": "Action",
    "s1186": "Name",
    "s1187": "Type:",
    "s1188": "Layer name",
    "s1189": "Numeric",
    "s1190": "Disabled",
    "s1191": "Duplicate",
    "s1192": "Open",
    "s1193": "Value",
    "s1194": "Row",
    "s1195": "Stop request",
    "s1196": "Source",
    "s1197": "Please check the event definitions",
    "s1198": "No matching transition found",
    "s1199": "Function name is not specified",
    "s1200": "Please change the variable name",
}

BATCHES["batch7"] = {
    "s1201": "Restore from dictionary",
    "s1202": "Error handling",
    "s1203": "Error state",
    "s1204": "Convert to dictionary",
    "s1205": "Event",
    "s1206": "Initial state",
    "s1207": "Power ON",
    "s1208": "State name",
    "s1209": "Stop",
    "s1210": "Variable",
    "s1211": "State",
    "s1212": "Function",
    "s1213": "\\nMerge generated and existing code\\nPreserve user edits\\n\\n[v2.0 fix] Replace existing marker block\\n",
    "s1214": "{\\n  \\\"changes\\\": [\\n    {\\n      \\\"action\\\": \\\"set_initial\\\",\\n      \\\"params\\\": {\\\"state\\\": \\\"INIT\\\"},\\n      \\\"reason\\\": \\\"Initial state not set\\\"\\n    },\\n    {\\n      \\\"action\\\": \\\"add_transition\\\",\\n      \\\"params\\\": {\\\"source\\\": \\\"ERROR\\\", \\\"event\\\": \\\"RESET\\\", \\\"target\\\": \\\"IDLE\\\"},\\n      \\\"reason\\\": \\\"No error recovery\\\"\\n    }\\n  ]\\n}",
    "s1215": "\\n        Merge all files (folder structure support)\\n",
    "s1216": "You are a state machine design expert.\\n\\n[Task] Validate state machine data and output changes in JSON.\\n\\n[Output] Pure JSON only. No greetings, no markers, no code blocks.\\n\\n{example}\\n\\n{data}\\n",
    "s1217": "\\n        Inject whole-file user code\\n",
    "s1218": "\\nSample data for code generation tests\\n",
    "s1219": "\\n        Remove a role function.\\n",
    "s1220": "\\n        Extract user code for all functions\\n",
    "s1221": "\\nEvent validation\\n",
    "s1222": "\\nTransition validation\\n",
    "s1223": "\\n        Replace existing marker block with user_code\\n",
    "s1224": "\\nAction definitions (data only)\\n",
    "s1225": "\\nChange apply engine (fixed version)\\n",
    "s1226": "[Validation points]\\n1. Initial state set?\\n2. All states have transitions?\\n3. Error recovery?\\n4. All events covered?\\n5. Unreachable states?\\n6. Deadlock?\\n",
    "s1227": "\\n    PEP 562 lazy import\\n",
    "s1228": "\\nStaTable code generation layer\\n",
    "s1229": "\\nPrompt template definitions (data only)\\n",
    "s1230": "\\nAI prompt generation class\\n",
    "s1231": " Match by qualified_name",
    "s1232": " v1.6: accept parent parameter",
    "s1233": "Transition \\\"{source} --[{event}]--> {target}\\\" is duplicated",
    "s1234": " v1.6: fall back to NORMAL",
    "s1235": " ---- 2. If block missing, insert after include ----",
    "s1236": " Match by bare name",
    "s1237": "Self transition \\\"{source} --[{event}]--> {source}\\\"",
    "s1238": "State names \\\"{name}\\\" and \\\"{other}\\\" differ in case",
    "s1239": " Function name extraction pattern",
    "s1240": " [v1.5 fix] action= -> pre_actions=[]",
    "s1241": " Get handler by ChangeActionType value",
    "s1242": " Default logger",
    "s1243": "\\nCode generation settings management module\\n",
    "s1244": "min_value <= max_value required",
    "s1245": " Function user code injection: replace block",
    "s1246": "Interrupt \\\"{name}\\\" contains undefined events",
    "s1247": "No transition defined for event \\\"{name}\\\"",
    "s1248": "Event \\\"{name}\\\" is not used",
    "s1249": "Queue \\\"{name}\\\" contains undefined events",
    "s1250": "Inject user code at end of generated code",
    "s1251": "Class mapping StaTable types to C",
    "s1252": "Please set initial state with set_initial()",
    "s1253": "Timer variable \\\"{name}\\\" duplicates existing",
    "s1254": " ---- 1. Replace if existing block exists ----",
    "s1255": "Convert to PascalCase",
    "s1256": "Function name (bare or namespace.name)",
    "s1257": "Variable \\\"{name}\\\" has invalid type \\\"{type}\\\"",
    "s1258": "Role function \\\"{name}\\\" has incomplete args",
    "s1259": "Role function \\\"{name}\\\" has undefined return type",
    "s1260": "Type \\\"{name}\\\" has no members",
    "s1261": "Add transition or mark as terminal",
    "s1262": "\\nC language type mapping module\\n",
    "s1263": " ===== Super include =====",
    "s1264": "Event \\\"{event}\\\" is not defined",
    "s1265": "Role function \\\"{name}\\\" is unused",
    "s1266": "Source \\\"{source}\\\" is not defined",
    "s1267": "Target \\\"{target}\\\" is not defined",
    "s1268": " If camelCase, capitalize first letter",
    "s1269": "Add transition or delete event",
    "s1270": "\\nC language naming convention module\\n",
    "s1271": " ===== Project settings =====",
    "s1272": " ===== Marker presence check =====",
    "s1273": " ===== Reserved event limit =====",
    "s1274": " ===== External include =====",
    "s1275": "Convert action definitions to prompt text",
    "s1276": "Interrupt name \\\"{name}\\\" is duplicated",
    "s1277": "Variable \\\"{name}\\\" has invalid array size",
    "s1278": "Check if function contains user code",
    "s1279": "State \\\"{name}\\\" has no outgoing transition",
    "s1280": "Queue \\\"{name}\\\" has invalid size",
    "s1281": "Newly inserted file user code",
    "s1282": "Flag name \\\"{name}\\\" is duplicated",
    "s1283": "No existing code, using generated",
    "s1284": "Add transition or delete state",
    "s1285": "Array size must be > 0",
    "s1286": " ===== Comment generation =====",
    "s1287": " ===== Debug log =====",
    "s1288": " ===== Folder structure =====",
    "s1289": " ===== Generation style =====",
    "s1290": "Timer \\\"{name}\\\" has invalid multiplier",
    "s1291": "Flag \\\"{name}\\\" has invalid range",
    "s1292": "Variable name \\\"{name}\\\" is duplicated",
    "s1293": "Please set arg names and types",
    "s1294": " ===== Merge processing =====",
    "s1295": " File end user code injection",
    "s1296": " Inject at top if no include",
    "s1297": " Inject whole-file user code",
    "s1298": "Size must be > 0",
    "s1299": "File user code extracted",
    "s1300": "File user code replaced",
    "s1301": "Type name \\\"{name}\\\" is duplicated",
    "s1302": "Class merging generated and existing code",
    "s1303": " ===== Marker =====",
    "s1304": " ===== Output settings =====",
    "s1305": " ===== Naming convention =====",
    "s1306": " ===== Extraction processing =====",
    "s1307": " ===== Injection processing =====",
    "s1308": " Inject user code into generated",
    "s1309": "Extract whole-file user code",
    "s1310": "Extract end-of-file user code",
    "s1311": "Multiplier must be > 0",
    "s1312": "Apply change requests to system",
    "s1313": "State \\\"{name}\\\" is unreachable",
    "s1314": "Confirm if self transition is intentional",
    "s1315": "\\nKeyword definitions (data only)\\n",
    "s1316": "\\nValidation rule definitions (data only)\\n",
    "s1317": " Define handler dict by string key",
    "s1318": " File end user code extraction",
    "s1319": " Extract function-level user code",
    "s1320": " Inject function-level user code",
    "s1321": "### Problems detected by internal validation",
    "s1322": "### Internal validation result\\nNo problems",
    "s1323": "Class managing C naming conventions",
    "s1324": "Initial state[::]\\s*(\\w+)",
    "s1325": "End user code extracted",
    "s1326": "End user code injected",
    "s1327": "\\nLogger setup for validation module\\n",
    "s1328": "\\nPer-item validator package\\n",
    "s1329": "Event name is not specified",
    "s1330": "Whether user code is included",
    "s1331": "Merge generated and existing code",
    "s1332": "Please define the source state",
    "s1333": "Please define the target state",
    "s1334": "Please delete the duplicate transition",
    "s1335": "Extract function-level user code",
    "s1336": "\\nValidation / AI integration package\\n",
    "s1337": "Initial state is not set",
    "s1338": "Please change the interrupt name",
    "s1339": "End marker not found",
    "s1340": " End-of-file user area",
    "s1341": "include/src separation",
    "s1342": "Please define the event",
    "s1343": "Code generation validation main class",
    "s1344": "Please change the flag name",
    "s1345": "Please add a member",
    "s1346": "Get summary of user code",
    "s1347": "Please use or delete it",
    "s1348": "Please unify the naming convention",
    "s1349": "Please set the return type",
    "s1350": "Please specify a valid type",
    "s1351": "State name is not specified",
    "s1352": "Transition information is incomplete",
    "s1353": "\\nValidator base class\\n",
    "s1354": "\\nValidation data package\\n",
    "s1355": "\\nValidation data model definitions\\n",
    "s1356": " Folder structure compatible version",
    "s1357": " Inject after include",
    "s1358": " Various user code extractions",
    "s1359": "AI prompt generation class",
    "s1360": "[Available actions]",
    "s1361": "Clipboard management class",
    "s1362": "Sample data generation class",
    "s1363": "\\nClipboard management\\n",
    "s1364": "\\nChange action definitions\\n",
    "s1365": "System status management struct",
    "s1366": "Available table styles",
    "s1367": "Available generation styles",
    "s1368": "Please change the type name",
    "s1369": "Please add a transition",
    "s1370": "High priority event queue",
    "s1371": "\\nAI answer parser\\n",
    "s1372": "\\nValidation main class\\n",
    "s1373": " Console handler",
    "s1374": "UART receive interrupt",
    "s1375": "\\n### Events",
    "s1376": "Custom type validation class",
    "s1377": "Sensor data struct",
    "s1378": "Validator base class",
    "s1379": "Main event queue",
    "s1380": "Setup logger",
    "s1381": "Role function validation class",
    "s1382": "\\nCustom type validation\\n",
    "s1383": "\\nRole function validation\\n",
    "s1384": " File handler",
    "s1385": " Logger referenced directly",
    "s1386": " Ignore unknown keys",
    "s1387": " Transition table style",
    "s1388": "UART communication port",
    "s1389": "Event validation class",
    "s1390": "Error detection event",
    "s1391": "Available OS types",
    "s1392": "Interrupt validation class",
    "s1393": "Change action kind",
    "s1394": "Partially update settings",
    "s1395": "Dictionary style (deprecated)",
    "s1396": "\\nInterrupt validation\\n",
    "s1397": "AI answer parser",
    "s1398": "\\n### Transitions",
    "s1399": "Understood",
    "s1400": "Queue validation class",
}

BATCHES["batch8"] = {
    "s1401": "Timer validation class",
    "s1402": "Flag validation class",
    "s1403": "Merge processing started",
    "s1404": "Remove role function",
    "s1405": "Add role function",
    "s1406": "Initialization complete flag",
    "s1407": "New action",
    "s1408": "Validation context",
    "s1409": "Start condition check",
    "s1410": "Power ON event",
    "s1411": "\\nQueue validation\\n",
    "s1412": "\\nTimer validation\\n",
    "s1413": "\\nFlag validation\\n",
    "s1414": " Path resolution",
    "s1415": " Marker definitions",
    "s1416": "AD converter",
    "s1417": "Please check",
    "s1418": "Best regards",
    "s1419": "Add event",
    "s1420": "System timer",
    "s1421": "Data buffer",
    "s1422": "Battery voltage",
    "s1423": "Set initial state",
    "s1424": "Variable validation class",
    "s1425": "Change request",
    "s1426": "Convert from string",
    "s1427": "State validation class",
    "s1428": "Reset settings",
    "s1429": "Settings management class",
    "s1430": "Transition validation class",
    "s1431": "\\nVariable validation\\n",
    "s1432": "\\nState validation\\n",
    "s1433": " Validator",
    "s1434": "### States",
    "s1435": "- No transition",
    "s1436": "Idle state",
    "s1437": "Action name",
    "s1438": "Error code",
    "s1439": "Error flag",
    "s1440": "Add flag",
    "s1441": "Understood",
    "s1442": "Stop event",
    "s1443": "Apply all changes",
    "s1444": "Understood",
    "s1445": "New target",
    "s1446": "Validated",
    "s1447": "Temperature sensor value",
    "s1448": "Confirmed",
    "s1449": "Start event",
    "s1450": "Power ON processing",
    "s1451": "Power ON state",
    "s1452": "Power ON request",
    "s1453": " Exact match",
    "s1454": "Hello",
    "s1455": "Data processing",
    "s1456": "Operation mode",
    "s1457": "For reference",
    "s1458": "Add variable",
    "s1459": "Apply change",
    "s1460": "New condition",
    "s1461": "Validation severity",
    "s1462": "Add state",
    "s1463": "State type",
    "s1464": "Update settings",
    "s1465": "Delete transition",
    "s1466": "Update transition",
    "s1467": "Add transition",
    "s1468": " Model",
    "s1469": "By the way",
    "s1470": "That is all",
    "s1471": "Fix method",
    "s1472": "Stop processing",
    "s1473": "Analysis result",
    "s1474": "Interrupt",
    "s1475": "Running state",
    "s1476": "Validation issue",
    "s1477": "Validation result",
    "s1478": "Array style",
    "s1479": "Start processing",
    "s1480": "Start request",
    "s1481": "is.",
    "s1482": "I think",
    "s1483": "Considering",
    "s1484": "Note,",
    "s1485": "Yes,",
    "s1486": "Queue",
    "s1487": "Flag",
    "s1488": "The above is",
    "s1489": "Below",
    "s1490": "The following is",
    "s1491": "Fix proposal",
    "s1492": "Not set",
    "s1493": "Struct",
    "s1494": "Pressure value",
    "s1495": "Temperature value",
    "s1496": "Humidity value",
    "s1497": "Optional",
    "s1498": "Solution",
    "s1499": "is",
    "s1500": "does",
    "s1501": "Corresponds",
    "s1502": "Required",
    "s1503": "Proposal",
    "s1504": "Condition",
    "s1505": "Supplement",
    "s1506": "Transition",
    "s1507": "Critical",
    "s1508": "Start",
    "s1509": "System status",
    "s1510": "Startup request",
    "s1511": "UART receive queue",
    "s1512": "Error log output",
    "s1513": "Sensor initialization",
    "s1514": "Battery voltage",
    "s1515": "Error notification",
    "s1516": "Status",
    "s1517": "Data array",
    "s1518": "Data length",
    "s1519": "Mode",
    "s1520": " [v1.5 fix] Root fix for Transition positional arg bug",
    "s1521": " User-defined type (struct + bitfield + array)",
    "s1522": " Auto-register timer variables as globals",
    "s1523": "Sample data generation (business logic layer)",
    "s1524": "Timer0 interrupt flag clear register",
    "s1525": " Global variables (array support)",
    "s1526": "System status struct",
    "s1527": "Timer0 IRQ flag",
    "s1528": "Data packet struct",
    "s1529": "System timer base",
    "s1530": "Receive data buffer",
    "s1531": "100ms timer",
    "s1532": "1ms timer expired",
    "s1533": "1ms period timer",
    "s1534": "Timer0 interrupt",
    "s1535": "Mode indication flag",
    "s1536": "High-speed 1ms timer",
    "s1537": "10ms timer",
    "s1538": "Data packet",
    "s1539": "Startup request flag",
    "s1540": "Power ON flag",
    "s1541": "High-speed timer base",
    "s1542": "Receive buffer",
    "s1543": "1s timer",
    "s1544": "Timer expired",
    "s1545": "Mode indication",
    "s1546": "To error",
    "s1547": "Retry",
    "s1548": "Stopped state",
    "s1549": "To stop",
    "s1550": "Running",
    "s1551": "Ignore",
    "s1552": "Startup",
    "s1553": "Currently, please use statable/xml_io.py.",
    "s1554": "\\n    State transition definition\\n    [v1.6 change] kw_only=True\\n    [v2.0 known constraint: transition_type is reserved]\\n",
    "s1555": "\\nStaTable parser (unimplemented stub)\\n",
    "s1556": "\\n    Role function (implements conditions and actions together)\\n",
    "s1557": "\\nXML I/O (project settings / layer priority / namespace)\\n",
    "s1558": "Interrupt handler definition\\n    used_role_functions / used_variables (auto-extracted)\\n",
    "s1559": "Register timer base variables as global variables.\\n",
    "s1560": "\\n    Always normalize pre_actions / else_actions to List[str].\\n",
    "s1561": "\\n    Sanitize the Mermaid label string.\\n",
    "s1562": "\\nStaTable data model layer\\n",
    "s1563": "\\n    Load state transition data from an Excel file (not implemented)\\n",
    "s1564": "\\n    Load state transition data from a JSON file (not implemented)\\n",
    "s1565": "\\n    Load state transition data from a CSV file (not implemented)\\n",
    "s1566": "\\n    Generate a Mermaid stateDiagram-v2 string from StateMachine.\\n",
    "s1567": "\\n    libcntrl.RoleFunction only accepts name/title/description.\\n",
    "s1568": "\\n        Old form 'Driver_Init' -> namespace='Driver', name='Init'\\n",
    "s1569": "Management class for globals, flags, interrupts, resources, timers, queues, custom types",
    "s1570": "        Example: \\\"Halt --> Active : RETRY\\\"",
    "s1571": " Interrupts: used_role_functions support",
    "s1572": " Interrupts: used_role_functions restore",
    "s1573": "Data model for globals, flags, interrupts, resources, timers, custom types",
    "s1574": "Save project to XML file (including shared library)",
    "s1575": " Legacy migration: namespace unset + layer prefix",
    "s1576": " Characters causing problems in Mermaid labels:",
    "s1577": "For GUI display / ISR reference",
    "s1578": " RoleFunctions: namespace loading",
    "s1579": " Generate only with accepted arguments",
    "s1580": " Preserve existing description / title",
    "s1581": " Add namespace attribute to RoleFunctions",
    "s1582": " Normalization: convert strings to lists",
    "s1583": "        -> parse fails if double [ ]",
    "s1584": "   newline label only valid on one line",
    "s1585": "        -> parse error due to : in title",
    "s1586": " ---- Guard condition (shortened) ----",
    "s1587": " namespace added as keyword argument",
    "s1588": " state_machine.py (depends on model)",
    "s1589": "   : misidentified as label separator",
    "s1590": " Mermaid label sanitization (v2.0 added)",
    "s1591": " Reserved fields",
    "s1592": "Exception indicating parser.py features not implemented",
    "s1593": "State transition event",
    "s1594": "   quote misidentified as label end",
    "s1595": " model.py (no dependencies) should be loaded first",
    "s1596": "Show long conditions abbreviated",
    "s1597": "        may conflict with condition block notation",
    "s1598": "   backquote may be misidentified as code block",
    "s1599": " Detect and merge old data split into chars",
    "s1600": " Old version compatibility (no namespace)",
}

BATCHES["batch9"] = {
    "s1601": " ---- Title (other than untitled) ----",
    "s1602": " Shared library (None if import fails)",
    "s1603": " global_defs.py (no dependencies)",
    "s1604": " Normalization (merge if split)",
    "s1605": " The following are placeholders.",
    "s1606": "parse_excel is not implemented.",
    "s1607": " Layer name (e.g., \\\"Driver\\\")",
    "s1608": " Helper: string/list normalization",
    "s1609": " No public API (not implemented)",
    "s1610": "Restore project settings from XML element",
    "s1611": "parse_json is not implemented.",
    "s1612": " ---- Output transition lines ----",
    "s1613": " Append ellipsis if 2nd line or later",
    "s1614": " Treat timer definition as authoritative",
    "s1615": " Do not call until implemented.",
    "s1616": "parse_csv is not implemented.",
    "s1617": "Convert project settings to XML element",
    "s1618": " ---- Event name ----",
    "s1619": " ---- Label combine ----",
    "s1620": " Restore used role functions and variables",
    "s1621": " Record used role functions and variables",
    "s1622": " No title -> show target",
    "s1623": " If newline, use only first line",
    "s1624": " Old field (compatibility)",
    "s1625": " Set additional attributes if they exist",
    "s1626": " Double quote -> single",
    "s1627": " Backquote -> single",
    "s1628": " Project settings -> XML",
    "s1629": " Shared library -> XML",
    "s1630": " Condition expression (symbol names)",
    "s1631": "User-defined types (structs, etc.)",
    "s1632": " Complete if group is unset",
    "s1633": " Colon -> full-width colon",
    "s1634": " Project save/load",
    "s1635": " Normalize consecutive whitespace",
    "s1636": " Project settings",
    "s1637": " Get raw list",
    "s1638": " Added: usage record",
    "s1639": " Load shared library",
    "s1640": " Execution priority (1-9)",
    "s1641": " Close bracket -> full-width",
    "s1642": " Open bracket -> full-width",
    "s1643": "Event source layer",
    "s1644": " else action",
    "s1645": "Event: (complete)",
    "s1646": " Get group name",
    "s1647": " Project settings",
    "s1648": " Layer description (optional)",
    "s1649": "Event delivery method",
    "s1650": " Layer settings",
    "s1651": " Base timer variable",
    "s1652": " Newline -> space",
    "s1653": " Unimplemented marker",
    "s1654": " Derived timer variable",
    "s1655": "Struct member definition",
    "s1656": " Normal list",
    "s1657": " Pre-transition processing",
    "s1658": ":",
    "s1659": "[",
    "s1660": "]",
}


def build_flat_map(batches):
    flat = {}
    for batch_name, mapping in batches.items():
        if not mapping:
            continue
        for sid, en in mapping.items():
            if sid in flat and flat[sid] != en:
                print(f"[WARN] duplicate id {sid} in {batch_name}", file=sys.stderr)
            flat[sid] = en
    return flat


def apply_translations(data, flat, force=False):
    applied = 0
    skipped_existing = 0
    seen_ids = set()
    for entry in data.get("strings", []):
        sid = entry.get("id")
        if sid not in flat:
            continue
        seen_ids.add(sid)
        current = entry.get("english", "").strip()
        if current and not force:
            skipped_existing += 1
            continue
        entry["english"] = flat[sid]
        applied += 1
    unknown_ids = sorted(set(flat.keys()) - seen_ids)
    return applied, skipped_existing, unknown_ids


def main():
    parser = argparse.ArgumentParser(description="Apply translation batches")
    parser.add_argument("--input", default="translations.json")
    parser.add_argument("--output", default=None)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()

    input_path = PROJECT_ROOT / args.input
    output_path = PROJECT_ROOT / (args.output or args.input)

    if not input_path.exists():
        print(f"ERROR: {input_path} not found", file=sys.stderr)
        return 1

    data = json.loads(input_path.read_text(encoding="utf-8"))
    flat = build_flat_map(BATCHES)
    total_entries = len(data.get("strings", []))
    total_batch = len(flat)

    non_empty = [k for k, v in BATCHES.items() if v]
    empty = [k for k, v in BATCHES.items() if not v]

    print("=== apply_batch.py ===")
    print(f"Input           : {input_path}")
    print(f"Output          : {output_path}")
    print(f"Batches (loaded): {', '.join(non_empty) or '(none)'}")
    if empty:
        print(f"Batches (empty) : {', '.join(empty)}")
    print(f"Batch entries   : {total_batch}")
    print(f"JSON entries    : {total_entries}")
    print(f"Mode            : {'DRY-RUN' if args.dry_run else 'APPLY'}"
          f"{' (force)' if args.force else ''}")
    print()

    if total_batch == 0:
        print("No translations to apply.")
        return 1

    applied, skipped, unknown = apply_translations(data, flat, force=args.force)

    print(f"Applied         : {applied}")
    print(f"Skipped (exists): {skipped}")
    if unknown:
        print(f"IDs not in JSON : {len(unknown)}")
        for sid in unknown[:10]:
            print(f"  - {sid}")
        if len(unknown) > 10:
            print(f"  ... and {len(unknown) - 10} more")
    print()

    total_en = sum(1 for e in data.get("strings", [])
                   if e.get("english", "").strip())
    pct = (total_en * 100) // max(total_entries, 1)
    print(f"Coverage        : {total_en}/{total_entries} ({pct}%)")

    if args.dry_run:
        print()
        print("Dry-run: no file written.")
        return 0

    output_path.write_text(
        json.dumps(data, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"Wrote           : {output_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())