/**
 * @file    statable_timer.c
 * @brief   Timer processing
 *
 * @note    Code auto-generated by StaTable
 *          - Manual editing is not recommended
 *          - To modify, use StaTable
 *
 * @date    2026-09-19 22:08:36
 */

/*==============================================================
 *  Include files
 *==============================================================*/

#include "statable_types_common.h"
#include "Driver/statable_types_Driver.h"
#include "Middleware/statable_types_Middleware.h"
#include "Application/statable_types_Application.h"

/*==============================================================
 *  Type definitions
 *==============================================================*/



/*==============================================================
 *  Initialization function
 *==============================================================*/

/**
 * @brief  Timer variable initialization
 * @param  ctx  System context pointer
 */
void Timer_Init(SystemContext_t *ctx)
{
    if (ctx == NULL) {
        return;
    }
    LOG_DEBUG("Enter Timer_Init");

    ctx->data.g_system_tick = 0;
    ctx->data.g_tick_10ms = 0;

    LOG_DEBUG("Exit Timer_Init");
}

/*==============================================================
 *  State transition functions
 *==============================================================*/

/**
 * @brief  Timer update processing
 * @param  ctx  System context pointer
 */
void Timer_Update(SystemContext_t *ctx)
{
    if (ctx == NULL) {
        return;
    }
    ctx->data.g_tick_10ms = (uint8_t)(ctx->data.g_system_tick / 10);
}