/**
 * @file    statable_event_queue.c
 * @brief   Event queue implementation
 *
 * @note    Code auto-generated by StaTable
 *          - Manual editing is not recommended
 *          - To modify, use StaTable
 *
 * @date    2026-09-20 11:36:09
 */

/*==============================================================
 *  Include files
 *==============================================================*/

#include "statable_types_common.h"
#include "Driver/statable_types_Driver.h"
#include "Middleware/statable_types_Middleware.h"
#include "Application/statable_types_Application.h"

/* No event queue definitions */