/**
 * @file    statable_types_common.h
 * @brief   Common type definitions for state transition system
 *
 * @note    Code auto-generated by StaTable
 *          - Manual editing is not recommended
 *          - To modify, use StaTable
 *
 * @date    2026-09-20 07:42:37
 */

#ifndef STATABLE_TYPES_COMMON_H
#define STATABLE_TYPES_COMMON_H

/*==============================================================
 *  Include files
 *==============================================================*/

#include <stdint.h>
#include <stdbool.h>
#include <string.h>

/*==============================================================
 *  Type definitions
 *==============================================================*/

/* Event flag definitions */
typedef enum {
    FLAG_EVT_INIT_DONE = 0,    /* Init done Title: Init done */
    FLAG_EVT_ERROR = 1,    /* Error occurred Title: Error flag */
    FLAG_MAX           /* element count (for system use) */
} FLAG_t;


/*==============================================================
 *  System structs
 *==============================================================*/

/* Global variable struct */
/* Manages variables shared across the system */
typedef struct {
    /* === System === */
    /* General counter */
    uint32_t counter;
    /* Error code */
    uint8_t error_code;
    /* Retry counter */
    uint8_t retry_count;
    /* Running flag */
    bool running;

    /* === Timer === */
    /* Timer base [1ms] */
    volatile uint32_t g_system_tick;
    /* Derived timer [10ms] */
    uint8_t g_tick_10ms;
} SystemData_t;

/* Event flag struct */
/* Manages flags indicating event occurrences */
typedef struct {
    /* === System === */
    /* Init done */
    uint8_t EVT_INIT_DONE;
    /* Error occurred */
    uint8_t EVT_ERROR;
} EventFlags_t;

/* System context struct */
/* Integrates global variables and event flags */
typedef struct {
    SystemData_t data;     /* global variables */
    EventFlags_t flags;    /* event flags */
    uint16_t pending_event;         /* pending event */
    bool pending_event_valid;       /* pending event valid flag */
} SystemContext_t;

/* Generic transition context (for common role functions across layers) */
/* Same layout as each layer's TransitionContext_<Layer>_t */
typedef struct {
    uint16_t from_state;   /* source state (cast from layer enum) */
    uint16_t event;        /* event (cast from layer enum) */
} TransitionContext_t;


/* ============================================================== */
/*  Pending event control                                         */
/* ============================================================== */

/* Event fire macro */
/* Used within role functions: FIRE_EVENT(ctx, EVENT_XXX_YYY); */
#define FIRE_EVENT(ctx, evt)  do { \
    (ctx)->pending_event = (uint16_t)(evt); \
    (ctx)->pending_event_valid = true; \
} while(0)

/* Upper limit for consecutive pending event processing */
/* Infinite loop prevention. Can be overridden at build time via -D */
#ifndef MAX_CONSECUTIVE_PENDING_EVENTS
#define MAX_CONSECUTIVE_PENDING_EVENTS 16
#endif


/*==============================================================
 *  Variable access macros
 *==============================================================*/

#define DATA_COUNTER(ctx)    ((ctx)->data.counter)
#define DATA_ERROR_CODE(ctx)    ((ctx)->data.error_code)
#define DATA_RETRY_COUNT(ctx)    ((ctx)->data.retry_count)
#define DATA_RUNNING(ctx)    ((ctx)->data.running)
#define DATA_G_SYSTEM_TICK(ctx)    ((ctx)->data.g_system_tick)
#define DATA_G_TICK_10MS(ctx)    ((ctx)->data.g_tick_10ms)
#define FLAG_EVT_INIT_DONE(ctx)   ((ctx)->flags.EVT_INIT_DONE)
#define FLAG_EVT_ERROR(ctx)   ((ctx)->flags.EVT_ERROR)

/*==============================================================
 *  Common function declarations
 *==============================================================*/

/**
 * @brief  Initialize SystemContext_t (implemented in statable_init.c)
 * @param  ctx  System context pointer
 */
void SystemContext_Init(SystemContext_t *ctx);

/**
 * @brief  Initialize timer variables (implemented in statable_timer.c)
 * @param  ctx  System context pointer
 */
void Timer_Init(SystemContext_t *ctx);

/**
 * @brief  Update derived timer variables (implemented in statable_timer.c)
 * @param  ctx  System context pointer
 */
void Timer_Update(SystemContext_t *ctx);

#endif /* STATABLE_TYPES_COMMON_H */