/**
 * @file    statable_init.c
 * @brief   Initialization processing
 *
 * @note    Code auto-generated by StaTable
 *          - Manual editing is not recommended
 *          - To modify, use StaTable
 *
 * @date    2026-09-19 23:27:07
 */

/*==============================================================
 *  Include files
 *==============================================================*/

#include "statable_types_common.h"
#include "Driver/statable_types_Driver.h"
#include "Middleware/statable_types_Middleware.h"
#include "Application/statable_types_Application.h"

/*==============================================================
 *  Initialization function
 *==============================================================*/

/**
 * @brief  System context initialization
 * @param  ctx  System context pointer
 */
void SystemContext_Init(SystemContext_t *ctx)
{
    /* NULL check */
    if (ctx == NULL) {
        LOG_ERROR("NULL pointer: ctx");
        return;
    }

    LOG_DEBUG("Enter SystemContext_Init");

    /* Initialize global variables */
    ctx->data.counter = 0;
    ctx->data.error_code = 0;
    ctx->data.retry_count = 0;
    ctx->data.running = false;
    ctx->data.g_system_tick = 0;
    ctx->data.g_tick_10ms = 0;

    /* Initialize event flags */
    ctx->flags.EVT_INIT_DONE = 0;
    ctx->flags.EVT_ERROR = 0;

    /* Initialize pending event */
    ctx->pending_event = 0;
    ctx->pending_event_valid = false;

    LOG_DEBUG("Exit SystemContext_Init");
}