/**
 * @file    statable_event_queue.c
 * @brief   Event queue implementation
 *
 * @note    Code auto-generated by StaTable
 *          - Manual editing is not recommended
 *          - To modify, use StaTable
 *
 * @date    2026-09-19 17:26:55
 */

/*==============================================================*/
 *  Include files
/*==============================================================*/

#include "statable_types_common.h"
#include "Application/statable_types_Application.h"

/* No event queue definitions */