/**
 * @file    statable_interrupt.c
 * @brief   Interrupt handler ISR
 *
 * @note    Code auto-generated by StaTable
 *          - Manual editing is not recommended
 *          - To modify, use StaTable
 *
 * @date    2026-09-20 10:25:08
 */

/*==============================================================
 *  Include files
 *==============================================================*/

#include "statable_all.h"

/*==============================================================
 *  State transition functions
 *==============================================================*/

/**
 * @brief  TIMER0 interrupt handler
 * @note   1ms timer
 */
void ISR_TIMER0(void)
{

    /* ===== Context reference (auto-generated) ===== */
    SystemContext_t *ctx = &g_ctx;
    (void)ctx;

    /* ===== Entry log ===== */
    LOG_DEBUG("Enter ISR: TIMER0");

    /* ===== Actions (auto-generated) ===== */
    ctx->data.g_system_tick++;

    /* ===== User extension area ===== */
    /* [[STABLE_USER_CODE_START:TIMER0]] */
    /* Add user code here */
    /* [[STABLE_USER_CODE_END:TIMER0]] */

    /* ===== Exit log ===== */
    LOG_DEBUG("Exit ISR: TIMER0");
}
