/**
 * @file    statable_types_common.h
 * @brief   Common type definitions for state transition system
 *
 * @note    Code auto-generated by StaTable
 *          - Manual editing is not recommended
 *          - To modify, use StaTable
 *
 * @date    2026-09-18 21:42:39
 */

#ifndef STATABLE_TYPES_COMMON_H
#define STATABLE_TYPES_COMMON_H

/*==============================================================*/
 *  Include files
/*==============================================================*/

#include <stdint.h>
#include <stdbool.h>
#include <string.h>

/*==============================================================*/
 *  Type definitions
/*==============================================================*/

/*==============================================================*/
 *  System structs
/*==============================================================*/

/* Global variable struct */
/* Manages variables shared across the system */
typedef struct {
    /* === System === */
    /* 汎用カウンタ */
    uint32_t counter;
    /* エラーコード */
    uint8_t error_code;
    /* リトライ回数 */
    uint8_t retry_count;
    /* RX 準備完了 */
    bool rx_ready;
    /* RX 受信データ */
    uint8_t rx_data;

    /* === Timer === */
    /* タイマ基準 [1ms] */
    volatile uint32_t g_system_tick;
    /* 派生タイマ [10ms] */
    uint8_t g_tick_10ms;
} SystemData_t;

/* Event flag struct */
/* Manages flags indicating event occurrences */
typedef struct {
    /* === System === */
    /* 初期化完了 */
    uint8_t EVT_INIT_DONE;
    /* エラー発生 */
    uint8_t EVT_ERROR;
} EventFlags_t;

/* System context struct */
/* Integrates global variables and event flags */
typedef struct {
    SystemData_t data;     /* global variables */
    EventFlags_t flags;    /* event flags */
    uint16_t pending_event;         /* pending event */
    bool pending_event_valid;       /* pending event valid flag */
} SystemContext_t;

/* Generic transition context (for common role functions across layers) */
/* Same layout as each layer's TransitionContext_<Layer>_t */
typedef struct {
    uint16_t from_state;   /* source state (cast from layer enum) */
    uint16_t event;        /* event (cast from layer enum) */
} TransitionContext_t;


/* ============================================================== */
/*  Pending event control                                         */
/* ============================================================== */

/* Event fire macro */
/* Used within role functions: FIRE_EVENT(ctx, EVENT_XXX_YYY); */
#define FIRE_EVENT(ctx, evt)  do { \
    (ctx)->pending_event = (uint16_t)(evt); \
    (ctx)->pending_event_valid = true; \
} while(0)

/* Upper limit for consecutive pending event processing */
/* Infinite loop prevention. Can be overridden at build time via -D */
#ifndef MAX_CONSECUTIVE_PENDING_EVENTS
#define MAX_CONSECUTIVE_PENDING_EVENTS 16
#endif


/*==============================================================*/
 *  Variable access macros
/*==============================================================*/

#define DATA_COUNTER(ctx)    ((ctx)->data.counter)
#define DATA_ERROR_CODE(ctx)    ((ctx)->data.error_code)
#define DATA_RETRY_COUNT(ctx)    ((ctx)->data.retry_count)
#define DATA_RX_READY(ctx)    ((ctx)->data.rx_ready)
#define DATA_RX_DATA(ctx)    ((ctx)->data.rx_data)
#define DATA_G_SYSTEM_TICK(ctx)    ((ctx)->data.g_system_tick)
#define DATA_G_TICK_10MS(ctx)    ((ctx)->data.g_tick_10ms)
#define FLAG_EVT_INIT_DONE(ctx)   ((ctx)->flags.EVT_INIT_DONE)
#define FLAG_EVT_ERROR(ctx)   ((ctx)->flags.EVT_ERROR)

#endif /* STATABLE_TYPES_COMMON_H */